// Phase 6 #6 — Codex config artefact generator.
//
// Output shape: a TOML document the operator copies into
// `~/.codex/config.toml` (or layers via Codex's config-merge mechanism).
// We do NOT emit a complete Codex config: only the harness-managed
// hook stanzas the policy pack contributed. Operators keep their own
// model/auth/sandbox config separately; harness owns hook wiring only.
//
// File layout under `harness.generated/codex/`:
//   - config.toml: the harness-managed hook stanzas + a banner header
//                  explaining the merge-into-codex contract.
//
// Stable-output rules (load-bearing for byte-equivalent regeneration on
// a no-op apply):
//   - Hook entries sorted by event then by command.
//   - No timestamps, hostnames, or other run-specific data.
//
// What we deliberately do NOT do:
//   - Try to merge into an existing `~/.codex/config.toml`. The
//     operator owns that file; harness apply writes its own copy under
//     harness.generated/codex/ and the operator decides how to compose.
//     `harness apply --target <path>` with --runtime codex is rejected
//     (see apply.ts).
//   - Map Claude Code's permission-block to Codex's sandbox profile.
//     Codex permission shaping is Phase 6 #6 follow-up scope; for v1
//     the hooks alone are the enforcement.

import type { Hook, Manifest } from "../../schema/index.js";
import { expandCodexHookMatchPattern } from "../../runtime/tool-name-aliases.js";
import { buildMemoryRouterHook } from "./generate-settings.js";

export interface CodexConfigResult {
  content: string;
  warnings: string[];
}

const HEADER = [
  "# Generated by harness apply --runtime codex.",
  "# DO NOT EDIT: re-run `harness apply --runtime codex` to regenerate.",
  "#",
  "# Merge into your ~/.codex/config.toml: copy the [[hooks.*]] entries below",
  "# under your existing config, or include this file from your config via",
  "# Codex's config-merge mechanism. Operator-owned settings (model, auth,",
  "# sandbox profile) stay in your own config; harness owns hook wiring only.",
  "#",
  "# Wire format the harness adapter scripts expect on stdin (per",
  '# docs/policy-packs/understanding-before-execution.md "Adapter notes /',
  '# Codex"):',
  "#",
  "#   { session_id?: string, tool_name?: string, raw_input?: any, event?: string }",
  "#",
  "# PreToolUse blocker exit-code contract: 0 = allow, 2 = block (with reason",
  "# on stderr). UserPromptSubmit injector emits the instruction template on",
  "# stdout for Codex to prepend to additional_instructions.",
  "",
].join("\n");

// Control-character regex covering U+0000..U+001F + U+007F. Constructed
// programmatically so the source file stays free of literal control
// bytes (which other tooling tends to mangle on edit).
const CONTROL_CHAR_RE = new RegExp(`[\\u0000-\\u001f\\u007f]`, "g");

function escapeTomlString(s: string): string {
  // Basic-string escapes per TOML 1.0: backslash and double-quote,
  // plus every control char in U+0000..U+001F + U+007F. Tab/CR/LF
  // and BS/FF use shorthand escapes; the rest fall back to \uXXXX.
  // Hook fields are free-form `z.string().min(1)` and may carry a
  // stray newline (multi-line description) or a regex backreference
  // we cannot trust at face value; defence-in-depth is cheaper than
  // a parse error downstream.
  let out = s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  out = out.replace(CONTROL_CHAR_RE, (ch) => {
    switch (ch) {
      case "\n":
        return "\\n";
      case "\r":
        return "\\r";
      case "\t":
        return "\\t";
      case "\b":
        return "\\b";
      case "\f":
        return "\\f";
      default:
        return `\\u${ch.charCodeAt(0).toString(16).padStart(4, "0")}`;
    }
  });
  return out;
}

function tomlString(s: string): string {
  return `"${escapeTomlString(s)}"`;
}

function eventKey(event: string): string {
  // Codex hook keys conventionally use snake_case. Map Claude-Code's
  // CamelCase event names so the emitted TOML reads naturally to a
  // Codex operator. Unknown events pass through unchanged so a future
  // event the schema accepts but this generator hasn't learned about
  // is not silently dropped.
  switch (event) {
    case "UserPromptSubmit":
      return "user_prompt_submit";
    case "PreToolUse":
      return "pre_tool_use";
    case "Stop":
      return "stop";
    case "PostToolUse":
      return "post_tool_use";
    case "SessionStart":
      return "session_start";
    default:
      return event;
  }
}

function emitHook(h: Hook): string {
  const lines: string[] = [];
  lines.push(`[[hooks.${eventKey(h.event)}]]`);
  lines.push(`name = ${tomlString(h.name)}`);
  lines.push(`command = ${tomlString(h.command)}`);
  if (h.match !== undefined) {
    lines.push(`match = ${tomlString(expandCodexHookMatchPattern(h.match))}`);
  }
  lines.push(`timeout_ms = ${h.budget_ms}`);
  if (h.blocking === "hard") {
    lines.push("blocking = true");
  } else if (h.blocking === "soft") {
    lines.push("blocking = false  # soft");
  } else {
    lines.push("blocking = false");
  }
  if (h.description !== undefined && h.description.length > 0) {
    lines.push(`description = ${tomlString(h.description)}`);
  }
  return lines.join("\n");
}

export function generateCodexConfig(manifest: Manifest): CodexConfigResult {
  const warnings: string[] = [];
  // Same memory.router projection as generate-settings.ts so the Codex
  // operator gets per-prompt augmentation wired into their config.toml
  // alongside the standard pack hooks (PR #203, agent-tasks/eefbcaa8).
  const routerHook = buildMemoryRouterHook(manifest);
  const allHooks = routerHook
    ? [...manifest.hooks, routerHook]
    : manifest.hooks;
  const hooks = [...allHooks].sort((a, b) => {
    if (a.event !== b.event) return a.event < b.event ? -1 : 1;
    return a.command < b.command ? -1 : a.command > b.command ? 1 : 0;
  });
  // Surface a warning for hook entries that carry path_match / bash_match
  // filters; we do not project those into the emitted TOML (the harness
  // schema treats them as documentation that the underlying script
  // enforces internally, identical to the Claude Code projection in
  // generate-settings.ts). The warning makes the silent-drop visible
  // to operators who might expect TOML-level filtering.
  for (const h of hooks) {
    if (h.path_match !== undefined) {
      warnings.push(
        `hook ${JSON.stringify(h.name)}: path_match is not projected into Codex config (script-side filter only)`,
      );
    }
    if (h.bash_match !== undefined) {
      warnings.push(
        `hook ${JSON.stringify(h.name)}: bash_match is not projected into Codex config (script-side filter only)`,
      );
    }
  }
  if (hooks.length === 0) {
    warnings.push(
      "manifest contributes no hooks; the emitted Codex config has no [[hooks.*]] entries",
    );
  }
  const body = hooks.map(emitHook).join("\n\n");
  const content = `${HEADER}${body}${body.length > 0 ? "\n" : ""}`;
  return { content, warnings };
}
