// Phase 6 #6 — Codex config artefact generator.
//
// Output shape: a TOML document that `harness apply --runtime codex
// --install` can merge into `~/.codex/config.toml` as a marked
// harness-managed block. Operators may also copy it manually or layer it
// via Codex's config-merge mechanism.
// We do NOT emit a complete Codex config: only the harness-managed
// hook stanzas the policy pack contributed. Operators keep their own
// model/auth/sandbox config separately; harness owns hook wiring only.
//
// File layout under `harness.generated/codex/`:
//   - config.toml: the harness-managed hook stanzas + a banner header
//                  explaining the merge-into-codex contract.
//
// Stable-output rules (load-bearing for byte-equivalent regeneration on
// a no-op apply):
//   - Hook entries sorted by event then by command.
//   - No timestamps, hostnames, or other run-specific data.
//
// What we deliberately do NOT do:
//   - Own the complete `~/.codex/config.toml`. The installer path only
//     replaces the marked harness-managed block; operator settings stay
//     byte-for-byte outside that block. `harness apply --target <path>`
//     with --runtime codex is still rejected (see apply.ts) because
//     target is the Claude Code settings.json surface.
//   - Map Claude Code's permission-block to Codex's sandbox profile.
//     Codex permission shaping is Phase 6 #6 follow-up scope; for v1
//     the hooks alone are the enforcement.

import type { Hook, Manifest } from "../../schema/index.js";
import { expandCodexHookMatchPattern } from "../../runtime/tool-name-aliases.js";
import { buildMemoryRouterHook } from "./generate-settings.js";

export interface CodexConfigResult {
  content: string;
  warnings: string[];
}

/**
 * First line of the generated Codex `config.toml`. Exported so callers
 * that need to detect a harness-generated artifact (e.g. apply.ts's
 * last-apply baseline recovery) can pin against the same literal as
 * the emitter, instead of duplicating the string.
 */
export const CODEX_GENERATED_HEADER_LINE =
  "# Generated by harness apply --runtime codex.";

const HEADER = [
  CODEX_GENERATED_HEADER_LINE,
  "# DO NOT EDIT: re-run `harness apply --runtime codex` to regenerate.",
  "#",
  "# Install into ~/.codex/config.toml with:",
  "#   harness apply --runtime codex --install",
  "#",
  "# The installer replaces only the marked harness-managed hook block.",
  "# Operator-owned settings (model, auth, sandbox profile, MCP servers)",
  "# stay in your own config; harness owns hook wiring only.",
  "#",
  "# Wire format the harness adapter scripts expect on stdin (per",
  '# docs/policy-packs/understanding-before-execution.md "Adapter notes /',
  '# Codex"):',
  "#",
  "#   { session_id?: string, tool_name?: string, raw_input?: any, event?: string }",
  "#",
  "# PreToolUse blocker exit-code contract: 0 = allow, 2 = block (with reason",
  "# on stderr). UserPromptSubmit injector emits the instruction template on",
  "# stdout for Codex to prepend to additional_instructions.",
  "",
].join("\n");

// Control-character regex covering U+0000..U+001F + U+007F. Constructed
// programmatically so the source file stays free of literal control
// bytes (which other tooling tends to mangle on edit).
const CONTROL_CHAR_RE = new RegExp(`[\\u0000-\\u001f\\u007f]`, "g");

function escapeTomlString(s: string): string {
  // Basic-string escapes per TOML 1.0: backslash and double-quote,
  // plus every control char in U+0000..U+001F + U+007F. Tab/CR/LF
  // and BS/FF use shorthand escapes; the rest fall back to \uXXXX.
  // Hook fields are free-form `z.string().min(1)` and may carry a
  // stray newline (multi-line description) or a regex backreference
  // we cannot trust at face value; defence-in-depth is cheaper than
  // a parse error downstream.
  let out = s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  out = out.replace(CONTROL_CHAR_RE, (ch) => {
    switch (ch) {
      case "\n":
        return "\\n";
      case "\r":
        return "\\r";
      case "\t":
        return "\\t";
      case "\b":
        return "\\b";
      case "\f":
        return "\\f";
      default:
        return `\\u${ch.charCodeAt(0).toString(16).padStart(4, "0")}`;
    }
  });
  return out;
}

function tomlString(s: string): string {
  return `"${escapeTomlString(s)}"`;
}

function eventKey(event: string): string {
  // Codex 0.131.0's TOML schema uses protocol event names as table
  // keys (for example [[hooks.PreToolUse]]), not the legacy lower-snake
  // names harness emitted in the first Codex adapter. Unknown events
  // pass through unchanged so future schema additions are not dropped.
  switch (event) {
    case "UserPromptSubmit":
      return "UserPromptSubmit";
    case "PreToolUse":
      return "PreToolUse";
    case "Stop":
      return "Stop";
    case "PostToolUse":
      return "PostToolUse";
    case "SessionStart":
      return "SessionStart";
    default:
      return event;
  }
}

function codexTimeoutSeconds(h: Hook): number {
  const minimumSeconds = h.command.trim() === "harness policy intercept" ? 2 : 1;
  return Math.max(minimumSeconds, Math.ceil(h.budget_ms / 1000));
}

function emitCommandHook(h: Hook): string {
  const fields = [
    `type = "command"`,
    `command = ${tomlString(h.command)}`,
    `timeout = ${codexTimeoutSeconds(h)}`,
  ];
  return `{ ${fields.join(", ")} }`;
}

function tomlCommentText(s: string): string {
  return s.replace(CONTROL_CHAR_RE, " ").replace(/\s+/g, " ").trim();
}

function emitHook(h: Hook): string {
  const lines: string[] = [];
  lines.push(`# harness hook: ${tomlCommentText(h.name)} (budget_ms=${h.budget_ms})`);
  lines.push(`[[hooks.${eventKey(h.event)}]]`);
  if (h.match !== undefined) {
    lines.push(`matcher = ${tomlString(expandCodexHookMatchPattern(h.match))}`);
  }
  lines.push(`hooks = [${emitCommandHook(h)}]`);
  return lines.join("\n");
}

export function generateCodexConfig(manifest: Manifest): CodexConfigResult {
  const warnings: string[] = [];
  // Same memory.router projection as generate-settings.ts so the Codex
  // operator gets per-prompt augmentation wired into their config.toml
  // alongside the standard pack hooks (PR #203, agent-tasks/eefbcaa8).
  const routerHook = buildMemoryRouterHook(manifest);
  const allHooks = routerHook
    ? [...manifest.hooks, routerHook]
    : manifest.hooks;
  const hooks = [...allHooks].sort((a, b) => {
    if (a.event !== b.event) return a.event < b.event ? -1 : 1;
    return a.command < b.command ? -1 : a.command > b.command ? 1 : 0;
  });
  // Surface a warning for hook entries that carry path_match / bash_match
  // filters; we do not project those into the emitted TOML (the harness
  // schema treats them as documentation that the underlying script
  // enforces internally, identical to the Claude Code projection in
  // generate-settings.ts). The warning makes the silent-drop visible
  // to operators who might expect TOML-level filtering.
  for (const h of hooks) {
    if (h.path_match !== undefined) {
      warnings.push(
        `hook ${JSON.stringify(h.name)}: path_match is not projected into Codex config (script-side filter only)`,
      );
    }
    if (h.bash_match !== undefined) {
      warnings.push(
        `hook ${JSON.stringify(h.name)}: bash_match is not projected into Codex config (script-side filter only)`,
      );
    }
  }
  if (hooks.length === 0) {
    warnings.push(
      "manifest contributes no hooks; the emitted Codex config has no [[hooks.*]] entries",
    );
  }
  const body = hooks.map(emitHook).join("\n\n");
  const content = `${HEADER}${body}${body.length > 0 ? "\n" : ""}`;
  return { content, warnings };
}
