import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { parse as parseToml } from "smol-toml";
import { atomicWriteFile } from "../../io/atomic-write.js";
import { EX_FAIL, HarnessExitError } from "../exit-codes.js";

export const CODEX_MANAGED_SOURCE_PREFIX = "# Harness Codex hook wiring.";
export const CODEX_MANAGED_BEGIN = "# BEGIN harness-managed codex hooks";
export const CODEX_MANAGED_END = "# END harness-managed codex hooks";

/**
 * Thrown instead of a plain `Error` when the install refuses rather than
 * guesses (a duplicate/moved BEGIN marker, or a foreign table wedged
 * inside the managed block). Extends `HarnessExitError` so it carries the
 * repo's own exit-code convention (`EX_FAIL`) through `run()`'s top-level
 * catch without the generic "return 70" branch, and the CLI action can
 * recognize it by type to emit a structured `--json` error the same way
 * the other apply refusals (`target-exists-refuse`, `drift-refuse`) do.
 */
export class CodexInstallRefusalError extends HarnessExitError {
  constructor(
    message: string,
    public readonly configPath: string,
  ) {
    super(message, EX_FAIL);
    this.name = "CodexInstallRefusalError";
  }
}

const GENERATED_HEADER = "# Generated by harness apply --runtime codex.";
const LEGACY_HOOK_TABLE_RE =
  /^\[\[hooks\.(pre_tool_use|post_tool_use|user_prompt_submit|session_start|stop)\]\]$/;
const CURRENT_HOOK_TABLE_RE = /^\[\[hooks\.[A-Za-z][A-Za-z0-9_]*\]\]$/;
// A single, unquoted-or-quoted TOML bare/quoted key: `foo-bar_1`, a basic
// `"..."` string (escapes allowed), or a literal `'...'` string (no
// escapes, so a literal key may itself contain `[`, `]`, `"` or `#`
// verbatim, e.g. `'a[b'`).
const TOML_KEY = String.raw`(?:[A-Za-z0-9_-]+|"(?:[^"\\]|\\.)*"|'[^']*')`;
// A single-line TOML table header only: `[key]`, `[[key]]`, or a dotted
// path of keys (`[a.b."c d".'e[f']`), optionally surrounded by whitespace
// around the brackets and each dot, and optionally followed by whitespace
// and a trailing comment. Quote-aware so a key that itself contains `[`,
// `]`, `.` or `#` (a real path or filename used as a TOML key, e.g.
// `[projects."/Users/x/Photos [2024]"]`, `[plugins.'a[b']`) is still
// recognized as one header, instead of the bracket/hash inside the quotes
// being mistaken for the header's own delimiters. Deliberately excludes an
// array-continuation line such as `  [1, 2],` (no trailing comma allowed,
// and a bare numeric-looking segment such as `1` only ever matches as a
// single key with nothing after it, never as an array element) so a
// multi-line array/value sitting inside a still-owned harness hook table
// is never misread as a foreign table header ending the owned region
// early (task 6a037359).
const NON_HOOK_TABLE_RE = new RegExp(
  String.raw`^\[(?!\[hooks\.)\[?\s*${TOML_KEY}(?:\s*\.\s*${TOML_KEY})*\s*\]\]?\s*(?:#.*)?$`,
);
// Every emitted hook table is preceded by exactly this comment shape
// (generate-codex-config.ts's `emitHook`); used both to name removed hook
// blocks in the install summary and to detect a foreign table wedged
// between two harness hook tables (see `assertNoSplitBlock`).
const HARNESS_HOOK_COMMENT_PREFIX = "# harness hook: ";
const HOOK_ID_LINE_RE = /^# harness hook: (.+) \(budget_ms=\d+\)$/;

export interface CodexConfigInstallPlan {
  configPath: string;
  generatedPath: string;
  currentContent: string;
  nextContent: string;
  changed: boolean;
  summary: string;
  /**
   * Hook ids (the `# harness hook: <id>` comment text) that were present
   * in the old managed block and are absent from the new one. Reported so
   * an operator whose manifest still declares a pack does not silently
   * lose a hook (task 6a037359).
   */
  removedHookIds: string[];
  /**
   * Foreign (non harness-owned) table headers that sat between the old
   * managed block and a stray END marker, one representative header per
   * distinct top-level namespace. Populated only when the previous
   * install's END marker had drifted past foreign content (the
   * task-6a037359 bug): these are the sections that would have been
   * deleted under the old blind-END-trust logic and are now preserved
   * byte-for-byte instead.
   */
  foreignSectionsPreserved: string[];
}

export interface CodexConfigInstallResult extends CodexConfigInstallPlan {
  backupPath?: string;
  written: boolean;
}

export interface CodexConfigInstallOptions {
  configPath?: string;
  homeDir?: string;
  generatedPath: string;
  generatedContent: string;
  now?: Date;
}

export function defaultCodexConfigPath(homeDir?: string): string {
  return path.join(homeDir ?? os.homedir(), ".codex", "config.toml");
}

function lineStartAt(text: string, index: number): number {
  const prev = text.lastIndexOf("\n", Math.max(0, index - 1));
  return prev === -1 ? 0 : prev + 1;
}

function lineEndAfter(text: string, index: number): number {
  const next = text.indexOf("\n", index);
  return next === -1 ? text.length : next + 1;
}

function previousLine(
  text: string,
  lineStart: number,
): { start: number; text: string } | null {
  if (lineStart === 0) return null;
  const end = lineStart - 1;
  const start = lineStartAt(text, end);
  return { start, text: text.slice(start, end) };
}

/** 1-based line number of `index` within `text`, for operator-facing error text. */
function lineNumberAt(text: string, index: number): number {
  let n = 1;
  for (let i = 0; i < index && i < text.length; i += 1) {
    if (text[i] === "\n") n += 1;
  }
  return n;
}

type TripleDelim = '"""' | "'''" | null;

/** True when the character at `index` is escaped by an odd number of
 * immediately preceding backslashes (`\"` is escaped, `\\"` is not: the
 * first backslash escapes the second, leaving the quote bare). Only basic
 * (double-quoted) strings support this escape; literal (single-quoted)
 * strings never do. */
function isEscapedAt(line: string, index: number): boolean {
  let backslashes = 0;
  let j = index - 1;
  while (j >= 0 && line[j] === "\\") {
    backslashes += 1;
    j -= 1;
  }
  return backslashes % 2 === 1;
}

/**
 * Walks one physical line of TOML, tracking only what a caller needs to
 * decide whether the NEXT line is opaque multi-line-string content: which
 * triple-quote delimiter (if any) is open once this line ends. `delimIn`
 * is the delimiter already open when this line STARTS (from a preceding
 * multi-line string that has not yet closed); when non-null, this line's
 * own content is scanned only for that SAME delimiter closing it (task
 * 6a037359 L1: a basic `"""` string is closed only by another `"""`, never
 * by `'''`, and vice versa -- naively counting either delimiter's raw
 * occurrences, as the pre-fix code did, misreads a `'''` sitting inside an
 * open `"""` string, or a comment/single-line-string containing `'''` or
 * `"""`, as a real close).
 *
 * When `delimIn` is null, the line is scanned left to right: a bare `#`
 * (outside any string) starts a line comment and ends scanning (its
 * content, including any quote characters, is never code); a single-line
 * basic (`"`) or literal (`'`) string is skipped to its own closing quote
 * (escapes honored only for `"`) without inspecting its contents for
 * delimiters; a `"""`/`'''` not preceded by an escaped quote opens a
 * multi-line string of that type.
 */
function nextTripleDelim(rawLine: string, delimIn: TripleDelim): TripleDelim {
  let i = 0;
  const n = rawLine.length;
  let delim = delimIn;
  while (i < n) {
    if (delim !== null) {
      if (rawLine.startsWith(delim, i)) {
        if (delim === '"""' && isEscapedAt(rawLine, i)) {
          i += 1;
          continue;
        }
        delim = null;
        i += 3;
        continue;
      }
      if (delim === '"""' && rawLine[i] === "\\") {
        i += 2; // an escaped char inside a basic string can never itself
        continue; // start a real closing delimiter.
      }
      i += 1;
      continue;
    }
    const ch = rawLine[i];
    if (ch === "#") break; // line comment: nothing after it is code.
    if (rawLine.startsWith('"""', i)) {
      delim = '"""';
      i += 3;
      continue;
    }
    if (rawLine.startsWith("'''", i)) {
      delim = "'''";
      i += 3;
      continue;
    }
    if (ch === '"') {
      i += 1;
      while (i < n && rawLine[i] !== '"') {
        if (rawLine[i] === "\\") i += 1;
        i += 1;
      }
      i += 1; // consume the closing quote (or run to end if unterminated)
      continue;
    }
    if (ch === "'") {
      i += 1;
      while (i < n && rawLine[i] !== "'") i += 1;
      i += 1;
      continue;
    }
    i += 1;
  }
  return delim;
}

/**
 * The first line, at or after `from`, whose TRIMMED content is byte-equal
 * to `target` (not a raw substring search). A raw `text.indexOf(target,
 * from)` would also match `target` sitting mid-line inside unrelated
 * content; matching only whole trimmed lines rules that out. A line that
 * BEGAN inside an open TOML multi-line string (tracked via
 * `nextTripleDelim`, correctly distinguishing `"""` from `'''` and
 * ignoring delimiters inside a comment or a single-line string) is never
 * treated as a possible match, regardless of its trimmed text: a foreign
 * table's own multi-line string value may legitimately contain a line
 * that reads exactly like the harness END marker (task 6a037359) without
 * that being a real stray END. The triple-quote state is tracked only
 * from `from` onward (a string open before `from` is not detected), which
 * is correct for the caller's one use: `from` is always the start of the
 * first foreign table in the zone being searched, so any multi-line
 * string that matters here opens inside that zone, not before it.
 */
function findExactLine(text: string, target: string, from: number): number {
  let pos = from;
  let delim: TripleDelim = null;
  while (pos < text.length) {
    const lineEnd = lineEndAfter(text, pos);
    const rawLine = text.slice(pos, lineEnd);
    const startedInsideString = delim !== null;
    delim = nextTripleDelim(rawLine, delim);
    if (!startedInsideString && rawLine.trim() === target) return pos;
    pos = lineEnd;
  }
  return -1;
}

/** The first non-blank, non-comment line at or after `from` (bounded by
 * `limit`), trimmed. Used to name the offending foreign header in a
 * refusal message. */
function firstContentLine(text: string, from: number, limit: number): string | null {
  let pos = Math.max(from, 0);
  const end = Math.max(limit, from);
  while (pos < end) {
    const lineEnd = Math.min(lineEndAfter(text, pos), end);
    const trimmed = text.slice(pos, lineEnd).trim();
    if (trimmed !== "" && !trimmed.startsWith("#")) return trimmed;
    pos = lineEnd;
  }
  return null;
}

/**
 * Scans forward from `start` classifying each line as either still-owned
 * harness content or the start of foreign (non-harness) content, WITHOUT
 * relying on where (or whether) a `CODEX_MANAGED_END` marker sits. This is
 * what makes the region computation safe against a stray/misplaced END
 * (task 6a037359: `findManagedRange` used to trust `text.indexOf(END,
 * begin)` unconditionally, so an END marker that had drifted past
 * Codex-written tables such as `[hooks.state]` caused every foreign table
 * between BEGIN and that END to be deleted on the next install) and
 * against a config that has no END marker at all (the legacy shape).
 *
 * A run of blank/comment lines immediately followed by foreign content is
 * excluded from the owned region (backed off to the start of that run):
 * Codex, or an operator, may attach a comment to the table that follows,
 * and that comment must never be misread as harness commentary and folded
 * into the replaced block.
 *
 * A line is "foreign" exactly when it is a table header that is not one
 * of ours (`NON_HOOK_TABLE_RE`, mirroring the pre-existing legacy scan);
 * every other non-blank, non-comment line (a hook table's `matcher =` /
 * `hooks =` field, or an older schema's bare `command =` / `match =` /
 * `timeout_ms =` / `blocking =` field) is treated as still-owned content,
 * same as before this fix. A line that BEGAN inside an open TOML
 * multi-line string (`nextTripleDelim`) is always treated as still-owned
 * content too, regardless of what it looks like: a hook table's own
 * multi-line string value (or a foreign table's, once one is already
 * inside the owned region by construction -- this scanner only ever runs
 * from a position that is itself still-owned) may contain a line that
 * reads exactly like a comment, a blank line, or even the END marker
 * without that ending the region early (task 6a037359 L1).
 */
function scanOwnedContentEnd(
  text: string,
  start: number,
): { end: number; sawEndMarker: boolean } {
  let pos = start;
  let commentRunStart: number | null = null;
  let delim: TripleDelim = null;
  while (pos < text.length) {
    const lineEnd = lineEndAfter(text, pos);
    const rawLine = text.slice(pos, lineEnd);
    const startedInsideString = delim !== null;
    delim = nextTripleDelim(rawLine, delim);
    if (startedInsideString) {
      commentRunStart = null;
      pos = lineEnd;
      continue;
    }
    const trimmed = rawLine.trim();

    if (trimmed === CODEX_MANAGED_END) {
      return { end: lineEnd, sawEndMarker: true };
    }
    if (trimmed === "" || trimmed.startsWith("#")) {
      if (commentRunStart === null) commentRunStart = pos;
      pos = lineEnd;
      continue;
    }
    if (NON_HOOK_TABLE_RE.test(trimmed)) {
      return { end: commentRunStart ?? pos, sawEndMarker: false };
    }
    commentRunStart = null;
    pos = lineEnd;
  }
  return { end: pos, sawEndMarker: false };
}

/**
 * Refuses loudly (mirror case of the stray-END bug) when the zone between
 * `from` and `to` still contains a recognizable fragment of a harness
 * hook block: a second BEGIN/source-prefix marker, or a `# harness hook:`
 * comment. Either means a foreign table was wedged between two harness
 * hook tables, or the BEGIN marker moved, and the true block boundaries
 * can no longer be determined by a line scan; guessing risks reordering
 * or dropping harness- or foreign-owned bytes, so this throws instead. The
 * message names the resolved config path (never a hard-coded `~/.codex`),
 * the first foreign table header the scan found (`from` always sits at
 * one, see `scanOwnedContentEnd`), and the offending line that still
 * looks like harness content beyond it, so the operator can act without
 * guessing themselves. `hasEndMarker` distinguishes the two callers: when
 * `to` was derived from a real stray `CODEX_MANAGED_END` line, the fix
 * guidance can point at that marker; when there is no END marker anywhere
 * in the document (`to` is `text.length`), telling the operator to move
 * something below a marker that does not exist would be nonsensical, so a
 * different fix (add one, or move the table below the last harness hook
 * table) is offered instead (task 6a037359 L2).
 */
function assertNoSplitBlock(
  text: string,
  from: number,
  to: number,
  configPath: string,
  hasEndMarker: boolean,
): void {
  const zoneStart = Math.max(from, 0);
  const zoneEnd = Math.max(to, from);
  const zone = text.slice(zoneStart, zoneEnd);
  const markerOffsets = [CODEX_MANAGED_SOURCE_PREFIX, CODEX_MANAGED_BEGIN, HARNESS_HOOK_COMMENT_PREFIX]
    .map((marker) => zone.indexOf(marker))
    .filter((idx) => idx !== -1);
  if (markerOffsets.length === 0) return;

  const markerOffset = Math.min(...markerOffsets);
  const offendingLineStart = lineStartAt(text, zoneStart + markerOffset);
  const offendingLineEnd = lineEndAfter(text, zoneStart + markerOffset);
  const offendingLine = text.slice(offendingLineStart, offendingLineEnd).trim();
  const offendingLineNumber = lineNumberAt(text, offendingLineStart);
  const firstForeignHeader =
    firstContentLine(text, zoneStart, zoneStart + markerOffset) ?? "(unknown)";

  const guidance = hasEndMarker
    ? `Move ${firstForeignHeader} below the '${CODEX_MANAGED_END}' marker, or delete the lines ` +
      `between '${CODEX_MANAGED_BEGIN}' and '${CODEX_MANAGED_END}' so only harness-owned tables ` +
      "remain between them"
    : `Add a '${CODEX_MANAGED_END}' marker line right after the last harness hook table (before ` +
      `${firstForeignHeader}), or move ${firstForeignHeader} below the last harness hook table`;

  throw new CodexInstallRefusalError(
    `Codex config ${configPath} has a foreign table (${firstForeignHeader}) sitting before ` +
      `more harness-owned content: line ${offendingLineNumber} (${offendingLine}) still looks ` +
      "like part of the harness-managed hook block; refusing to guess the block boundaries. " +
      `${guidance}, then re-run \`harness apply --runtime codex --install\`. As a last resort, ` +
      `restore ${configPath} from the most recent .harness-backup-* file, but that discards any ` +
      "Codex state (hook trust entries, marketplaces, plugins) written to the file since that " +
      "backup.",
    configPath,
  );
}

function foreignSectionRootKey(headerLine: string): string {
  const inner = headerLine.replace(/^\[+/, "").replace(/\]+$/, "");
  const cut = inner.search(/[."]/);
  return cut === -1 ? inner : inner.slice(0, cut);
}

/** One representative header per distinct top-level foreign namespace
 * found between `from` and `to` (e.g. all `[hooks.state."..."]` sub-tables
 * collapse to one entry), in first-seen order. A namespace with more than
 * one table under it prints its representative header suffixed with a
 * `(N tables)` count (e.g. `[hooks.state] (3 tables)`) instead of silently
 * dropping the other N-1 headers, so the operator can tell "one table" from
 * "a whole namespace" preserved. */
function collectForeignSectionHeaders(
  text: string,
  from: number,
  to: number,
): string[] {
  const seenRoots = new Set<string>();
  const headers: string[] = [];
  const counts = new Map<string, number>();
  let pos = Math.max(from, 0);
  const limit = Math.max(to, from);
  let delim: TripleDelim = null;
  while (pos < limit) {
    const lineEnd = Math.min(lineEndAfter(text, pos), limit);
    const rawLine = text.slice(pos, lineEnd);
    const startedInsideString = delim !== null;
    delim = nextTripleDelim(rawLine, delim);
    if (startedInsideString) {
      pos = lineEnd;
      continue;
    }
    const trimmed = rawLine.trim();
    if (NON_HOOK_TABLE_RE.test(trimmed)) {
      const root = foreignSectionRootKey(trimmed);
      counts.set(root, (counts.get(root) ?? 0) + 1);
      if (!seenRoots.has(root)) {
        seenRoots.add(root);
        headers.push(trimmed);
      }
    }
    pos = lineEnd;
  }
  return headers.map((header) => {
    const root = foreignSectionRootKey(header);
    const count = counts.get(root) ?? 1;
    // More than one table collapses to this root: name the ROOT with a
    // wildcard (`[hooks.*] (3 tables)`) instead of the first table's own
    // full header, so the operator reads "a whole namespace, N tables"
    // rather than mistaking the printed header for the only table kept
    // (task 6a037359 L5). Exactly one table under a root still prints its
    // own full header, unchanged -- there is no namespace to summarize.
    return count > 1 ? `[${root}.*] (${count} tables)` : header;
  });
}

function extractHookIds(content: string): Set<string> {
  const ids = new Set<string>();
  for (const rawLine of content.split(/\r?\n/)) {
    const m = HOOK_ID_LINE_RE.exec(rawLine.trim());
    if (m?.[1] !== undefined) ids.add(m[1]);
  }
  return ids;
}

interface ManagedRange {
  start: number;
  end: number;
  /** A stray END-marker line beyond `end` to excise (task 6a037359). */
  strayEnd?: { start: number; end: number };
  foreignSectionsPreserved: string[];
}

function findManagedRange(text: string, configPath: string): ManagedRange | null {
  const begin = text.indexOf(CODEX_MANAGED_BEGIN);
  if (begin !== -1) {
    const secondBegin = text.indexOf(CODEX_MANAGED_BEGIN, begin + CODEX_MANAGED_BEGIN.length);
    if (secondBegin !== -1) {
      const secondBeginLineStart = lineStartAt(text, secondBegin);
      const secondBeginLineEnd = lineEndAfter(text, secondBegin);
      const secondBeginLine = text.slice(secondBeginLineStart, secondBeginLineEnd).trim();
      const secondBeginLineNumber = lineNumberAt(text, secondBeginLineStart);
      throw new CodexInstallRefusalError(
        `Codex config ${configPath} has more than one '${CODEX_MANAGED_BEGIN}' marker ` +
          `(a second one at line ${secondBeginLineNumber}: ${secondBeginLine}); refusing to ` +
          "guess which one is current. Delete the entire unwanted BEGIN/END pair -- including " +
          `its own '${CODEX_MANAGED_BEGIN}' and '${CODEX_MANAGED_END}' marker lines (and its ` +
          `'${CODEX_MANAGED_SOURCE_PREFIX}' source-prefix comment line, if it has one) -- ` +
          "keeping exactly one pair, then re-run `harness apply --runtime codex --install`. As " +
          `a last resort, restore ${configPath} from the most recent .harness-backup-* file, ` +
          "but that discards any Codex state (hook trust entries, marketplaces, plugins) " +
          "written to the file since that backup.",
        configPath,
      );
    }
    let start = lineStartAt(text, begin);
    const prev = previousLine(text, start);
    if (prev && prev.text.startsWith(CODEX_MANAGED_SOURCE_PREFIX)) {
      start = prev.start;
    }

    const contentStart = lineEndAfter(text, begin);
    const scan = scanOwnedContentEnd(text, contentStart);
    const end = scan.end;

    if (scan.sawEndMarker) {
      return { start, end, foreignSectionsPreserved: [] };
    }

    const strayIdx = findExactLine(text, CODEX_MANAGED_END, end);
    if (strayIdx === -1) {
      assertNoSplitBlock(text, end, text.length, configPath, false);
      const foreignSectionsPreserved = collectForeignSectionHeaders(text, end, text.length);
      return { start, end, foreignSectionsPreserved };
    }

    const strayLineStart = lineStartAt(text, strayIdx);
    const strayLineEnd = lineEndAfter(text, strayIdx);
    assertNoSplitBlock(text, end, strayLineStart, configPath, true);
    const foreignSectionsPreserved = collectForeignSectionHeaders(text, end, strayLineStart);
    return {
      start,
      end,
      strayEnd: { start: strayLineStart, end: strayLineEnd },
      foreignSectionsPreserved,
    };
  }

  const source = text.indexOf(CODEX_MANAGED_SOURCE_PREFIX);
  if (source !== -1) {
    const start = lineStartAt(text, source);
    const scan = scanOwnedContentEnd(text, start);
    const end = scan.end;
    const foreignSectionsPreserved = scan.sawEndMarker
      ? []
      : collectForeignSectionHeaders(text, end, text.length);
    return { start, end, foreignSectionsPreserved };
  }

  const generated = text.indexOf(GENERATED_HEADER);
  if (generated !== -1) {
    const start = lineStartAt(text, generated);
    const scan = scanOwnedContentEnd(text, start);
    const end = scan.end;
    const candidate = text.slice(start, end);
    if (
      candidate.includes("[[hooks.") ||
      candidate.includes("[[hooks.pre_tool_use]]")
    ) {
      const foreignSectionsPreserved = scan.sawEndMarker
        ? []
        : collectForeignSectionHeaders(text, end, text.length);
      return { start, end, foreignSectionsPreserved };
    }
  }

  return null;
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith("\n") ? s : `${s}\n`;
}

function buildManagedBlock(
  generatedContent: string,
  generatedPath: string,
): string {
  return [
    `${CODEX_MANAGED_SOURCE_PREFIX} Generated source: ${generatedPath}`,
    CODEX_MANAGED_BEGIN,
    ensureTrailingNewline(generatedContent).trimEnd(),
    CODEX_MANAGED_END,
    "",
  ].join("\n");
}

export function validateCodexManagedConfig(content: string): void {
  const lines = content.split(/\r?\n/);
  const legacyLine = lines.find((line) => {
    const trimmed = line.trim();
    return (
      LEGACY_HOOK_TABLE_RE.test(trimmed) ||
      trimmed.startsWith("timeout_ms =") ||
      trimmed.startsWith("blocking =") ||
      trimmed.startsWith("match =")
    );
  });
  if (legacyLine !== undefined) {
    throw new Error(
      `generated Codex config still uses legacy hook schema: ${legacyLine.trim()}`,
    );
  }

  const hookTableIndexes: number[] = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (CURRENT_HOOK_TABLE_RE.test(lines[i]!.trim())) hookTableIndexes.push(i);
  }
  if (hookTableIndexes.length === 0) return;

  for (let i = 0; i < hookTableIndexes.length; i += 1) {
    const start = hookTableIndexes[i]!;
    const end = hookTableIndexes[i + 1] ?? lines.length;
    const segment = lines.slice(start, end).join("\n");
    if (!segment.includes("hooks = [")) {
      throw new Error(
        `generated Codex hook table is missing hooks array: ${lines[start]!.trim()}`,
      );
    }
    if (
      !segment.includes('type = "command"') ||
      !/command = "([^"\\]|\\.)+"/.test(segment) ||
      !/timeout = [1-9][0-9]*/.test(segment)
    ) {
      throw new Error(
        `generated Codex hook table has invalid command hook shape: ${lines[start]!.trim()}`,
      );
    }
  }
}

const HOOK_TABLE_HEADER_RE = /^\[\[hooks\.([A-Za-z][A-Za-z0-9_]*)\]\]$/;

/**
 * For every `[[hooks.<Event>]]` table header found in `text` (in document
 * order, multi-line-string aware via `nextTripleDelim` so a header-looking
 * line inside a string value is never miscounted), records its 0-based
 * index within that event's array AND whether the header's own start
 * offset falls inside `range` (the text span `findManagedRange` treats as
 * harness-owned). Returns, per event, the set of indexes that are inside
 * that range -- i.e. the entries `assertConfigSemanticInvariant`'s
 * per-entry survival check does NOT require to survive unchanged, because
 * the installer is free to replace them (task 6a037359, Part A safety
 * net). Every index NOT in the returned set is "outside the managed
 * region" and must still be present, unchanged, in `next`.
 */
function computeOwnedHookEntryIndexes(
  text: string,
  range: { start: number; end: number } | null,
): Map<string, Set<number>> {
  const owned = new Map<string, Set<number>>();
  const eventCounts = new Map<string, number>();
  let pos = 0;
  let delim: TripleDelim = null;
  while (pos < text.length) {
    const lineEnd = lineEndAfter(text, pos);
    const rawLine = text.slice(pos, lineEnd);
    const startedInsideString = delim !== null;
    delim = nextTripleDelim(rawLine, delim);
    if (!startedInsideString) {
      const m = HOOK_TABLE_HEADER_RE.exec(rawLine.trim());
      if (m?.[1] !== undefined) {
        const event = m[1];
        const idx = eventCounts.get(event) ?? 0;
        eventCounts.set(event, idx + 1);
        if (range && pos >= range.start && pos < range.end) {
          const set = owned.get(event) ?? new Set<number>();
          set.add(idx);
          owned.set(event, set);
        }
      }
    }
    pos = lineEnd;
  }
  return owned;
}

/** Every harness-managed hook event array (`hooks.<Event>`, an ARRAY of
 * tables) removed from `doc.hooks`, keeping every other `hooks.*` key
 * (single tables such as `hooks.state`, or any future non-array key)
 * untouched. This is the "simplest robust definition" of what the
 * installer owns: everything else in the document -- including all of
 * `hooks.state` -- is not the installer's to change (task 6a037359, D-003
 * safety net). Non-object/array `doc` and a missing/non-object `hooks` are
 * returned as-is; there is nothing to strip. */
function stripManagedHookArrays(doc: unknown): unknown {
  if (typeof doc !== "object" || doc === null || Array.isArray(doc)) return doc;
  const obj = doc as Record<string, unknown>;
  const hooksRaw = obj.hooks;
  if (typeof hooksRaw !== "object" || hooksRaw === null || Array.isArray(hooksRaw)) return obj;
  const hooks = hooksRaw as Record<string, unknown>;
  const strippedHooks: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(hooks)) {
    if (Array.isArray(value)) continue;
    strippedHooks[key] = value;
  }
  const result: Record<string, unknown> = { ...obj };
  if (Object.keys(strippedHooks).length === 0) {
    // A document all of whose `hooks.*` keys were array-valued (the
    // common case: nothing but harness-managed event arrays) must strip
    // down to "no hooks key at all", the same as a document that never
    // had one, so the comparison never flags the mere PRESENCE of an
    // (empty, post-strip) `hooks` table as a semantic difference.
    delete result.hooks;
  } else {
    result.hooks = strippedHooks;
  }
  return result;
}

/** The path (as a dotted string once joined by the caller) to the first
 * value at which `a` and `b` differ, walking objects/arrays recursively
 * and comparing primitives (including `Date`/`TomlDate`, by their time
 * value) with `Object.is`; `null` means the two are deeply equal. Key
 * order follows `a`'s own insertion order first, then any key present
 * only in `b`, so the reported path is deterministic. */
function firstDifferingKeyPath(a: unknown, b: unknown, path: string[]): string[] | null {
  if (a instanceof Date || b instanceof Date) {
    const av = a instanceof Date ? a.getTime() : a;
    const bv = b instanceof Date ? b.getTime() : b;
    return Object.is(av, bv) ? null : path;
  }
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return path;
    for (let i = 0; i < a.length; i += 1) {
      const diff = firstDifferingKeyPath(a[i], b[i], [...path, String(i)]);
      if (diff) return diff;
    }
    return null;
  }
  if (typeof a === "object" && a !== null && typeof b === "object" && b !== null) {
    const aObj = a as Record<string, unknown>;
    const bObj = b as Record<string, unknown>;
    const aKeys = Object.keys(aObj);
    const bOnlyKeys = Object.keys(bObj).filter((k) => !aKeys.includes(k));
    for (const key of [...aKeys, ...bOnlyKeys]) {
      const diff = firstDifferingKeyPath(aObj[key], bObj[key], [...path, key]);
      if (diff) return diff;
    }
    return null;
  }
  return Object.is(a, b) ? null : path;
}

/**
 * The independent TOML-semantic safety net (task 6a037359, operator
 * redesign decision D-003): the byte-preserving text splice above stays
 * the source of truth for what gets WRITTEN, but before it is written
 * both `currentContent` and `nextContent` are parsed with `smol-toml` and
 * compared, and the install refuses rather than writes when the
 * comparison cannot establish that nothing outside the installer's own
 * ownership changed. This exists to catch a scanner defect (a shape the
 * line-based scan above mishandles) that would otherwise silently drop or
 * corrupt operator- or Codex-owned TOML content.
 *
 * What the installer owns, precisely: the harness-managed hook event
 * arrays, `[[hooks.<Event>]]`, both the ones a previous install wrote
 * (identified by `ownedHookEntries`, the entries physically inside the
 * managed text region) and the ones this install writes now. Two checks
 * enforce that boundary:
 *
 * 1. Whole-array-removed comparison: strip every ARRAY-valued key under
 *    `hooks` from both parsed documents (keeping `hooks.state` and any
 *    other single-table `hooks.*` key untouched) and deep-compare what
 *    remains. Any difference means the splice changed something outside
 *    the hook arrays it owns -- a foreign table, a Codex-written table
 *    like `hooks.state`, or any other top-level key.
 * 2. Per-entry survival: check 1 necessarily ignores the hook arrays
 *    themselves (the installer is expected to change those), which would
 *    hide a regression that drops a `[[hooks.<Event>]]` entry sitting
 *    OUTSIDE the managed region (an operator-authored hook table with no
 *    harness comment, for instance, positioned before BEGIN or after the
 *    tail). Every such "outside" entry in `current` must still appear, in
 *    order and deep-equal once parsed, as a subsequence of the
 *    corresponding array in `next`.
 *
 * Refuses via `CodexInstallRefusalError` naming the first differing key
 * path (check 1) or the offending event (check 2); the file is never
 * touched by this function, and a `--dry-run` plan that reaches this
 * check reports the same refusal a real install would (both call
 * `planCodexConfigInstall`, which is where this runs).
 */
export function assertConfigSemanticInvariant(
  currentContent: string,
  nextContent: string,
  configPath: string,
  ownedHookEntries: Map<string, Set<number>>,
): void {
  let currentDoc: unknown;
  try {
    currentDoc = parseToml(currentContent);
  } catch (err) {
    throw new CodexInstallRefusalError(
      `Codex config ${configPath} does not parse as TOML (${(err as Error).message}); ` +
        "refusing to install rather than guess whether every foreign table would be " +
        "preserved. Fix the file's existing TOML syntax (or restore it from a " +
        ".harness-backup-* file), then re-run `harness apply --runtime codex --install`.",
      configPath,
    );
  }

  let nextDoc: unknown;
  try {
    nextDoc = parseToml(nextContent);
  } catch (err) {
    throw new CodexInstallRefusalError(
      `The Codex config harness would write to ${configPath} does not parse as TOML ` +
        `(${(err as Error).message}); refusing to write a config that would not load. This ` +
        "points at a bug in the generated hook block or the install itself, not at the " +
        "existing file.",
      configPath,
    );
  }

  const diffPath = firstDifferingKeyPath(
    stripManagedHookArrays(currentDoc),
    stripManagedHookArrays(nextDoc),
    [],
  );
  if (diffPath) {
    throw new CodexInstallRefusalError(
      `Codex config ${configPath}: installing would change '${diffPath.join(".")}', which is ` +
        "not a harness-managed hook event array; refusing to install rather than risk " +
        "silently dropping or altering operator- or Codex-owned content. Restore " +
        `${configPath} from the most recent .harness-backup-* file if it looks wrong, or file ` +
        "an issue with the config shape that triggered this.",
      configPath,
    );
  }

  const currentHooks =
    typeof currentDoc === "object" &&
    currentDoc !== null &&
    !Array.isArray(currentDoc) &&
    typeof (currentDoc as Record<string, unknown>).hooks === "object" &&
    (currentDoc as Record<string, unknown>).hooks !== null &&
    !Array.isArray((currentDoc as Record<string, unknown>).hooks)
      ? ((currentDoc as Record<string, unknown>).hooks as Record<string, unknown>)
      : {};
  const nextHooks =
    typeof nextDoc === "object" &&
    nextDoc !== null &&
    !Array.isArray(nextDoc) &&
    typeof (nextDoc as Record<string, unknown>).hooks === "object" &&
    (nextDoc as Record<string, unknown>).hooks !== null &&
    !Array.isArray((nextDoc as Record<string, unknown>).hooks)
      ? ((nextDoc as Record<string, unknown>).hooks as Record<string, unknown>)
      : {};

  for (const [event, value] of Object.entries(currentHooks)) {
    if (!Array.isArray(value)) continue;
    const owned = ownedHookEntries.get(event) ?? new Set<number>();
    const outsideEntries = value.filter((_, idx) => !owned.has(idx));
    if (outsideEntries.length === 0) continue;
    const nextArray = Array.isArray(nextHooks[event]) ? (nextHooks[event] as unknown[]) : [];
    let cursor = 0;
    for (const entry of outsideEntries) {
      while (cursor < nextArray.length && firstDifferingKeyPath(entry, nextArray[cursor], []) !== null) {
        cursor += 1;
      }
      if (cursor >= nextArray.length) {
        throw new CodexInstallRefusalError(
          `Codex config ${configPath}: an operator-authored [[hooks.${event}]] table (outside ` +
            "the harness-managed block) would not survive this install unchanged; refusing to " +
            `install rather than drop it. Restore ${configPath} from the most recent ` +
            ".harness-backup-* file if it looks wrong, or file an issue with the config shape " +
            "that triggered this.",
          configPath,
        );
      }
      cursor += 1;
    }
  }
}

export function planCodexConfigInstall(
  opts: CodexConfigInstallOptions,
): CodexConfigInstallPlan {
  validateCodexManagedConfig(opts.generatedContent);

  const configPath = opts.configPath ?? defaultCodexConfigPath(opts.homeDir);
  let currentContent = "";
  try {
    currentContent = fs.readFileSync(configPath, "utf8");
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code !== "ENOENT") throw err;
  }

  const managedBlock = buildManagedBlock(
    opts.generatedContent,
    opts.generatedPath,
  );
  const range = findManagedRange(currentContent, configPath);
  let nextContent: string;
  let summary: string;
  let removedHookIds: string[] = [];
  let foreignSectionsPreserved: string[] = [];
  if (range) {
    const oldHookIds = extractHookIds(currentContent.slice(range.start, range.end));
    const newHookIds = extractHookIds(managedBlock);
    removedHookIds = [...oldHookIds].filter((id) => !newHookIds.has(id));
    foreignSectionsPreserved = range.foreignSectionsPreserved;

    const middleForeign = range.strayEnd
      ? currentContent.slice(range.end, range.strayEnd.start)
      : "";
    const tailStart = range.strayEnd ? range.strayEnd.end : range.end;
    nextContent = `${currentContent.slice(0, range.start)}${managedBlock}${middleForeign}${currentContent.slice(tailStart)}`;
    summary = `updated harness-managed Codex hook block in ${configPath}`;
  } else {
    const prefix =
      currentContent.length === 0
        ? ""
        : currentContent.endsWith("\n\n")
          ? ""
          : currentContent.endsWith("\n")
            ? "\n"
            : "\n\n";
    nextContent = `${currentContent}${prefix}${managedBlock}`;
    summary = `installed harness-managed Codex hook block into ${configPath}`;
  }

  if (currentContent !== nextContent) {
    const ownedHookEntries = computeOwnedHookEntryIndexes(
      currentContent,
      range ? { start: range.start, end: range.end } : null,
    );
    assertConfigSemanticInvariant(currentContent, nextContent, configPath, ownedHookEntries);
  }

  return {
    configPath,
    generatedPath: opts.generatedPath,
    currentContent,
    nextContent,
    changed: currentContent !== nextContent,
    summary:
      currentContent === nextContent
        ? `Codex config already up to date: ${configPath}`
        : summary,
    removedHookIds,
    foreignSectionsPreserved,
  };
}

function timestampForBackup(now: Date): string {
  return now.toISOString().replace(/[:.]/g, "-");
}

/** The config holds operator secrets (API tokens under `[mcp_servers.*]`,
 * Codex hook trust hashes); the install must never widen its permissions.
 * Preserves the existing file's own mode for both the rewritten config and
 * its backup, and falls back to `0o600` (owner read/write only) when
 * creating a config that did not exist before this install, rather than
 * `atomicWriteFile`'s own `0o644` default. */
function existingFileMode(filePath: string): number {
  try {
    return fs.statSync(filePath).mode & 0o777;
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code !== "ENOENT") throw err;
    return 0o600;
  }
}

export function writeCodexConfigInstall(
  plan: CodexConfigInstallPlan,
  opts: { now?: Date } = {},
): CodexConfigInstallResult {
  if (!plan.changed) return { ...plan, written: false };
  const backupPath = `${plan.configPath}.harness-backup-${timestampForBackup(opts.now ?? new Date())}`;
  fs.mkdirSync(path.dirname(plan.configPath), { recursive: true });
  const mode = existingFileMode(plan.configPath);
  atomicWriteFile(backupPath, plan.currentContent, { mode });
  atomicWriteFile(plan.configPath, plan.nextContent, { mode });
  return { ...plan, backupPath, written: true };
}
