import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { parse as parseTomlDocument, TomlError } from "smol-toml";
import { atomicWriteFile } from "../../io/atomic-write.js";
import { EX_FAIL, HarnessExitError } from "../exit-codes.js";

export const CODEX_MANAGED_SOURCE_PREFIX = "# Harness Codex hook wiring.";
export const CODEX_MANAGED_BEGIN = "# BEGIN harness-managed codex hooks";
export const CODEX_MANAGED_END = "# END harness-managed codex hooks";

/**
 * Thrown instead of a plain `Error` when the install refuses rather than
 * guesses (a duplicate/moved BEGIN marker, or a foreign table wedged
 * inside the managed block). Extends `HarnessExitError` so it carries the
 * repo's own exit-code convention (`EX_FAIL`) through `run()`'s top-level
 * catch without the generic "return 70" branch, and the CLI action can
 * recognize it by type to emit a structured `--json` error the same way
 * the other apply refusals (`target-exists-refuse`, `drift-refuse`) do.
 */
export class CodexInstallRefusalError extends HarnessExitError {
  constructor(
    message: string,
    public readonly configPath: string,
  ) {
    super(message, EX_FAIL);
    this.name = "CodexInstallRefusalError";
  }
}

const GENERATED_HEADER = "# Generated by harness apply --runtime codex.";
/** How the split-block refusal names a legacy generated header as the line
 * its block starts at (`assertNoSplitBlock`, `findManagedRange`). */
const GENERATED_HEADER_OPENING = `the '${GENERATED_HEADER}' line`;
const LEGACY_HOOK_TABLE_RE =
  /^\[\[hooks\.(pre_tool_use|post_tool_use|user_prompt_submit|session_start|stop)\]\]$/;
const CURRENT_HOOK_TABLE_RE = /^\[\[hooks\.[A-Za-z][A-Za-z0-9_]*\]\]$/;
// A single, unquoted-or-quoted TOML bare/quoted key: `foo-bar_1`, a basic
// `"..."` string (escapes allowed), or a literal `'...'` string (no
// escapes, so a literal key may itself contain `[`, `]`, `"` or `#`
// verbatim, e.g. `'a[b'`).
const TOML_KEY = String.raw`(?:[A-Za-z0-9_-]+|"(?:[^"\\]|\\.)*"|'[^']*')`;
// A single-line TOML table header only: `[key]`, `[[key]]`, or a dotted
// path of keys (`[a.b."c d".'e[f']`), optionally surrounded by whitespace
// around the brackets and each dot, and optionally followed by whitespace
// and a trailing comment. Quote-aware so a key that itself contains `[`,
// `]`, `.` or `#` (a real path or filename used as a TOML key, e.g.
// `[projects."/Users/x/Photos [2024]"]`, `[plugins.'a[b']`) is still
// recognized as one header, instead of the bracket/hash inside the quotes
// being mistaken for the header's own delimiters. Deliberately excludes an
// array-continuation line such as `  [1, 2],` (no trailing comma allowed,
// and a bare numeric-looking segment such as `1` only ever matches as a
// single key with nothing after it, never as an array element) so a
// multi-line array/value sitting inside a still-owned harness hook table
// is never misread as a foreign table header ending the owned region
// early (task 6a037359). A lone element on its own line (`["x"]`, `['x']`,
// `[1]`, `[1979-05-27]`) does have the shape of a header, so this regex is
// only a candidate filter: every caller also requires `createTopLevelProbe`
// before treating a match as a real header (task 6b56d735), the scans
// through `createLineClassifier` (task 01053b27).
const NON_HOOK_TABLE_RE = new RegExp(
  String.raw`^\[(?!\[hooks\.)\[?\s*${TOML_KEY}(?:\s*\.\s*${TOML_KEY})*\s*\]\]?\s*(?:#.*)?$`,
);
// Every emitted hook table is preceded by exactly this comment shape
// (generate-codex-config.ts's `emitHook`); used both to name removed hook
// blocks in the install summary and to detect a foreign table wedged
// between two harness hook tables (see `assertNoSplitBlock`).
const HARNESS_HOOK_COMMENT_PREFIX = "# harness hook: ";
const HOOK_ID_LINE_RE = /^# harness hook: (.+) \(budget_ms=\d+\)$/;
// A `[[hooks.<Event>]]` array-of-tables header, harness-written or not.
// `NON_HOOK_TABLE_RE` deliberately excludes it, so the ownership scan tells
// the two apart by the `# harness hook:` comment above the header instead
// (see `scanOwnedContentEnd`).
const HOOK_ARRAY_HEADER_RE = /^\[\[hooks\./;

export interface CodexConfigInstallPlan {
  /**
   * The regular file the install reads and writes. When the requested
   * config path is a symlink (a dotfiles-managed config), this is the
   * link's fully resolved target, so the write lands in the real file and
   * the link itself stays a link (task 1637fbc8).
   */
  configPath: string;
  /**
   * The requested config path when it is a symlink, set only then. Named
   * in the summary so the operator sees both the link and the real file
   * written, and the base of the backup file name: the backup of a
   * symlinked config sits beside the link (e.g. in ~/.codex), never beside
   * the target, because the config holds secrets and the target's
   * directory is typically a dotfiles git work tree.
   */
  linkPath?: string;
  generatedPath: string;
  currentContent: string;
  nextContent: string;
  changed: boolean;
  /**
   * True when `configPath` already held a file before this install (even
   * an empty one), false when the path did not exist. Distinguishes "no
   * prior file" from "an existing, possibly empty, prior file" so
   * `writeCodexConfigInstall` only backs up a file that actually existed
   * (task 461ec064): writing a 0-byte backup for a config that never
   * existed had nothing to protect and misreported a write that never
   * happened.
   */
  configExisted: boolean;
  summary: string;
  /**
   * Hook ids (the `# harness hook: <id>` comment text) that were present
   * in the old managed block and are absent from the new one. Reported so
   * an operator whose manifest still declares a pack does not silently
   * lose a hook (task 6a037359).
   */
  removedHookIds: string[];
  /**
   * Foreign (non harness-owned) table headers that sat between the old
   * managed block and a stray END marker, one representative header per
   * distinct namespace (see `collectForeignSectionHeaders`). Populated
   * only when the previous install's END marker had drifted past foreign
   * content (the task-6a037359 bug): these are the sections that would
   * have been deleted under the old blind-END-trust logic and are now
   * preserved byte-for-byte instead.
   */
  foreignSectionsPreserved: string[];
  /**
   * Operator-authored `[[hooks.<Event>]]` tables (no `# harness hook:`
   * comment above them) that the managed-range scan ended the harness block
   * at and that are kept after the fresh block, one entry per table: its
   * header and its 1-based line number in the config before the install and
   * in the config the install writes (for example
   * `[[hooks.Stop]] (line 14 before the install, line 40 after it)`), never
   * any value text. A hook event table spelled without the `[[hooks.` prefix
   * (`[[ hooks.Stop ]]`, `[["hooks".Stop]]`) directly after the harness
   * tables is one of these too (task e8f4fc03). Named because the
   * scan cannot tell such a table from a harness table whose comment line an
   * operator deleted (task 01053b27); a kept table that looks
   * harness-generated is refused instead (see `assertKeptHookTablesAreOperatorOwned`).
   * The same entries are appended to `foreignSectionsPreserved`, which is
   * what `--dry-run` and the install summary print.
   */
  keptOperatorHookTables: string[];
}

export interface CodexConfigInstallResult extends CodexConfigInstallPlan {
  backupPath?: string;
  written: boolean;
}

export interface CodexConfigInstallOptions {
  configPath?: string;
  homeDir?: string;
  generatedPath: string;
  generatedContent: string;
  now?: Date;
}

export function defaultCodexConfigPath(homeDir?: string): string {
  return path.join(homeDir ?? os.homedir(), ".codex", "config.toml");
}

function lineStartAt(text: string, index: number): number {
  const prev = text.lastIndexOf("\n", Math.max(0, index - 1));
  return prev === -1 ? 0 : prev + 1;
}

function lineEndAfter(text: string, index: number): number {
  const next = text.indexOf("\n", index);
  return next === -1 ? text.length : next + 1;
}

function previousLine(
  text: string,
  lineStart: number,
): { start: number; text: string } | null {
  if (lineStart === 0) return null;
  const end = lineStart - 1;
  const start = lineStartAt(text, end);
  return { start, text: text.slice(start, end) };
}

/** 1-based line number of `index` within `text`, for operator-facing error text. */
function lineNumberAt(text: string, index: number): number {
  let n = 1;
  for (let i = 0; i < index && i < text.length; i += 1) {
    if (text[i] === "\n") n += 1;
  }
  return n;
}

type TripleDelim = '"""' | "'''" | null;

/** True when the character at `index` is escaped by an odd number of
 * immediately preceding backslashes (`\"` is escaped, `\\"` is not: the
 * first backslash escapes the second, leaving the quote bare). Only basic
 * (double-quoted) strings support this escape; literal (single-quoted)
 * strings never do. */
function isEscapedAt(line: string, index: number): boolean {
  let backslashes = 0;
  let j = index - 1;
  while (j >= 0 && line[j] === "\\") {
    backslashes += 1;
    j -= 1;
  }
  return backslashes % 2 === 1;
}

/**
 * Walks one physical line of TOML, tracking only what a caller needs to
 * decide whether the NEXT line is opaque multi-line-string content: which
 * triple-quote delimiter (if any) is open once this line ends. `delimIn`
 * is the delimiter already open when this line STARTS (from a preceding
 * multi-line string that has not yet closed); when non-null, this line's
 * own content is scanned only for that SAME delimiter closing it (a basic
 * `"""` string is closed only by another `"""`, never by `'''`, and vice
 * versa -- naively counting either delimiter's raw
 * occurrences, as the pre-fix code did, misreads a `'''` sitting inside an
 * open `"""` string, or a comment/single-line-string containing `'''` or
 * `"""`, as a real close).
 *
 * When `delimIn` is null, the line is scanned left to right: a bare `#`
 * (outside any string) starts a line comment and ends scanning (its
 * content, including any quote characters, is never code); a single-line
 * basic (`"`) or literal (`'`) string is skipped to its own closing quote
 * (escapes honored only for `"`) without inspecting its contents for
 * delimiters; a `"""`/`'''` not preceded by an escaped quote opens a
 * multi-line string of that type.
 */
function nextTripleDelim(rawLine: string, delimIn: TripleDelim): TripleDelim {
  let i = 0;
  const n = rawLine.length;
  let delim = delimIn;
  while (i < n) {
    if (delim !== null) {
      if (rawLine.startsWith(delim, i)) {
        if (delim === '"""' && isEscapedAt(rawLine, i)) {
          i += 1;
          continue;
        }
        delim = null;
        i += 3;
        continue;
      }
      if (delim === '"""' && rawLine[i] === "\\") {
        i += 2; // an escaped char inside a basic string can never itself
        continue; // start a real closing delimiter.
      }
      i += 1;
      continue;
    }
    const ch = rawLine[i];
    if (ch === "#") break; // line comment: nothing after it is code.
    if (rawLine.startsWith('"""', i)) {
      delim = '"""';
      i += 3;
      continue;
    }
    if (rawLine.startsWith("'''", i)) {
      delim = "'''";
      i += 3;
      continue;
    }
    if (ch === '"') {
      i += 1;
      while (i < n && rawLine[i] !== '"') {
        if (rawLine[i] === "\\") i += 1;
        i += 1;
      }
      i += 1; // consume the closing quote (or run to end if unterminated)
      continue;
    }
    if (ch === "'") {
      i += 1;
      while (i < n && rawLine[i] !== "'") i += 1;
      i += 1;
      continue;
    }
    i += 1;
  }
  return delim;
}

/** How a managed-block marker's line must read once trimmed: `whole`, the
 * line is the marker (END, compared exactly as before); `prefix`, the line
 * starts with it (BEGIN, which was found wherever its text sat and so still
 * matches a marker line with text after it; the source prefix, which the
 * generator follows with the generated path; the generated header; the
 * `# harness hook: <id>` comment). */
type MarkerShape = "whole" | "prefix";

/**
 * The one rule every managed-block marker is located by (task 36d962d2): a
 * line is a marker line only when its trimmed text is the marker (`whole`)
 * or starts with it (`prefix`) AND it sits at the top level of the document
 * (`createTopLevelProbe`). Marker text anywhere else is operator content:
 * inside a single-line or multi-line string (basic or literal), after a
 * content line as a trailing comment, inside an inline table, or on a line
 * inside a multi-line array (an element, or a comment line between
 * elements). Treating such text as a marker made the install replace,
 * delete, or splice a fresh block into the operator's value. Every lookup
 * of BEGIN, END, the source prefix, the generated header and the
 * `# harness hook:` comment goes through this probe or `findMarkerLine`, and
 * so does the `[[hooks.` header line that lets a generated header open a
 * legacy block (`findManagedRange`).
 * Two marker searches stay outside it on purpose: the split-block refusal's
 * candidate list (`assertNoSplitBlock`), which can only refuse, never
 * install, and the trailing comment run of `scanOwnedContentEnd`, whose
 * lines are whole top-level comment lines by construction. That run (blank
 * and comment lines ending the file after a block with no END marker) is
 * consumed as stale harness output when the source prefix, the generated
 * header or the `# harness hook:` text appears anywhere in it, so an
 * operator comment there that mentions such text mid-line is removed with
 * the block.
 *
 * The returned probe answers for line starts queried in non-decreasing
 * order (the top-level probe's contract, which a line that fails the text
 * test never touches).
 */
function createMarkerLineProbe(
  text: string,
): (lineStart: number, marker: string, shape: MarkerShape) => boolean {
  const topLevel = createTopLevelProbe(text);
  return (lineStart, marker, shape) => {
    const trimmed = text.slice(lineStart, lineEndAfter(text, lineStart)).trim();
    const textMatches = shape === "whole" ? trimmed === marker : trimmed.startsWith(marker);
    return textMatches && topLevel(lineStart);
  };
}

/** The start of the first marker line (`createMarkerLineProbe`) at or after
 * the line start `from`, or -1. Candidates are visited in order, one line
 * each, so the probe's non-decreasing-offset contract holds. */
function findMarkerLine(text: string, marker: string, shape: MarkerShape, from = 0): number {
  const isMarkerLine = createMarkerLineProbe(text);
  let pos = from;
  for (;;) {
    const idx = text.indexOf(marker, pos);
    if (idx === -1) return -1;
    const lineStart = lineStartAt(text, idx);
    if (isMarkerLine(lineStart, marker, shape)) return lineStart;
    pos = lineEndAfter(text, lineStart);
  }
}

/** True when a line in `[from, to)` is a marker line for the prefix
 * `marker`. */
function rangeHoldsMarkerLine(
  text: string,
  from: number,
  to: number,
  marker: string,
  isMarkerLine: (lineStart: number, marker: string, shape: MarkerShape) => boolean,
): boolean {
  for (let pos = from; pos < to; pos = lineEndAfter(text, pos)) {
    if (isMarkerLine(pos, marker, "prefix")) return true;
  }
  return false;
}

/** Answers, for a line start in `text`, whether that line sits at the top
 * level of the document, that is, not inside a multi-line array, a multi-line
 * inline table or a multi-line string opened by an earlier line. The document
 * parser is the oracle: the text before the line parses on its own exactly
 * when nothing is still open there, whereas a prefix that ends inside an
 * array is an unterminated array and fails. A line that merely LOOKS like a
 * table header (an array element on its own line such as `["x"]`, `['x']`,
 * `[1]` or `[1979-05-27]`) is therefore told apart from a real header even
 * when a real table of the same name exists elsewhere in the document, which
 * a lookup of the header's key path in the parsed document could not do.
 * A line inside an open construct never has a prefix that parses, so such a
 * line is never taken for a header.
 *
 * The verdict is the full-prefix verdict: a line is top level when
 * `text.slice(0, lineStart)` parses. The probe first tries a fast path: it
 * remembers the last line start it confirmed as top level and parses only
 * the text from there; when that segment parses, the line is confirmed
 * without parsing the full prefix. When the segment fails, the full prefix
 * decides, and a line it accepts is confirmed too. The segment is not
 * claimed to agree with the full prefix: a segment can fail where the full
 * prefix parses (a sub-table `[hooks.Stop.meta]` confirmed, then the next
 * `[[hooks.Stop]]` element, which is never a candidate and so stays in the
 * segment, redefines `hooks.Stop` as seen from the segment alone), and then
 * the full prefix is what answers. So a line is reported as not top level
 * only when the full prefix fails, and a line whose full prefix parses is
 * always reported as top level. The fast path can only answer "top level"
 * where the full prefix fails if the prefix holds a conflict of its own (a
 * table defined twice); such a document does not parse as a whole, and the
 * install refuses it through the parse check on the config either way. Even
 * then the segment starts at a confirmed line with nothing open, so a line
 * inside an open array, inline table or multi-line string still fails it.
 *
 * Cost: a real table confirmed on the fast path costs a segment parse. Any
 * candidate whose segment fails costs a full-prefix parse too: an array
 * element on its own line, or a sub-table after a later element of the same
 * array of tables. Many of those are quadratic in their number (seconds at
 * thousands; the CHANGELOG entry for this change has the measurements).
 * Both scans query non-decreasing line starts. A query
 * before the last confirmed line start throws instead of answering; a line
 * reported as not top level is never confirmed, so it never moves that
 * bound (task 6b56d735). Exported for direct tests only. */
export function createTopLevelProbe(text: string): (lineStart: number) => boolean {
  let confirmed = 0;
  const parses = (content: string): boolean => {
    try {
      parseToml(content);
      return true;
    } catch {
      return false;
    }
  };
  return (lineStart) => {
    if (lineStart < confirmed) {
      throw new Error(
        `top-level probe queried at offset ${lineStart}, before the last confirmed line start ${confirmed}`,
      );
    }
    const topLevel =
      parses(text.slice(confirmed, lineStart)) ||
      (confirmed > 0 && parses(text.slice(0, lineStart)));
    if (topLevel) confirmed = lineStart;
    return topLevel;
  };
}

/** The first non-blank, non-comment line at or after `from` (bounded by
 * `limit`), trimmed, with the offset its line starts at. Used to name the
 * offending foreign header in a refusal message. */
function firstContentLine(
  text: string,
  from: number,
  limit: number,
): { line: string; start: number } | null {
  let pos = Math.max(from, 0);
  const end = Math.max(limit, from);
  while (pos < end) {
    const lineEnd = Math.min(lineEndAfter(text, pos), end);
    const trimmed = text.slice(pos, lineEnd).trim();
    if (trimmed !== "" && !trimmed.startsWith("#")) return { line: trimmed, start: pos };
    pos = lineEnd;
  }
  return null;
}

/** What a line of the config is, as every header scan reads it (see
 * `createLineClassifier`). */
type LineKind = "string" | "comment" | "hookHeader" | "foreignHeader" | "content";

/**
 * The one line classifier every header scan of the install uses (the
 * managed-range scan, the foreign-section listing, the kept hook table scan
 * and the hook header map), so a line is read the same way wherever it is
 * met (task 01053b27). Called once per line, in order, from a line start at
 * which nothing is open. The rule, applied in this order:
 *
 * 1. A line that starts inside a multi-line string opened by an earlier line
 *    (`nextTripleDelim`) is `string`: string content, whatever it looks like.
 * 2. A blank line or a `#` comment line is `comment` (the END marker and the
 *    `# harness hook:` lines are comment lines the callers check by text).
 * 3. A line starting `[[hooks.` is `hookHeader`. No parse is needed: a dotted
 *    bare key is not a TOML value, so in a config that parses such a line is
 *    never inside an array or inline table, and a config that does not parse
 *    is refused by the parse checks before anything is written.
 * 4. Any other line with the shape of a table header (`NON_HOOK_TABLE_RE`)
 *    is `foreignHeader` only when it starts at the top level of the document
 *    (`createTopLevelProbe`); otherwise it is an array element on its own
 *    line inside a multi-line value (`["x"]`, `['x']`, `[1]`,
 *    `[1979-05-27]`) and is `content`, never a header.
 * 5. Every other line is `content` (a key/value line or a continuation line
 *    of a multi-line value).
 *
 * `wanted` narrows rule 4 for a scan that only uses some headers: a
 * header-shaped line it rejects is `content` for that scan without the
 * top-level probe, whose full-prefix parse is the cost of rule 4 (see
 * `createTopLevelProbe`). Only the hook header map passes one, since it
 * resolves nothing but headers whose root key is `hooks`.
 */
function createLineClassifier(
  text: string,
  wanted: (trimmed: string) => boolean = () => true,
): (lineStart: number, rawLine: string) => LineKind {
  let delim: TripleDelim = null;
  const startsAtTopLevel = createTopLevelProbe(text);
  return (lineStart, rawLine) => {
    const startedInsideString = delim !== null;
    delim = nextTripleDelim(rawLine, delim);
    if (startedInsideString) return "string";
    const trimmed = rawLine.trim();
    if (trimmed === "" || trimmed.startsWith("#")) return "comment";
    if (HOOK_ARRAY_HEADER_RE.test(trimmed)) return "hookHeader";
    if (NON_HOOK_TABLE_RE.test(trimmed) && wanted(trimmed) && startsAtTopLevel(lineStart)) {
      return "foreignHeader";
    }
    return "content";
  };
}

/**
 * Scans forward from `start` classifying each line as either still-owned
 * harness content or the start of foreign (non-harness) content, WITHOUT
 * relying on where (or whether) a `CODEX_MANAGED_END` marker sits. This is
 * what makes the region computation safe against a stray/misplaced END
 * (task 6a037359: `findManagedRange` used to trust `text.indexOf(END,
 * begin)` unconditionally, so an END marker that had drifted past
 * Codex-written tables such as `[hooks.state]` caused every foreign table
 * between BEGIN and that END to be deleted on the next install) and
 * against a config that has no END marker at all (the legacy shape).
 *
 * A run of blank/comment lines immediately followed by foreign content is
 * excluded from the owned region (backed off to the start of that run):
 * Codex, or an operator, may attach a comment to the table that follows,
 * and that comment must never be misread as harness commentary and folded
 * into the replaced block.
 *
 * A line is "foreign" exactly when it is a table header that is not one
 * of ours (`NON_HOOK_TABLE_RE`, mirroring the pre-existing legacy scan) and
 * sits at the top level of the document (`createTopLevelProbe`: an array
 * element on its own line inside a multi-line value has the same shape but
 * is not a header), or
 * a `[[hooks.<Event>]]` header without a `# harness hook:` comment above it
 * that comes after at least one header that has one (task 01053b27).
 * Failure modes of that second rule: a harness table whose comment an
 * operator deleted ends the range there (a later harness table still
 * carrying its comment, before the END marker when one follows, lands in
 * the zone `assertNoSplitBlock` refuses on; a
 * last table stays as an operator table, which the install names in
 * `keptOperatorHookTables` and refuses when its command is one harness
 * writes, see `assertKeptHookTablesAreOperatorOwned`); a
 * block that never carried the comments (older generator output) has no
 * marked table before its first hook table, so it is consumed whole as
 * before. Bare `key =` lines of an operator table follow that table out of
 * the range; bare keys placed directly under a harness table cannot be told
 * apart from the harness table's own fields and are still consumed with it;
 * every other non-blank, non-comment line (a hook table's `matcher =` /
 * `hooks =` field, or an older schema's bare `command =` / `match =` /
 * `timeout_ms =` / `blocking =` field) is treated as still-owned content,
 * same as before this fix. A line that BEGAN inside an open TOML
 * multi-line string (`nextTripleDelim`) is always treated as still-owned
 * content too, regardless of what it looks like: a hook table's own
 * multi-line string value (or a foreign table's, once one is already
 * inside the owned region by construction -- this scanner only ever runs
 * from a position that is itself still-owned) may contain a line that
 * reads exactly like a comment, a blank line, or even the END marker
 * without that ending the region early (task 6a037359).
 */
function scanOwnedContentEnd(
  text: string,
  start: number,
): { end: number; sawEndMarker: boolean; endedAtOperatorHookTable?: true } {
  let pos = start;
  let commentRunStart: number | null = null;
  let sawOwnedContent = false;
  let sawMarkedHookTable = false;
  const classify = createLineClassifier(text);
  const isMarkerLine = createMarkerLineProbe(text);
  while (pos < text.length) {
    const lineEnd = lineEndAfter(text, pos);
    const rawLine = text.slice(pos, lineEnd);
    const kind = classify(pos, rawLine);
    if (kind === "string") {
      commentRunStart = null;
      sawOwnedContent = true;
      pos = lineEnd;
      continue;
    }
    if (isMarkerLine(pos, CODEX_MANAGED_END, "whole")) {
      return { end: lineEnd, sawEndMarker: true };
    }
    if (kind === "comment") {
      if (commentRunStart === null) commentRunStart = pos;
      pos = lineEnd;
      continue;
    }
    if (kind === "foreignHeader") {
      return { end: commentRunStart ?? pos, sawEndMarker: false };
    }
    if (kind === "hookHeader") {
      const marked =
        commentRunStart !== null &&
        rangeHoldsMarkerLine(text, commentRunStart, pos, HARNESS_HOOK_COMMENT_PREFIX, isMarkerLine);
      if (marked) {
        sawMarkedHookTable = true;
      } else if (sawMarkedHookTable) {
        // An operator-authored hook table (no `# harness hook:` comment
        // above it) after the harness tables ends the owned region, like a
        // foreign table, and keeps a comment attached to it (task 01053b27).
        return { end: commentRunStart ?? pos, sawEndMarker: false, endedAtOperatorHookTable: true };
      }
    }
    commentRunStart = null;
    sawOwnedContent = true;
    pos = lineEnd;
  }
  // No END marker and no foreign table: a run of blank/comment lines that
  // reaches EOF and holds at least one comment is an operator's trailing
  // comment, not harness content, so back off to the start of that run
  // (task b34ed105). Not when the run holds a harness-authored line (the
  // generated header, a `# harness hook:` line, the source prefix: the
  // generator itself writes comment-only content, so such a run is stale
  // harness output that must be replaced), and not before the scan has seen
  // an owned content line. A run of only blank lines is still consumed.
  if (commentRunStart !== null && sawOwnedContent) {
    const run = text.slice(commentRunStart, pos);
    const hasComment = /(^|\n)[ \t]*#/.test(run);
    // Matched as substrings on purpose, outside `createMarkerLineProbe`:
    // every line of this run is a whole comment or blank line at the top
    // level (a string line resets the run, and at the end of a document that
    // parses nothing is still open), so marker text here is never inside a
    // value, and a comment that mentions a marker is stale harness output.
    const harnessAuthored =
      run.includes(HARNESS_HOOK_COMMENT_PREFIX) ||
      run.includes(CODEX_MANAGED_SOURCE_PREFIX) ||
      run.includes(GENERATED_HEADER);
    if (hasComment && !harnessAuthored) {
      return { end: commentRunStart, sawEndMarker: false };
    }
  }
  return { end: pos, sawEndMarker: false };
}

/**
 * True when a harness-commented hook table (a `# harness hook:` comment line
 * followed, later in the zone, by a `[[hooks.` header or a hook event array
 * header spelled without that prefix, `[[ hooks.SessionStart ]]`) lies after the named
 * table's header line, before `to`. The comment is found as a marker line
 * (`createMarkerLineProbe`), so a value that merely contains the marker text
 * does not count. Used only to pick the fix guidance of a refusal (task
 * 36d962d2).
 */
function harnessHookTableFollows(
  text: string,
  header: { line: string; start: number } | null,
  to: number,
): boolean {
  if (header === null) return false;
  let pos = lineEndAfter(text, header.start);
  let sawComment = false;
  const isMarkerLine = createMarkerLineProbe(text);
  while (pos < to) {
    const lineEnd = Math.min(lineEndAfter(text, pos), to);
    const trimmed = text.slice(pos, lineEnd).trim();
    if (isMarkerLine(pos, HARNESS_HOOK_COMMENT_PREFIX, "prefix")) sawComment = true;
    else if (sawComment && (HOOK_ARRAY_HEADER_RE.test(trimmed) || isHookEventArrayHeader(trimmed))) {
      return true;
    }
    pos = lineEnd;
  }
  return false;
}

/**
 * Refuses loudly (mirror case of the stray-END bug) when the zone between
 * `from` and `to` still contains a recognizable fragment of a harness
 * hook block: a second BEGIN/source-prefix marker, or a `# harness hook:`
 * comment. Either means a foreign table was wedged between two harness
 * hook tables, or the BEGIN marker moved, and the true block boundaries
 * can no longer be determined by a line scan; guessing risks reordering
 * or dropping harness- or foreign-owned bytes, so this throws instead. The
 * message names the resolved config path (never a hard-coded `~/.codex`),
 * the foreign table header the scan found (usually `from` itself, see
 * `scanOwnedContentEnd`; when only blank or comment lines precede the found
 * marker in the zone -- so the pre-marker lookup finds no content line to
 * report -- the header is looked up again just past that marker's own
 * line, since the wedged table then sits after it, not before, and the
 * message says the marker line sits above the table (task e8f4fc03); printed
 * through `describeTableHeader`, so only the header's own bracketed key
 * path appears, never a trailing comment), and
 * the line number and marker of the first line beyond it
 * that still looks like harness content. That line's own text is never
 * echoed: the marker is found by a substring search, so the line may be
 * foreign content (a value holding an API token, say) that merely contains
 * the marker text, and the refusal is printed to stderr and into `--json`
 * output. `hasEndMarker` distinguishes the two callers: when `to` was
 * derived from a real stray `CODEX_MANAGED_END` line, the fix guidance can
 * point at that marker; when there is no END marker anywhere in the
 * document (`to` is `text.length`), telling the operator to move something
 * below a marker that does not exist would be nonsensical, so a different
 * fix (add one, or move the table below the last harness hook table) is
 * offered instead (task 6a037359). Adding one is offered only when no
 * harness-commented hook table follows the named table
 * (`harnessHookTableFollows`): an END placed before the named table would
 * leave that later table running next to the fresh block (task 36d962d2).
 * When the named table is a hook event table spelled without the `[[hooks.`
 * prefix, the guidance offers deleting it if harness wrote it, since the scan
 * reads such a table as foreign with or without a comment line above it
 * (task e8f4fc03). The legacy paths call
 * this too, so the substring matching above applies there as well: a value
 * holding marker text refuses. This candidate list and the trailing comment
 * run of `scanOwnedContentEnd` are the two marker searches that do not go
 * through `createMarkerLineProbe`, on purpose. This one can only refuse,
 * never install, so matching marker text in a value costs a refusal, never
 * operator content. The comment run's lines are whole top-level comment
 * lines, so marker text there is never inside a value, but that run (blank
 * and comment lines ending the file after a block with no END marker) is
 * consumed when the source prefix, the generated header or the
 * `# harness hook:` text appears anywhere in it, so an operator comment
 * there that mentions such text mid-line is removed with the block.
 * `blockOpening` names the line the block
 * starts at in the delete-the-lines fix: the BEGIN marker by default; a
 * legacy config (no BEGIN marker) whose END marker survived passes its
 * source-prefix line or generated header instead, since a BEGIN marker it
 * does not have is no line to delete from (task 01053b27). For the generated
 * header the fix deletes that line and the END marker line too: a generated
 * header left alone above END no longer marks a harness block
 * (`findManagedRange` needs a top-level `[[hooks.` header line after it), so the install
 * would add a fresh block and leave that pair behind as an orphan. Exported for
 * direct tests only: the scan
 * that feeds it never hands it a line that is not a real header, so its own
 * naming rule is reachable in isolation only by calling it directly (task
 * 6b56d735).
 */
export function assertNoSplitBlock(
  text: string,
  from: number,
  to: number,
  configPath: string,
  hasEndMarker: boolean,
  blockOpening = `'${CODEX_MANAGED_BEGIN}'`,
): void {
  const zoneStart = Math.max(from, 0);
  const zoneEnd = Math.max(to, from);
  const zone = text.slice(zoneStart, zoneEnd);
  let markerOffset = -1;
  let marker = "";
  for (const candidate of [
    CODEX_MANAGED_SOURCE_PREFIX,
    CODEX_MANAGED_BEGIN,
    HARNESS_HOOK_COMMENT_PREFIX,
  ]) {
    const idx = zone.indexOf(candidate);
    if (idx !== -1 && (markerOffset === -1 || idx < markerOffset)) {
      markerOffset = idx;
      marker = candidate.trim();
    }
  }
  if (markerOffset === -1) return;

  const offendingLineNumber = lineNumberAt(text, lineStartAt(text, zoneStart + markerOffset));
  // Normally the foreign table header is the zone's own first content line,
  // sitting before the marker (`from` starts at that header per
  // `scanOwnedContentEnd`). But when only blank or comment lines precede the
  // marker in the zone -- so that pre-marker lookup finds no content line --
  // the foreign table that split the block is wedged after the marker's own
  // line instead, so look there.
  const markerLineEnd = lineEndAfter(text, zoneStart + markerOffset);
  const headerBeforeMarker = firstContentLine(text, zoneStart, zoneStart + markerOffset);
  const foreignHeaderLine = headerBeforeMarker ?? firstContentLine(text, markerLineEnd, zoneEnd);
  const firstForeignHeader = describeForeignHeaderLine(text, foreignHeaderLine);
  // Where the marker line sits relative to the named table, so the message
  // stays true when the table was found past the marker (a respelled hook
  // table with its own '# harness hook:' comment line above it, say).
  const placement =
    headerBeforeMarker === null
      ? `below harness-owned content: line ${offendingLineNumber}, above it, contains '${marker}'`
      : `sitting before more harness-owned content: line ${offendingLineNumber} contains '${marker}'`;

  const fixes = hasEndMarker
    ? [
        `move ${firstForeignHeader} below the '${CODEX_MANAGED_END}' marker`,
        blockOpening === GENERATED_HEADER_OPENING
          ? `delete every line from ${blockOpening} through the '${CODEX_MANAGED_END}' marker ` +
            "line, both included, so the install writes a fresh harness block"
          : `delete the lines between ${blockOpening} and '${CODEX_MANAGED_END}' so only ` +
            "harness-owned tables remain between them",
      ]
    : harnessHookTableFollows(text, foreignHeaderLine, zoneEnd)
      ? // An END marker placed before the named table would leave the
        // harness-commented hook table after it running next to the fresh
        // block, so the only fix offered is moving the named table past it
        // (task 36d962d2).
        [`move ${firstForeignHeader} below the last harness hook table`]
      : [
          `add a '${CODEX_MANAGED_END}' marker line right after the last harness hook table ` +
            `(before ${firstForeignHeader})`,
          `move ${firstForeignHeader} below the last harness hook table`,
        ];
  // An uncommented hook table in the middle may be a harness table whose
  // comment line was deleted, so moving it (the operator-table fix) is only
  // right for an operator-owned one; name the restore option first (task
  // 01053b27).
  const isHookTable = HOOK_ARRAY_HEADER_RE.test(foreignHeaderLine?.line ?? "");
  // A hook event table spelled another way (`[[ hooks.Stop ]]`) is read as
  // foreign with or without a comment line above it, so restoring one does
  // not help; deleting it does, if harness wrote it (task e8f4fc03).
  const isRespelledHookTable = isHookEventArrayHeader(foreignHeaderLine?.line ?? "");
  const guidance = isHookTable
    ? `If ${firstForeignHeader} is a harness hook table whose '${HARNESS_HOOK_COMMENT_PREFIX}<id> ` +
      "(budget_ms=<n>)' comment line was deleted, restore that comment line directly above it. " +
      `If it is an operator-owned table, ${fixes.join(", or ")}`
    : isRespelledHookTable
      ? `If ${firstForeignHeader} is a harness hook table, delete it together with any ` +
        `'${HARNESS_HOOK_COMMENT_PREFIX}<id> (budget_ms=<n>)' comment line above it (the install ` +
        "replaces only hook tables spelled '[[hooks.<Event>]]' with that comment line above " +
        `them, and writes the fresh block). If it is an operator-owned table, ${fixes.join(", or ")}`
      : fixes.join(", or ").replace(/^./, (c) => c.toUpperCase());

  throw new CodexInstallRefusalError(
    `Codex config ${configPath} has a foreign table (${firstForeignHeader}) ${placement} and still ` +
      "looks like part of the harness-managed hook block; refusing to guess the block " +
      `boundaries. ${guidance}, then re-run \`harness apply --runtime codex --install\`. As a ` +
      `last resort, restore ${configPath} from the most recent .harness-backup-* file (if one exists), but ` +
      "that discards any Codex state (hook trust entries, marketplaces, plugins) written to " +
      "the file since that backup.",
    configPath,
  );
}

// A single-line TOML table header split into the header itself (brackets
// plus dotted key path, without any trailing comment; group 1) and its
// dotted key path (group 2). Same shape `NON_HOOK_TABLE_RE` recognizes,
// minus the `[[hooks.` exclusion, so every header that regex accepts
// parses here too.
const TABLE_HEADER_PARTS_RE = new RegExp(
  String.raw`^(\[\[?\s*(${TOML_KEY}(?:\s*\.\s*${TOML_KEY})*)\s*\]\]?)\s*(?:#.*)?$`,
);
const TOML_KEY_GLOBAL_RE = new RegExp(TOML_KEY, "g");

/** A table header line's own bracketed key path (`header`) and its keys in
 * order (`keys`), each as written. Keys are matched with the quote-aware
 * `TOML_KEY`, so a quoted key containing `.`, `[`, `]` or `#` stays one
 * key, and a trailing comment is never part of either field. `null` for a
 * line that is not a single-line table header. */
function parseTableHeader(line: string): { header: string; keys: string[] } | null {
  const m = TABLE_HEADER_PARTS_RE.exec(line.trim());
  if (m?.[1] === undefined || m[2] === undefined) return null;
  return { header: m[1], keys: [...m[2].matchAll(TOML_KEY_GLOBAL_RE)].map((k) => k[0]) };
}

/** A table header for operator-facing output: the bracketed key path only,
 * with any trailing comment dropped (a comment is free text and is not
 * echoed). `(unknown)` for a line that is not a table header. */
function describeTableHeader(line: string): string {
  return parseTableHeader(line)?.header ?? "(unknown)";
}

/** How a refusal names the line it found where the foreign table's header
 * should be. A verified header prints as its bracketed key path. A line that
 * has the shape of a header but is not one (an array element on its own line
 * inside a multi-line value) is never printed, since it can hold a config
 * value such as a token; only its line number is. Any other line is
 * `(unknown)`, as before. */
function describeForeignHeaderLine(
  text: string,
  found: { line: string; start: number } | null,
): string {
  if (found === null) return "(unknown)";
  const parsed = parseTableHeader(found.line);
  if (parsed === null) return "(unknown)";
  if (!createTopLevelProbe(text)(found.start)) {
    return `line ${lineNumberAt(text, found.start)}`;
  }
  return parsed.header;
}

/** A key segment's bare name: a literal (`'...'`) key's inner text, a basic
 * (`"..."`) key's inner text when it holds no escape sequence, otherwise
 * the segment as written. Used only to recognize the `hooks` root however
 * it is spelled. */
function bareKeyName(segment: string): string {
  const quote = segment[0];
  if (segment.length >= 2 && (quote === "'" || quote === '"') && segment.endsWith(quote)) {
    const inner = segment.slice(1, -1);
    if (quote === "'" || !inner.includes("\\")) return inner;
  }
  return segment;
}

/** The namespace a foreign table header is grouped under in
 * `foreignSectionsPreserved`: its first key, or its first TWO keys when the
 * first is `hooks` (`hooks.state`), since `hooks` is shared with the
 * harness-managed event arrays and a bare `hooks` group would not tell the
 * operator which namespace was kept. */
function foreignSectionRootKey(headerLine: string): string {
  const parsed = parseTableHeader(headerLine);
  const first = parsed?.keys[0];
  if (parsed === null || first === undefined) return headerLine.trim();
  const second = parsed.keys[1];
  if (bareKeyName(first) === "hooks" && second !== undefined) return `${first}.${second}`;
  return first;
}

/** One representative header per distinct foreign namespace found between
 * `from` and `to` (e.g. all `[hooks.state."..."]` sub-tables collapse to
 * one entry), in first-seen order. A namespace with more than one table
 * under it prints its root with a wildcard and a count (e.g.
 * `[hooks.state.*] (3 tables)`) instead of the first table's own header,
 * so the operator reads "a whole namespace, N tables" rather than
 * mistaking the printed header for the only table kept; exactly one table
 * under a root prints its own header. Headers print through
 * `describeTableHeader` (no trailing comment). A header that is one of the
 * `kept` operator hook tables (a hook event table spelled without the
 * `[[hooks.` prefix, see `collectKeptHookTables`) is named there instead and
 * not listed twice. */
function collectForeignSectionHeaders(
  text: string,
  from: number,
  to: number,
  kept: readonly KeptHookTable[] = [],
): string[] {
  const seenRoots = new Set<string>();
  const headers: string[] = [];
  const counts = new Map<string, number>();
  const keptStarts = new Set(kept.map((t) => t.start));
  let pos = Math.max(from, 0);
  const limit = Math.max(to, from);
  const classify = createLineClassifier(text);
  while (pos < limit) {
    const lineEnd = Math.min(lineEndAfter(text, pos), limit);
    const rawLine = text.slice(pos, lineEnd);
    if (classify(pos, rawLine) === "foreignHeader" && !keptStarts.has(pos)) {
      const trimmed = rawLine.trim();
      const root = foreignSectionRootKey(trimmed);
      counts.set(root, (counts.get(root) ?? 0) + 1);
      if (!seenRoots.has(root)) {
        seenRoots.add(root);
        headers.push(describeTableHeader(trimmed));
      }
    }
    pos = lineEnd;
  }
  return headers.map((header) => {
    const root = foreignSectionRootKey(header);
    const count = counts.get(root) ?? 1;
    return count > 1 ? `[${root}.*] (${count} tables)` : header;
  });
}

/** The hook ids named by the `# harness hook:` marker lines
 * (`createMarkerLineProbe`) in `[from, to)` of `text`, so a value holding
 * that text is never reported as a removed hook. */
function extractHookIds(text: string, from = 0, to = text.length): Set<string> {
  const ids = new Set<string>();
  const isMarkerLine = createMarkerLineProbe(text);
  for (let pos = from; pos < to; pos = lineEndAfter(text, pos)) {
    if (!isMarkerLine(pos, HARNESS_HOOK_COMMENT_PREFIX, "prefix")) continue;
    const m = HOOK_ID_LINE_RE.exec(text.slice(pos, lineEndAfter(text, pos)).trim());
    if (m?.[1] !== undefined) ids.add(m[1]);
  }
  return ids;
}

/**
 * The operator-authored hook tables directly after a managed range: every
 * hook event table header from `from` up to the first non-hook table header
 * or `to`, each by header, line number and offset. A hook event table is a
 * `[[hooks.*]]` header, or an array-of-tables header spelled another way
 * whose first key resolves to `hooks` and that names an event
 * (`isHookEventArrayHeader`: `[[ hooks.Stop ]]`, `[["hooks".Stop]]`,
 * `[[hooks . Stop]]`). The ownership scan reads such a respelled header as a
 * foreign table, so it ends the managed range there; collected here, it is
 * named and its commands are checked like any kept hook table, instead of
 * being kept as a foreign section whose harness command would then run next
 * to the fresh block's (task e8f4fc03). Lines are read by
 * `createLineClassifier`, so an array element on its own line inside a kept
 * table's multi-line value neither ends the run nor is named, and a hook
 * table after it is still collected (task 01053b27). Empty when the first
 * header at `from` is a non-hook table, or there is none. A hook table after
 * the first non-hook table is not collected: it is kept, not named and not
 * checked, a deliberate boundary (only the run of hook tables directly after
 * the harness tables is examined). The caller refuses a zone that holds a
 * harness marker (`assertNoSplitBlock`) before it uses the tables: over the
 * whole zone on the BEGIN path and when an END marker follows, over the run
 * of hook tables (up to the returned `end`) on the legacy path without one,
 * so no table the install keeps carries a `# harness hook:` comment.
 */
function collectKeptHookTables(text: string, from: number, to: number): KeptHookRun {
  const tables: KeptHookTable[] = [];
  let pos = from;
  const classify = createLineClassifier(text);
  while (pos < to) {
    const lineEnd = Math.min(lineEndAfter(text, pos), to);
    const rawLine = text.slice(pos, lineEnd);
    const kind = classify(pos, rawLine);
    const hookTable =
      kind === "hookHeader" || (kind === "foreignHeader" && isHookEventArrayHeader(rawLine.trim()));
    if (kind === "foreignHeader" && !hookTable) break;
    if (hookTable) {
      tables.push({ header: describeTableHeader(rawLine), line: lineNumberAt(text, pos), start: pos });
    }
    pos = lineEnd;
  }
  return { tables, end: pos };
}

/** The kept hook tables `collectKeptHookTables` found and the offset its run
 * stopped at: the first non-hook table header after `from`, or `to`. */
interface KeptHookRun {
  tables: KeptHookTable[];
  end: number;
}

/** A kept table as the install names it: its header, its 1-based line
 * number in the config before the install and in the config the install
 * writes (`nextLines`, same order as `kept`), never any value text. */
function describeKeptHookTables(kept: KeptHookTable[], nextLines: number[]): string[] {
  return kept.map(
    (t, i) => `${t.header} (line ${t.line} before the install, line ${nextLines[i]} after it)`,
  );
}

/** An operator-authored hook table the managed-range scan ended the block
 * at, kept after the fresh block (task 01053b27): its header as printed, its
 * 1-based line number and the offset of its header line in the current
 * config. Its commands are read from the parsed whole document, matched by
 * that offset (`assertKeptHookTablesAreOperatorOwned`); the table's own text
 * is never parsed on its own and never printed. */
interface KeptHookTable {
  header: string;
  line: number;
  start: number;
}

interface ManagedRange {
  start: number;
  end: number;
  /** A stray END-marker line beyond `end` to excise (task 6a037359). */
  strayEnd?: { start: number; end: number };
  foreignSectionsPreserved: string[];
  keptHookTables: KeptHookTable[];
}

const UTF8_BOM = "\uFEFF";

/** A leading UTF-8 BOM is not part of any managed range: a range that would
 * start at offset 0 starts just past the BOM instead, so the splice keeps
 * the BOM exactly once (task b34ed105). */
function startPastBom(text: string, start: number): number {
  return start === 0 && text.startsWith(UTF8_BOM) ? UTF8_BOM.length : start;
}

/**
 * The range from `start` to `end`, where the ownership scan stopped short of
 * an END marker, plus what it keeps after `end`: when a stray END marker line
 * follows (a drifted END), the zone up to it is checked for a split block
 * (`assertNoSplitBlock`), its foreign sections and kept operator hook tables
 * are collected, and that END line is excised by the splice (`strayEnd`);
 * without one, the same happens up to the end of the document. Content below
 * that END line is never read here and the splice leaves it untouched.
 * `blockOpening` is the line the split-block refusal names as the start of
 * the block (`assertNoSplitBlock`; the BEGIN marker when omitted).
 */
function rangeBeforeStrayEnd(
  text: string,
  start: number,
  end: number,
  configPath: string,
  blockOpening?: string,
  zoneFrom = end,
): ManagedRange {
  const strayIdx = findMarkerLine(text, CODEX_MANAGED_END, "whole", end);
  if (strayIdx === -1) {
    assertNoSplitBlock(text, end, text.length, configPath, false);
    const keptHookTables = collectKeptHookTables(text, end, text.length).tables;
    const foreignSectionsPreserved = collectForeignSectionHeaders(text, end, text.length, keptHookTables);
    return { start, end, foreignSectionsPreserved, keptHookTables };
  }

  const strayLineStart = lineStartAt(text, strayIdx);
  const strayLineEnd = lineEndAfter(text, strayIdx);
  assertNoSplitBlock(text, zoneFrom, strayLineStart, configPath, true, blockOpening);
  const keptHookTables = collectKeptHookTables(text, end, strayLineStart).tables;
  const foreignSectionsPreserved = collectForeignSectionHeaders(text, end, strayLineStart, keptHookTables);
  return {
    start,
    end,
    strayEnd: { start: strayLineStart, end: strayLineEnd },
    foreignSectionsPreserved,
    keptHookTables,
  };
}

/**
 * The range of a legacy (no BEGIN marker) config: the source-prefix or
 * generated-header paths. When the scan ended at an operator hook table,
 * or at a foreign table with an END marker after it, the zone after it is
 * handled like the BEGIN path's (`rangeBeforeStrayEnd`): an END marker that
 * survived its deleted BEGIN line, sitting after the kept tables or the
 * foreign table, is excised like a drifted END, so the install leaves no
 * orphan END line and the kept-table refusal offers moving an operator-owned
 * table below that END; a harness-commented table after the kept tables or
 * the foreign table refuses through the split-block check instead of being
 * kept as if it were operator content (the fresh block would repeat it)
 * when it sits before that END, or, after kept tables, anywhere later when
 * no END follows (task e8f4fc03 extends the END case to a foreign table).
 * Content below that END is untouched, as on the BEGIN path, so a
 * harness-commented table there is kept and not named. The split-block
 * refusal names `blockOpening` (the source-prefix line or the generated
 * header) as the start of the block, since there is no BEGIN marker (task
 * 01053b27); the split-block zone starts after that opening line, so a block
 * with no hook table in it (the source prefix directly above an operator
 * table) is not refused for its own opening line (task 36d962d2). The opening
 * line is a marker line (`createMarkerLineProbe`), so marker text inside a
 * value or after a content line opens no block.
 * A scan that ended at a foreign table with no END marker anywhere after it
 * keeps the legacy behaviour (no split-block check), except that hook event tables directly after the block are collected, named and
 * checked (`collectKeptHookTables`), and a harness marker in their run
 * refuses through the split-block check. The END marker is looked up as a
 * marker line too, so END text in a foreign table's value does not route a
 * config here. Like the BEGIN path,
 * the split-block check matches its markers as substrings, so a value in the
 * zone that holds marker text refuses too (see `assertNoSplitBlock`).
 */
function legacyManagedRange(
  text: string,
  start: number,
  scan: { end: number; sawEndMarker: boolean; endedAtOperatorHookTable?: true },
  configPath: string,
  blockOpening: string,
): ManagedRange {
  if (scan.sawEndMarker) {
    return { start, end: scan.end, foreignSectionsPreserved: [], keptHookTables: [] };
  }
  // The split-block zone starts after the block's own opening line: when the
  // scan owned nothing (the generated header or a foreign table directly
  // follows the source prefix), `scan.end` is that opening line itself, which
  // is a split-block marker and would refuse a block with nothing in it
  // (task 36d962d2).
  const zoneFrom = Math.max(scan.end, lineEndAfter(text, start));
  if (scan.endedAtOperatorHookTable || findMarkerLine(text, CODEX_MANAGED_END, "whole", scan.end) !== -1) {
    return rangeBeforeStrayEnd(text, start, scan.end, configPath, blockOpening, zoneFrom);
  }
  const run = collectKeptHookTables(text, scan.end, text.length);
  // The scan ended at a hook table spelled without the `[[hooks.` prefix: a
  // harness marker in the run of hook tables after it (a harness-commented
  // table, or the respelled table's own comment line) is harness content the
  // scan could not read, so refuse through the split-block check, as the
  // BEGIN path does, instead of naming a table with that comment line above it
  // as one without (task e8f4fc03). The run stops at the first non-hook table:
  // past it the legacy reading below stays unchanged.
  if (run.tables.length > 0) assertNoSplitBlock(text, zoneFrom, run.end, configPath, false);
  const keptHookTables = run.tables;
  const foreignSectionsPreserved = collectForeignSectionHeaders(text, scan.end, text.length, keptHookTables);
  return { start, end: scan.end, foreignSectionsPreserved, keptHookTables };
}

function findManagedRange(text: string, configPath: string): ManagedRange | null {
  // BEGIN is found as a marker line (`createMarkerLineProbe`): BEGIN text in
  // an operator value (a string, a trailing comment) is neither the block nor
  // a second marker, so the install neither deletes operator content after
  // it nor splices the fresh block into the value (task 36d962d2).
  const begin = findMarkerLine(text, CODEX_MANAGED_BEGIN, "prefix");
  if (begin !== -1) {
    const secondBegin = findMarkerLine(text, CODEX_MANAGED_BEGIN, "prefix", lineEndAfter(text, begin));
    if (secondBegin !== -1) {
      // Names the second marker's line number only, never that line's own
      // text, since this refusal is printed to stderr and `--json`.
      const secondBeginLineNumber = lineNumberAt(text, secondBegin);
      throw new CodexInstallRefusalError(
        `Codex config ${configPath} has more than one '${CODEX_MANAGED_BEGIN}' marker ` +
          `(a second one at line ${secondBeginLineNumber}); refusing to ` +
          "guess which one is current. Delete the entire unwanted BEGIN/END pair -- including " +
          `its own '${CODEX_MANAGED_BEGIN}' and '${CODEX_MANAGED_END}' marker lines (and its ` +
          `'${CODEX_MANAGED_SOURCE_PREFIX}' source-prefix comment line, if it has one) -- ` +
          "keeping exactly one pair, then re-run `harness apply --runtime codex --install`. As " +
          `a last resort, restore ${configPath} from the most recent .harness-backup-* file (if one exists), ` +
          "but that discards any Codex state (hook trust entries, marketplaces, plugins) " +
          "written to the file since that backup.",
        configPath,
      );
    }
    let start = begin;
    const prev = previousLine(text, start);
    // Only a marker line is the block's source prefix: the closing line of a
    // multi-line string that ends with the prefix text is the operator's
    // value, not part of the block (task 36d962d2). Trimming also drops a BOM
    // sitting before the source-prefix comment on line 1 (task b34ed105).
    if (prev && createMarkerLineProbe(text)(prev.start, CODEX_MANAGED_SOURCE_PREFIX, "prefix")) {
      start = prev.start;
    }
    start = startPastBom(text, start);

    const contentStart = lineEndAfter(text, begin);
    const scan = scanOwnedContentEnd(text, contentStart);
    const end = scan.end;

    if (scan.sawEndMarker) {
      return { start, end, foreignSectionsPreserved: [], keptHookTables: [] };
    }
    return rangeBeforeStrayEnd(text, start, end, configPath);
  }

  const source = findMarkerLine(text, CODEX_MANAGED_SOURCE_PREFIX, "prefix");
  if (source !== -1) {
    const start = startPastBom(text, source);
    return legacyManagedRange(
      text,
      start,
      scanOwnedContentEnd(text, start),
      configPath,
      `the '${CODEX_MANAGED_SOURCE_PREFIX}' source-prefix line`,
    );
  }

  const generated = findMarkerLine(text, GENERATED_HEADER, "prefix");
  if (generated !== -1) {
    const start = startPastBom(text, generated);
    const scan = scanOwnedContentEnd(text, start);
    // The generated header opens a legacy block only when a hook table header
    // line (`[[hooks.`, the older `[[hooks.pre_tool_use]]` included) follows
    // it inside the scanned range, found by the same top-level line rule as
    // the markers: `[[hooks.` text in a value, a multi-line string line or a
    // comment under an operator table is operator content, and taking it for
    // a header made the install replace the operator's keys after the header
    // line with the fresh block (task 36d962d2).
    const hookHeader = findMarkerLine(text, "[[hooks.", "prefix", start);
    if (hookHeader !== -1 && hookHeader < scan.end) {
      return legacyManagedRange(text, start, scan, configPath, GENERATED_HEADER_OPENING);
    }
  }

  return null;
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith("\n") ? s : `${s}\n`;
}

function buildManagedBlock(
  generatedContent: string,
  generatedPath: string,
): string {
  return [
    `${CODEX_MANAGED_SOURCE_PREFIX} Generated source: ${generatedPath}`,
    CODEX_MANAGED_BEGIN,
    ensureTrailingNewline(generatedContent).trimEnd(),
    CODEX_MANAGED_END,
    "",
  ].join("\n");
}

export function validateCodexManagedConfig(content: string): void {
  const lines = content.split(/\r?\n/);
  const legacyLine = lines.find((line) => {
    const trimmed = line.trim();
    return (
      LEGACY_HOOK_TABLE_RE.test(trimmed) ||
      trimmed.startsWith("timeout_ms =") ||
      trimmed.startsWith("blocking =") ||
      trimmed.startsWith("match =")
    );
  });
  if (legacyLine !== undefined) {
    throw new Error(
      `generated Codex config still uses legacy hook schema: ${legacyLine.trim()}`,
    );
  }

  const hookTableIndexes: number[] = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (CURRENT_HOOK_TABLE_RE.test(lines[i]!.trim())) hookTableIndexes.push(i);
  }
  if (hookTableIndexes.length === 0) return;

  for (let i = 0; i < hookTableIndexes.length; i += 1) {
    const start = hookTableIndexes[i]!;
    const end = hookTableIndexes[i + 1] ?? lines.length;
    const segment = lines.slice(start, end).join("\n");
    if (!segment.includes("hooks = [")) {
      throw new Error(
        `generated Codex hook table is missing hooks array: ${lines[start]!.trim()}`,
      );
    }
    if (
      !segment.includes('type = "command"') ||
      !/command = "([^"\\]|\\.)+"/.test(segment) ||
      !/timeout = [1-9][0-9]*/.test(segment)
    ) {
      throw new Error(
        `generated Codex hook table has invalid command hook shape: ${lines[start]!.trim()}`,
      );
    }
  }
}

/** Parses a Codex config for the safety net below. A leading UTF-8 byte
 * order mark is not TOML content, so it is skipped for parsing only (the
 * bytes written are never changed here). Integers beyond JavaScript's safe
 * range, which TOML allows (64-bit), come back as a `bigint` instead of
 * failing the parse. */
function parseToml(content: string): unknown {
  const body = content.startsWith("\uFEFF") ? content.slice(1) : content;
  return parseTomlDocument(body, { integersAsBigInt: "asNeeded" });
}

/** Where and why the parser rejected a document, for a refusal message:
 * the line and column it reports plus the first line of its message, and
 * nothing else. The rest of a `TomlError` message is a code frame quoting
 * the surrounding lines of the document verbatim; a Codex config holds
 * secrets (API tokens under `[mcp_servers.*]`), and a refusal is printed to
 * stderr and into `--json` output, so that frame is never included. Any
 * other error is reduced to its name for the same reason. */
function describeTomlParseError(err: unknown): string {
  if (err instanceof TomlError) {
    const firstLine = err.message.split("\n", 1)[0] ?? "";
    const reason = firstLine.replace(/^Invalid TOML document: /, "");
    return `line ${err.line}, column ${err.column}: ${reason}`;
  }
  return err instanceof Error ? err.name : "unknown parse error";
}

/** True for a parsed TOML table: a non-array, non-date object. */
function isTomlTable(value: unknown): value is Record<string, unknown> {
  return (
    typeof value === "object" && value !== null && !Array.isArray(value) && !(value instanceof Date)
  );
}

/** Every ARRAY-valued key directly under `doc.hooks` (the `[[hooks.<Event>]]`
 * event arrays, the only shape the installer writes) removed, keeping every
 * other `hooks.*` key (single tables such as `hooks.state`, or any future
 * non-array key) untouched. Everything the result still holds, including all
 * of `hooks.state`, is not the installer's to change. The stripped `hooks`
 * map is a null-prototype object, so a key literally named `__proto__`
 * stays an own key instead of re-pointing the map's prototype and dropping
 * out of the comparison. A non-table `doc`, and a missing or non-table
 * `hooks` value, are returned as-is: there is nothing to strip. */
function stripManagedHookArrays(doc: unknown): unknown {
  if (!isTomlTable(doc)) return doc;
  const obj = doc;
  const hooks = obj.hooks;
  if (!isTomlTable(hooks)) return obj;
  const strippedHooks = Object.create(null) as Record<string, unknown>;
  for (const [key, value] of Object.entries(hooks)) {
    if (Array.isArray(value)) continue;
    strippedHooks[key] = value;
  }
  const result: Record<string, unknown> = { ...obj };
  if (Object.keys(strippedHooks).length === 0) {
    // A document all of whose `hooks.*` keys were array-valued (the
    // common case: nothing but harness-managed event arrays) must strip
    // down to "no hooks key at all", the same as a document that never
    // had one, so the comparison never flags the mere PRESENCE of an
    // (empty, post-strip) `hooks` table as a semantic difference.
    delete result.hooks;
  } else {
    result.hooks = strippedHooks;
  }
  return result;
}

/** A date/time value's identity for comparison: its as-written TOML form
 * (`TomlDate.toISOString` keeps local date, local time, local date-time
 * and offset forms apart), or `invalid` for an unparseable date. */
function dateIdentity(value: Date): string {
  return Number.isNaN(value.getTime()) ? "invalid" : value.toISOString();
}

/** The path (as a dotted string once joined by the caller) to the first
 * value at which `a` and `b` differ, walking tables and arrays recursively
 * and comparing primitives (including `bigint`) with `Object.is` and
 * date/time values by `dateIdentity`; `null` means the two are deeply
 * equal. A key present on one side only is a difference at that key (and,
 * when it holds a table, at that table's first key). Key
 * order follows `a`'s own insertion order first, then any key present only
 * in `b`, so the reported path is deterministic. */
function firstDifferingKeyPath(a: unknown, b: unknown, path: string[]): string[] | null {
  if (a instanceof Date || b instanceof Date) {
    if (!(a instanceof Date) || !(b instanceof Date)) return path;
    return dateIdentity(a) === dateIdentity(b) ? null : path;
  }
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return path;
    for (let i = 0; i < a.length; i += 1) {
      const diff = firstDifferingKeyPath(a[i], b[i], [...path, String(i)]);
      if (diff) return diff;
    }
    return null;
  }
  if (typeof a === "object" && a !== null && typeof b === "object" && b !== null) {
    const aObj = a as Record<string, unknown>;
    const bObj = b as Record<string, unknown>;
    const keys = new Set([...Object.keys(aObj), ...Object.keys(bObj)]);
    for (const key of keys) {
      const aHas = Object.hasOwn(aObj, key);
      if (aHas !== Object.hasOwn(bObj, key)) {
        // A whole table present on one side only: name its first key too
        // (`hooks.state` rather than just `hooks`), so the refusal points at
        // what was lost.
        const present = aHas ? aObj[key] : bObj[key];
        const child = isTomlTable(present) ? Object.keys(present)[0] : undefined;
        return child === undefined ? [...path, key] : [...path, key, child];
      }
      const diff = firstDifferingKeyPath(aObj[key], bObj[key], [...path, key]);
      if (diff) return diff;
    }
    return null;
  }
  return Object.is(a, b) ? null : path;
}

/**
 * The TOML-semantic safety net (task 6a037359). The byte-preserving text
 * splice in `planCodexConfigInstall` stays the source of truth for what gets
 * WRITTEN; before it is written, `currentContent` and `nextContent` are
 * both parsed and compared, and the install refuses rather than writes when
 * the comparison finds a change outside what the installer owns. It exists
 * to catch a scanner defect (a shape the line-based scan above mishandles)
 * that would otherwise silently drop or alter operator- or Codex-owned
 * content.
 *
 * The invariant: both documents must parse, and once every ARRAY-valued key
 * directly under `hooks` (the `[[hooks.<Event>]]` event arrays) is removed
 * from both, what remains must be deep-equal. What remains is everything
 * outside the hook event arrays: `hooks.state` and every other single-table
 * `hooks.*` key, plus all non-hooks content (top-level keys, `projects`,
 * `plugins`, `marketplaces`, `mcp_servers`, `tui`, ...). A refusal names the
 * first differing key path.
 *
 * What it does NOT check: the hook event arrays themselves. The installer
 * rewrites its own entries there, and telling an operator-authored entry
 * from a harness-written one would need the same line-level reading of the
 * file this net is meant to be independent of. An operator-authored
 * `[[hooks.<Event>]]` entry that the line scan wrongly counts as part of
 * the harness-managed block is therefore replaced without a refusal (task
 * 01053b27 covers the operator table after the harness tables, which the scan
 * now keeps and names; still replaced silently are an operator table before
 * the first harness table inside the block, one under a comment run that
 * holds a `# harness hook:` line, bare keys directly under a harness table,
 * and one after an old block that never carried the comments).
 *
 * Parsing goes through `parseToml` (a leading byte order mark ignored,
 * 64-bit integers kept as `bigint`). A document that does not parse refuses
 * with the parser's line, column and one-line reason only, never the
 * document's own text (`describeTomlParseError`). This function never
 * touches the file, and a `--dry-run` plan reports the same refusal a real
 * install would (both go through `planCodexConfigInstall`).
 */
export function assertConfigSemanticInvariant(
  currentContent: string,
  nextContent: string,
  configPath: string,
): void {
  let currentDoc: unknown;
  try {
    currentDoc = parseToml(currentContent);
  } catch (err) {
    throw new CodexInstallRefusalError(
      `Codex config ${configPath}: the TOML parser used by harness could not read this file ` +
        `(${describeTomlParseError(err)}); refusing to install, because without parsing it ` +
        "harness cannot confirm that every table outside the harness-managed hook block " +
        "would survive the install. The file is untouched. If Codex itself loads this file, " +
        "the construct at that position is one this parser does not support; please report " +
        "it as a harness issue (the construct, not its value).",
      configPath,
    );
  }

  let nextDoc: unknown;
  try {
    nextDoc = parseToml(nextContent);
  } catch (err) {
    throw new CodexInstallRefusalError(
      `The Codex config harness would write to ${configPath} would not parse as TOML ` +
        `(in the would-be output, ${describeTomlParseError(err)}); refusing to write a config ` +
        "that would not load. The file is untouched. A common cause is the current file " +
        "already defining `hooks`, or a hook event under it, in a form the generated " +
        "`[[hooks.<Event>]]` tables cannot extend: an inline table such as `hooks = { ... }`, " +
        "or an inline array such as `PreToolUse = []` under `[hooks]`. Rewrite that " +
        "definition as `[hooks.<name>]` / `[[hooks.<Event>]]` tables (or remove it), then " +
        "re-run `harness apply --runtime codex --install`. If the file has no such " +
        "definition, this points at a harness defect (in the generated hook block, or in " +
        "where the install placed it); please report it with the config's shape, not its values.",
      configPath,
    );
  }

  const diffPath = firstDifferingKeyPath(
    stripManagedHookArrays(currentDoc),
    stripManagedHookArrays(nextDoc),
    [],
  );
  if (diffPath) {
    throw new CodexInstallRefusalError(
      `Codex config ${configPath}: installing would change '${diffPath.join(".")}', which is ` +
        "not a harness-managed hook event array; refusing to install rather than risk " +
        "silently dropping or altering operator- or Codex-owned content. The file is " +
        `untouched. If it looks wrong, restore it from the most recent .harness-backup-* file ` +
        "(if one exists), or file an issue with the config shape that triggered this.",
      configPath,
    );
  }
}

/**
 * Follows a dangling link chain hop by hop with `readlink` and returns the
 * first path in it that does not exist, so a dangling refusal names the
 * missing file rather than the first hop (which may be an existing
 * intermediate link). Each relative link text is resolved against the
 * physical directory of the link holding it, as the kernel does. Returns
 * undefined when the chain cannot be walked (it changed under us, or a
 * hop is not readable); the caller then words the refusal generically.
 */
function missingEndOfLinkChain(start: string): string | undefined {
  const MAX_HOPS = 40;
  let current = start;
  for (let hop = 0; hop < MAX_HOPS; hop++) {
    let next: string;
    try {
      const linkText = fs.readlinkSync(current);
      next = path.resolve(fs.realpathSync(path.dirname(current)), linkText);
    } catch {
      return undefined;
    }
    let nextStat: fs.Stats;
    try {
      nextStat = fs.lstatSync(next);
    } catch (err) {
      return (err as NodeJS.ErrnoException).code === "ENOENT" ? next : undefined;
    }
    if (!nextStat.isSymbolicLink()) return undefined;
    current = next;
  }
  return undefined;
}

/**
 * Resolves a symlinked config path to the regular file it points at (task
 * 1637fbc8). `atomicWriteFile` renames a temp file over its destination,
 * which would replace a symlink with a regular file and leave the link's
 * target (typically a dotfiles repo) silently stale; writing to the
 * resolved target instead keeps the link intact. A non-symlink path
 * (including a missing one) is returned unchanged. A dangling link, an
 * unresolvable chain (a loop, a permission error) or a link to anything
 * other than a regular file is refused before anything is written.
 */
function resolveConfigSymlink(requestedPath: string): string {
  let linkStat: fs.Stats;
  try {
    linkStat = fs.lstatSync(requestedPath);
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "ENOENT") return requestedPath;
    throw err;
  }
  if (!linkStat.isSymbolicLink()) return requestedPath;

  let resolved: string;
  try {
    resolved = fs.realpathSync(requestedPath);
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "ENOENT") {
      const missing = missingEndOfLinkChain(requestedPath);
      throw new CodexInstallRefusalError(
        `Codex config ${requestedPath} is a dangling symlink (its link chain ends at ` +
          `${missing ?? "a missing file"}, which does not exist); refusing to install, ` +
          `nothing was written. Create the link's target file (or point the link at an ` +
          `existing config) and re-run.`,
        requestedPath,
      );
    }
    throw new CodexInstallRefusalError(
      `Codex config ${requestedPath} is a symlink that cannot be resolved ` +
        `(${e.code ?? "error"}: ${e.message}); refusing to install, nothing was written. ` +
        `Fix the link chain and re-run.`,
      requestedPath,
    );
  }
  if (!fs.statSync(resolved).isFile()) {
    throw new CodexInstallRefusalError(
      `Codex config ${requestedPath} is a symlink to ${resolved}, which is not a regular ` +
        `file; refusing to install, nothing was written. Point the link at a config file and re-run.`,
      requestedPath,
    );
  }
  return resolved;
}

/**
 * Runs a planning check and, for a symlinked config, extends any refusal
 * that points the operator at a `.harness-backup-*` file with where those
 * backups actually sit: beside the link, not beside the resolved target
 * the refusal names (task 1637fbc8). A non-symlink config (linkPath
 * undefined) keeps every refusal text unchanged.
 */
function withBackupLocation<T>(linkPath: string | undefined, check: () => T): T {
  if (linkPath === undefined) return check();
  try {
    return check();
  } catch (err) {
    if (!(err instanceof CodexInstallRefusalError) || !err.message.includes(".harness-backup-*")) {
      throw err;
    }
    throw new CodexInstallRefusalError(
      `${err.message} This config is reached through the symlink ${linkPath}; its backups ` +
        `sit beside the link, as ${linkPath}.harness-backup-* files.`,
      err.configPath,
    );
  }
}

/** A header key segment's name as TOML reads it: a bare key as written, a
 * literal (`'...'`) key's inner text, a basic (`"..."`) key's inner text
 * when it holds no escape sequence. `null` for a basic key with an escape,
 * which this scan does not decode; a header holding one is not matched to a
 * parsed entry (see `mapHookArrayHeaders`). */
function resolvedKeyName(segment: string): string | null {
  const quote = segment[0];
  if (quote === "'") return segment.slice(1, -1);
  if (quote === '"') {
    const inner = segment.slice(1, -1);
    return inner.includes("\\") ? null : inner;
  }
  return segment;
}

/** Whether a header-shaped line's first key resolves to `hooks`, the only
 * root `mapHookArrayHeaders` resolves. */
function hooksRooted(trimmed: string): boolean {
  return resolvedKeyName(parseTableHeader(trimmed)?.keys[0] ?? "") === "hooks";
}

/** Whether a header line is an array-of-tables header that appends to a
 * hook event array or below one (`[[hooks.Stop]]`, `[[ hooks.Stop ]]`,
 * `[["hooks".Stop]]`, `[[hooks . Stop.hooks]]`): double brackets, a first key
 * that resolves to `hooks` (`hooksRooted`) and at least an event key after
 * it. A one-key line (`[["hooks"]]`, which may also be an array element on
 * its own line) is not one. Used by `collectKeptHookTables` for the
 * spellings the `[[hooks.` prefix does not catch (task e8f4fc03). */
function isHookEventArrayHeader(trimmed: string): boolean {
  const parsed = parseTableHeader(trimmed);
  return (
    parsed !== null && parsed.header.startsWith("[[") && parsed.keys.length >= 2 && hooksRooted(trimmed)
  );
}

/** Where a `[[...]]` header line appends in the parsed document: the
 * `index`-th entry of `hooks.<event>`, or, for `[[hooks.<event>.hooks]]`,
 * the `subIndex`-th entry of that entry's own `hooks` array. */
interface HookArraySlot {
  event: string;
  index: number;
  subIndex?: number;
}

interface HookArrayHeaderMap {
  /** By offset of the header line in the document. */
  slots: Map<number, HookArraySlot>;
  /** Headers seen per event, to compare with the parsed array's length. */
  eventCounts: Map<string, number>;
  /** `[[hooks.<event>.hooks]]` headers seen per entry (`subKey`). */
  subCounts: Map<string, number>;
}

function subKey(event: string, index: number): string {
  return `${event}\u0000${index}`;
}

/**
 * Every table header of the whole document that appends to a hook
 * event array (`[[hooks.<Event>]]`, however its keys are spelled) or to such
 * an entry's own `hooks` array (`[[hooks.<Event>.hooks]]`), with the entry it
 * appends: TOML appends each header's table to its array in document order,
 * and a sub-array header to the array's LAST entry so far. Only the lines
 * `createLineClassifier` reads as a header are resolved: a line inside a
 * multi-line string, and an array element on its own line, are skipped. A line resolved
 * to such a header cannot be a value line of a document that parses (a
 * dotted bare path is not a TOML value), and a header this scan cannot
 * resolve (an escape in a quoted key) is not counted, so the caller compares
 * `eventCounts` and `subCounts` with the parsed arrays' lengths and treats a
 * mismatch as "cannot match exactly". The classifier reads a header-shaped
 * line as a header here only when its root key resolves to `hooks`
 * (`hooksRooted`, checked before the top-level probe), so every header this
 * scan resolves has the root `hooks` (a `[[hooks.` line has it by its
 * prefix), a table outside `hooks` never shifts the order match, and an
 * array element on its own line (`["x"]`, `[1]`) costs no parse in this
 * scan, unless the element line reads as a header whose first key is
 * `hooks` (`["hooks"]`, `['hooks']`, `[["hooks"]]`, `[[ 'hooks' ]]`): that
 * line reads as a `hooks` root, so it is probed like the `hooks`-rooted
 * spellings that `[[hooks.` does not catch (`[[ hooks.Stop ]]`,
 * `[["hooks".Stop]]`, `[hooks.Stop]`), and the probe finds it inside the
 * array.
 */
function mapHookArrayHeaders(text: string): HookArrayHeaderMap {
  const map: HookArrayHeaderMap = { slots: new Map(), eventCounts: new Map(), subCounts: new Map() };
  let pos = 0;
  const classify = createLineClassifier(text, hooksRooted);
  while (pos < text.length) {
    const lineEnd = lineEndAfter(text, pos);
    const rawLine = text.slice(pos, lineEnd);
    const kind = classify(pos, rawLine);
    const parsed = kind === "hookHeader" || kind === "foreignHeader" ? parseTableHeader(rawLine) : null;
    // The bracket kind is not checked: a single-bracket `[hooks.<Event>]`
    // cannot coexist with a `[[hooks.<Event>]]` array in a document that
    // parses, and a single-bracket `[hooks.<Event>.hooks]` makes that entry's
    // `hooks` a table, whose `command` is not a hook command either way.
    if (parsed !== null) {
      const [, event, sub] = parsed.keys.map(resolvedKeyName);
      if (typeof event === "string") {
        const count = map.eventCounts.get(event) ?? 0;
        if (parsed.keys.length === 2) {
          map.slots.set(pos, { event, index: count });
          map.eventCounts.set(event, count + 1);
        } else if (parsed.keys.length === 3 && sub === "hooks") {
          // Appends to the event's last entry so far; with no entry before
          // it (`index` -1) TOML makes the event a table, not an array, and
          // the caller finds no array to match.
          const key = subKey(event, count - 1);
          const subIndex = map.subCounts.get(key) ?? 0;
          map.slots.set(pos, { event, index: count - 1, subIndex });
          map.subCounts.set(key, subIndex + 1);
        }
      }
    }
    pos = lineEnd;
  }
  return map;
}

/** The hook command of one parsed hook entry, `{ command = "..." }`, as a
 * one-element list; empty for anything else. */
function hookCommandOf(entry: unknown): string[] {
  return isTomlTable(entry) && typeof entry.command === "string" ? [entry.command] : [];
}

/** The hook commands of one parsed `hooks.<Event>` entry: its own `command`
 * plus each `command` of its `hooks` array (inline `hooks = [{ ... }]` or the
 * expanded `[[hooks.<Event>.hooks]]` form). No other `command` key counts. */
function eventEntryCommands(entry: unknown): string[] {
  if (!isTomlTable(entry)) return [];
  const nested = Array.isArray(entry.hooks) ? entry.hooks.flatMap(hookCommandOf) : [];
  return [...hookCommandOf(entry), ...nested];
}

/** Every hook command of a parsed document's `hooks.<Event>` arrays. */
function documentHookCommands(doc: unknown): string[] {
  if (!isTomlTable(doc) || !isTomlTable(doc.hooks)) return [];
  return Object.values(doc.hooks).flatMap((value) =>
    Array.isArray(value) ? value.flatMap(eventEntryCommands) : [],
  );
}

/**
 * The hook commands a kept table defines, read from the parsed whole
 * document (`doc`) at the entry its header appends (`map`): for
 * `[[hooks.<Event>]]` the entry's own `command`, plus its `hooks` array's
 * commands unless `[[hooks.<Event>.hooks]]` headers build that array (each
 * of those is its own kept table); for `[[hooks.<Event>.hooks]]` that nested
 * entry's `command`. A header appending nowhere else (`[[hooks.<Event>.x]]`)
 * defines none. `null` when the header cannot be matched exactly: a header
 * the scan did not resolve, a count of headers that differs from the parsed
 * array's length, or a nested `hooks` header with no entry before it.
 */
function keptTableCommands(
  table: KeptHookTable,
  doc: unknown,
  map: HookArrayHeaderMap,
): string[] | null {
  const slot = map.slots.get(table.start);
  if (slot === undefined) {
    // Not an append the map resolved: a `[[hooks.<Event>.x]]` table holds no
    // hook command; a header with a key the map does not resolve cannot be
    // matched.
    const resolved = parseTableHeader(table.header)?.keys.every((k) => resolvedKeyName(k) !== null);
    return resolved === true ? [] : null;
  }
  const hooks = isTomlTable(doc) && isTomlTable(doc.hooks) ? doc.hooks : undefined;
  const entries = hooks?.[slot.event];
  if (!Array.isArray(entries) || entries.length !== map.eventCounts.get(slot.event)) return null;
  const entry: unknown = entries[slot.index];
  const subCount = map.subCounts.get(subKey(slot.event, slot.index)) ?? 0;
  if (slot.subIndex === undefined) {
    return subCount > 0 ? hookCommandOf(entry) : eventEntryCommands(entry);
  }
  const nested = isTomlTable(entry) && Array.isArray(entry.hooks) ? entry.hooks : [];
  if (nested.length !== subCount) return null;
  return hookCommandOf(nested[slot.subIndex]);
}

/** The move-below-END option of a kept-table refusal: only when the config
 * has an END marker after the kept tables, since below it the install never
 * touches a table (an operator-owned table whose command starts with
 * `harness `, the operator's own CLI, is kept that way). Every range with
 * kept tables and an END marker after them records that marker as
 * `strayEnd`, on the BEGIN path and on the legacy paths alike
 * (`rangeBeforeStrayEnd`), so the caller keys the option on it. */
function moveBelowEndOption(hasEndMarker: boolean): string {
  return hasEndMarker
    ? `, or, if it is an operator-owned table, move it below the '${CODEX_MANAGED_END}' marker, ` +
        "where the install never touches it"
    : "";
}

/** Parses the whole document for the kept-table check, refusing with the
 * parser's position and one-line reason only (never its code frame). */
function parseForKeptTableCheck(content: string, what: string, configPath: string): unknown {
  try {
    return parseToml(content);
  } catch (err) {
    throw new CodexInstallRefusalError(
      `Codex config ${configPath}: the TOML parser used by harness could not read ${what} ` +
        `(${describeTomlParseError(err)}), so harness cannot check the operator hook tables it ` +
        "would keep after the harness hook tables; refusing to install. The file is untouched.",
      configPath,
    );
  }
}

/**
 * Refuses (file untouched) when an operator hook table the install keeps
 * looks like one harness wrote: one of its hook commands equals a command of
 * the fresh block, or starts with `harness `. The line scan tells a harness
 * table from an operator one only by the `# harness hook:` comment above it,
 * so a harness table whose comment an operator deleted, sitting last, would
 * otherwise be kept next to the fresh block: the hook would run twice, or a
 * hook the manifest retired would keep running after every later install
 * (task 01053b27). A retired hook whose command does not start with
 * `harness ` (an environment-prefixed report-dir wrap, the memory-router
 * hook, a custom manifest hook) is not recognised: it is kept and named only.
 *
 * The commands come from the parsed WHOLE document (the same `parseToml` the
 * semantic net uses), each kept table matched to its parsed entry by the
 * order of the `[[hooks.<Event>]]` headers (`mapHookArrayHeaders`); no part
 * of the file is parsed on its own. Only hook commands count
 * (`hooks.<Event>[].command` and `hooks.<Event>[].hooks[].command`), not any
 * other key named `command`. A kept table that cannot be matched exactly
 * refuses too. Every message names the table's header and line number only,
 * never a command or any other value text, and never a parser code frame,
 * since a refusal is printed to stderr and into `--json` output.
 */
function assertKeptHookTablesAreOperatorOwned(
  kept: KeptHookTable[],
  currentContent: string,
  generatedContent: string,
  configPath: string,
  hasEndMarker: boolean,
): void {
  if (kept.length === 0) return;
  const freshCommands = new Set(
    documentHookCommands(parseForKeptTableCheck(generatedContent, "the generated hook block", configPath)),
  );
  const doc = parseForKeptTableCheck(currentContent, "this file", configPath);
  const map = mapHookArrayHeaders(currentContent);
  for (const table of kept) {
    const commands = keptTableCommands(table, doc, map);
    if (commands === null) {
      throw new CodexInstallRefusalError(
        `Codex config ${configPath} has a hook table ${table.header} (line ${table.line}) with no ` +
          `'${HARNESS_HOOK_COMMENT_PREFIX}<id> (budget_ms=<n>)' comment line above it, placed after the ` +
          "harness hook tables, that harness could not match to its entry in the parsed config " +
          "(a header it does not resolve: an escape sequence in a quoted key, on this table or on " +
          "another table of the same hook event, or a nested hooks table it cannot place), so it " +
          "cannot check whether harness wrote that table. Spell those header keys without escape " +
          `sequences, restore the '${HARNESS_HOOK_COMMENT_PREFIX}<id> (budget_ms=<n>)' comment line ` +
          `directly above ${table.header} if harness wrote it${moveBelowEndOption(hasEndMarker)}, or ` +
          "delete the table, then re-run `harness apply --runtime codex --install`. The file is untouched.",
        configPath,
      );
    }
    const harnessShaped = commands.some(
      (command) => freshCommands.has(command) || command.startsWith("harness "),
    );
    if (!harnessShaped) continue;
    // harness writes every hook table as `[[hooks.<Event>]]`; a table spelled
    // another way (`[[ hooks.Stop ]]`) never was one, and with the comment
    // line restored above it the scan would still read it as a foreign
    // table, so the restore fix is offered only for the harness spelling
    // (task e8f4fc03).
    const fix = HOOK_ARRAY_HEADER_RE.test(table.header)
      ? `Restore the comment line directly above ${table.header}, so the install replaces the table ` +
        `with the fresh block${moveBelowEndOption(hasEndMarker)}, or delete the table`
      : "Delete the table (the install replaces only hook tables spelled '[[hooks.<Event>]]' with " +
        `that comment line above them)${moveBelowEndOption(hasEndMarker)}`;
    throw new CodexInstallRefusalError(
      `Codex config ${configPath} has a hook table ${table.header} (line ${table.line}) with no ` +
        `'${HARNESS_HOOK_COMMENT_PREFIX}<id> (budget_ms=<n>)' comment line above it, placed after the ` +
        "harness hook tables, whose command is one harness itself writes. harness cannot tell it " +
        "from a harness hook table whose comment line was deleted, and keeping it next to the " +
        "fresh harness block would run that hook twice (or keep a retired harness hook running). " +
        `${fix}, then re-run \`harness apply --runtime codex --install\`. The file is untouched.`,
      configPath,
    );
  }
}

export function planCodexConfigInstall(
  opts: CodexConfigInstallOptions,
): CodexConfigInstallPlan {
  validateCodexManagedConfig(opts.generatedContent);

  const requestedPath = opts.configPath ?? defaultCodexConfigPath(opts.homeDir);
  const configPath = resolveConfigSymlink(requestedPath);
  const linkPath = configPath !== requestedPath ? requestedPath : undefined;
  const viaLink = linkPath !== undefined ? ` (via symlink ${linkPath})` : "";
  let currentContent = "";
  let configExisted = true;
  try {
    currentContent = fs.readFileSync(configPath, "utf8");
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code !== "ENOENT") throw err;
    configExisted = false;
  }

  const managedBlock = buildManagedBlock(
    opts.generatedContent,
    opts.generatedPath,
  );
  const range = withBackupLocation(linkPath, () => findManagedRange(currentContent, configPath));
  let nextContent: string;
  let summary: string;
  let removedHookIds: string[] = [];
  let foreignSectionsPreserved: string[] = [];
  let keptHookTables: KeptHookTable[] = [];
  let keptTableDescriptions: string[] = [];
  let hasEndMarkerAfterKept = false;
  if (range) {
    const oldHookIds = extractHookIds(currentContent, range.start, range.end);
    const newHookIds = extractHookIds(managedBlock);
    removedHookIds = [...oldHookIds].filter((id) => !newHookIds.has(id));
    keptHookTables = range.keptHookTables;
    hasEndMarkerAfterKept = range.strayEnd !== undefined;

    const middleForeign = range.strayEnd
      ? currentContent.slice(range.end, range.strayEnd.start)
      : "";
    const tailStart = range.strayEnd ? range.strayEnd.end : range.end;
    nextContent = `${currentContent.slice(0, range.start)}${managedBlock}${middleForeign}${currentContent.slice(tailStart)}`;
    // A kept table sits right after the fresh block in the written config
    // (it is in `middleForeign`, or at the start of the tail when there is
    // no stray END), so its offset there follows from the splice.
    const shift = range.start + managedBlock.length - range.end;
    keptTableDescriptions = describeKeptHookTables(
      keptHookTables,
      keptHookTables.map((t) => lineNumberAt(nextContent, t.start + shift)),
    );
    // The kept operator hook tables ride the same list, so the dry-run and
    // the install summary name them exactly like the foreign tables kept
    // beside them (task 01053b27).
    foreignSectionsPreserved = [...range.foreignSectionsPreserved, ...keptTableDescriptions];
    summary = `updated harness-managed Codex hook block in ${configPath}${viaLink}`;
  } else {
    const prefix =
      currentContent.length === 0
        ? ""
        : currentContent.endsWith("\n\n")
          ? ""
          : currentContent.endsWith("\n")
            ? "\n"
            : "\n\n";
    nextContent = `${currentContent}${prefix}${managedBlock}`;
    summary = `installed harness-managed Codex hook block into ${configPath}${viaLink}`;
  }

  if (currentContent !== nextContent) {
    withBackupLocation(linkPath, () =>
      assertConfigSemanticInvariant(currentContent, nextContent, configPath),
    );
  }
  assertKeptHookTablesAreOperatorOwned(
    keptHookTables,
    currentContent,
    opts.generatedContent,
    configPath,
    hasEndMarkerAfterKept,
  );

  return {
    configPath,
    ...(linkPath !== undefined ? { linkPath } : {}),
    generatedPath: opts.generatedPath,
    currentContent,
    nextContent,
    changed: currentContent !== nextContent,
    configExisted,
    summary:
      currentContent === nextContent
        ? `Codex config already up to date: ${configPath}${viaLink}`
        : summary,
    removedHookIds,
    foreignSectionsPreserved,
    keptOperatorHookTables: keptTableDescriptions,
  };
}

function timestampForBackup(now: Date): string {
  return now.toISOString().replace(/[:.]/g, "-");
}

/** The config holds operator secrets (API tokens under `[mcp_servers.*]`,
 * Codex hook trust hashes); the install must never widen its permissions.
 * Preserves the existing file's own mode for both the rewritten config and
 * its backup, and falls back to `0o600` (owner read/write only) when
 * creating a config that did not exist before this install, rather than
 * `atomicWriteFile`'s own `0o644` default. */
function existingFileMode(filePath: string): number {
  try {
    return fs.statSync(filePath).mode & 0o777;
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code !== "ENOENT") throw err;
    return 0o600;
  }
}

export function writeCodexConfigInstall(
  plan: CodexConfigInstallPlan,
  opts: { now?: Date } = {},
): CodexConfigInstallResult {
  if (!plan.changed) return { ...plan, written: false };
  fs.mkdirSync(path.dirname(plan.configPath), { recursive: true });
  const mode = existingFileMode(plan.configPath);
  // Only back up a config that actually existed before this install (task
  // 461ec064): a fresh install has nothing to protect, and writing a
  // 0-byte backup for it misreported a write that never happened.
  if (!plan.configExisted) {
    atomicWriteFile(plan.configPath, plan.nextContent, { mode });
    return { ...plan, written: true };
  }
  // A symlinked config's backup sits beside the link (task 1637fbc8), not
  // beside the resolved target: the config holds secrets, and the target's
  // directory is typically a dotfiles git work tree where an untracked
  // backup is one `git add` away from being pushed. The backup is a fresh
  // file, so it need not share the target's filesystem; only the atomic
  // write of the target itself (temp file plus rename) must.
  const backupBase = plan.linkPath ?? plan.configPath;
  const backupPath = `${backupBase}.harness-backup-${timestampForBackup(opts.now ?? new Date())}`;
  atomicWriteFile(backupPath, plan.currentContent, { mode });
  atomicWriteFile(plan.configPath, plan.nextContent, { mode });
  return { ...plan, backupPath, written: true };
}
