import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { atomicWriteFile } from "../../io/atomic-write.js";

export const CODEX_MANAGED_SOURCE_PREFIX = "# Harness Codex hook wiring.";
export const CODEX_MANAGED_BEGIN = "# BEGIN harness-managed codex hooks";
export const CODEX_MANAGED_END = "# END harness-managed codex hooks";

const GENERATED_HEADER = "# Generated by harness apply --runtime codex.";
const LEGACY_HOOK_TABLE_RE =
  /^\[\[hooks\.(pre_tool_use|post_tool_use|user_prompt_submit|session_start|stop)\]\]$/;
const CURRENT_HOOK_TABLE_RE = /^\[\[hooks\.[A-Za-z][A-Za-z0-9_]*\]\]$/;
const NON_HOOK_TABLE_RE = /^\[(?!\[hooks\.)/;

export interface CodexConfigInstallPlan {
  configPath: string;
  generatedPath: string;
  currentContent: string;
  nextContent: string;
  changed: boolean;
  summary: string;
}

export interface CodexConfigInstallResult extends CodexConfigInstallPlan {
  backupPath?: string;
  written: boolean;
}

export interface CodexConfigInstallOptions {
  configPath?: string;
  homeDir?: string;
  generatedPath: string;
  generatedContent: string;
  now?: Date;
}

export function defaultCodexConfigPath(homeDir?: string): string {
  return path.join(homeDir ?? os.homedir(), ".codex", "config.toml");
}

function lineStartAt(text: string, index: number): number {
  const prev = text.lastIndexOf("\n", Math.max(0, index - 1));
  return prev === -1 ? 0 : prev + 1;
}

function lineEndAfter(text: string, index: number): number {
  const next = text.indexOf("\n", index);
  return next === -1 ? text.length : next + 1;
}

function previousLine(
  text: string,
  lineStart: number,
): { start: number; text: string } | null {
  if (lineStart === 0) return null;
  const end = lineStart - 1;
  const start = lineStartAt(text, end);
  return { start, text: text.slice(start, end) };
}

function findLegacyRangeEnd(text: string, start: number): number {
  let pos = start;
  while (pos < text.length) {
    const end = lineEndAfter(text, pos);
    const line = text.slice(pos, end).trim();
    if (pos > start && NON_HOOK_TABLE_RE.test(line)) return pos;
    pos = end;
  }
  return text.length;
}

function findManagedRange(text: string): { start: number; end: number } | null {
  const begin = text.indexOf(CODEX_MANAGED_BEGIN);
  if (begin !== -1) {
    let start = lineStartAt(text, begin);
    const prev = previousLine(text, start);
    if (prev && prev.text.startsWith(CODEX_MANAGED_SOURCE_PREFIX)) {
      start = prev.start;
    }
    const endMarker = text.indexOf(CODEX_MANAGED_END, begin);
    if (endMarker !== -1) {
      return { start, end: lineEndAfter(text, endMarker) };
    }
    return { start, end: findLegacyRangeEnd(text, start) };
  }

  const source = text.indexOf(CODEX_MANAGED_SOURCE_PREFIX);
  if (source !== -1) {
    const start = lineStartAt(text, source);
    return { start, end: findLegacyRangeEnd(text, start) };
  }

  const generated = text.indexOf(GENERATED_HEADER);
  if (generated !== -1) {
    const start = lineStartAt(text, generated);
    const end = findLegacyRangeEnd(text, start);
    const candidate = text.slice(start, end);
    if (
      candidate.includes("[[hooks.") ||
      candidate.includes("[[hooks.pre_tool_use]]")
    ) {
      return { start, end };
    }
  }

  return null;
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith("\n") ? s : `${s}\n`;
}

function buildManagedBlock(
  generatedContent: string,
  generatedPath: string,
): string {
  return [
    `${CODEX_MANAGED_SOURCE_PREFIX} Generated source: ${generatedPath}`,
    CODEX_MANAGED_BEGIN,
    ensureTrailingNewline(generatedContent).trimEnd(),
    CODEX_MANAGED_END,
    "",
  ].join("\n");
}

export function validateCodexManagedConfig(content: string): void {
  const lines = content.split(/\r?\n/);
  const legacyLine = lines.find((line) => {
    const trimmed = line.trim();
    return (
      LEGACY_HOOK_TABLE_RE.test(trimmed) ||
      trimmed.startsWith("timeout_ms =") ||
      trimmed.startsWith("blocking =") ||
      trimmed.startsWith("match =")
    );
  });
  if (legacyLine !== undefined) {
    throw new Error(
      `generated Codex config still uses legacy hook schema: ${legacyLine.trim()}`,
    );
  }

  const hookTableIndexes: number[] = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (CURRENT_HOOK_TABLE_RE.test(lines[i]!.trim())) hookTableIndexes.push(i);
  }
  if (hookTableIndexes.length === 0) return;

  for (let i = 0; i < hookTableIndexes.length; i += 1) {
    const start = hookTableIndexes[i]!;
    const end = hookTableIndexes[i + 1] ?? lines.length;
    const segment = lines.slice(start, end).join("\n");
    if (!segment.includes("hooks = [")) {
      throw new Error(
        `generated Codex hook table is missing hooks array: ${lines[start]!.trim()}`,
      );
    }
    if (
      !segment.includes('type = "command"') ||
      !/command = "([^"\\]|\\.)+"/.test(segment) ||
      !/timeout = [1-9][0-9]*/.test(segment)
    ) {
      throw new Error(
        `generated Codex hook table has invalid command hook shape: ${lines[start]!.trim()}`,
      );
    }
  }
}

export function planCodexConfigInstall(
  opts: CodexConfigInstallOptions,
): CodexConfigInstallPlan {
  validateCodexManagedConfig(opts.generatedContent);

  const configPath = opts.configPath ?? defaultCodexConfigPath(opts.homeDir);
  let currentContent = "";
  try {
    currentContent = fs.readFileSync(configPath, "utf8");
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code !== "ENOENT") throw err;
  }

  const managedBlock = buildManagedBlock(
    opts.generatedContent,
    opts.generatedPath,
  );
  const range = findManagedRange(currentContent);
  let nextContent: string;
  let summary: string;
  if (range) {
    nextContent = `${currentContent.slice(0, range.start)}${managedBlock}${currentContent.slice(range.end)}`;
    summary = `updated harness-managed Codex hook block in ${configPath}`;
  } else {
    const prefix =
      currentContent.length === 0
        ? ""
        : currentContent.endsWith("\n\n")
          ? ""
          : currentContent.endsWith("\n")
            ? "\n"
            : "\n\n";
    nextContent = `${currentContent}${prefix}${managedBlock}`;
    summary = `installed harness-managed Codex hook block into ${configPath}`;
  }

  return {
    configPath,
    generatedPath: opts.generatedPath,
    currentContent,
    nextContent,
    changed: currentContent !== nextContent,
    summary:
      currentContent === nextContent
        ? `Codex config already up to date: ${configPath}`
        : summary,
  };
}

function timestampForBackup(now: Date): string {
  return now.toISOString().replace(/[:.]/g, "-");
}

export function writeCodexConfigInstall(
  plan: CodexConfigInstallPlan,
  opts: { now?: Date } = {},
): CodexConfigInstallResult {
  if (!plan.changed) return { ...plan, written: false };
  const backupPath = `${plan.configPath}.harness-backup-${timestampForBackup(opts.now ?? new Date())}`;
  fs.mkdirSync(path.dirname(plan.configPath), { recursive: true });
  atomicWriteFile(backupPath, plan.currentContent);
  atomicWriteFile(plan.configPath, plan.nextContent);
  return { ...plan, backupPath, written: true };
}
