// Phase 4 #5 — `harness policy intercept` CLI entrypoint.
//
// Wired by Claude Code's settings.json (regenerated by `harness apply`) as
// the PreToolUse hook. Reads the event JSON from stdin, runs the runtime
// interceptor, writes Claude Code's deny JSON to stdout on block.

import {
  queryLedgerByTag,
  type LedgerEntry,
  type LedgerQueryResult,
} from "../../policies/index.js";
import {
  intercept,
  recordPolicyDecision,
  type LedgerClient,
  type PolicyDecision,
  type ToolEvent,
} from "../../runtime/index.js";
import type { Manifest, McpServer } from "../../schema/index.js";
import { loadManifest, type LoaderOptions } from "../loader.js";

export interface InterceptCliOptions extends LoaderOptions {
  /** Defaults to process.stdin. */
  stdin?: NodeJS.ReadableStream;
  /** Defaults to process.stdout. */
  stdout?: NodeJS.WritableStream;
  /** Defaults to process.stderr. */
  stderr?: NodeJS.WritableStream;
  /** Override timeout per ledger call. */
  ledgerTimeoutMs?: number;
  /** Override "now" for deterministic tests. */
  now?: Date;
  /** Inject a fake ledger client (tests). */
  ledger?: LedgerClient;
  /** Inject the resolved manifest (tests). */
  manifest?: Manifest;
  /**
   * When true (or `HARNESS_POLICY_VERBOSE` env is truthy), emit a
   * human-readable diagnostic block to stderr for each non-allow
   * decision. stdout is unaffected, so Claude Code's deny JSON contract
   * is preserved. Phase 5 #3 — opt-in only.
   */
  verbose?: boolean;
}

export interface InterceptCliResult {
  exitCode: number;
  decisions: PolicyDecision[];
  blocked: boolean;
}

async function readStdin(stream: NodeJS.ReadableStream): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = "";
    stream.setEncoding("utf8");
    stream.on("data", (chunk: string) => {
      data += chunk;
    });
    stream.on("end", () => resolve(data));
    stream.on("error", (err) => reject(err));
  });
}

function findGroundingMcp(manifest: Manifest): McpServer | null {
  return manifest.tools.mcp.find((m) => m.name === "grounding-mcp") ?? null;
}

/**
 * Phase 5 #3 — render a deny / warn-degraded decision as a stderr
 * diagnostic block. Multiline, indented; each block is bounded by the
 * policy name so concurrent fires (rare but possible) stay readable.
 */
function formatDecisionDiagnostic(decision: PolicyDecision): string {
  const header = `harness policy intercept: ${decision.policyName} — ${decision.outcome}${
    decision.outcome === "warn-degraded" ? " (ledger unreachable)" : ""
  }`;
  const lines: string[] = [header];
  lines.push(`  ledger_tag: ${decision.ledgerTag}`);
  if (decision.requiresEval !== undefined) {
    lines.push(`  matched: ${decision.requiresEval.matchedCount}`);
  }
  lines.push(`  reason: ${decision.reason}`);
  const extractKeys = Object.keys(decision.extractValues);
  if (extractKeys.length > 0) {
    lines.push("  extract:");
    for (const k of extractKeys.sort()) {
      lines.push(`    ${k}=${decision.extractValues[k]}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

function isVerboseEnabled(opts: InterceptCliOptions): boolean {
  if (opts.verbose === true) return true;
  if (opts.verbose === false) return false;
  const env = process.env.HARNESS_POLICY_VERBOSE;
  if (typeof env !== "string") return false;
  if (env.length === 0) return false;
  // Accept anything truthy except literal "0"/"false" (case-insensitive).
  return !/^(0|false)$/i.test(env.trim());
}

function realLedgerClient(server: McpServer, opts: InterceptCliOptions): LedgerClient {
  const command = Array.isArray(server.command)
    ? server.command
    : server.command.trim().split(/\s+/);
  const env = server.env ?? undefined;
  const timeoutMs = opts.ledgerTimeoutMs ?? server.health?.timeout_ms ?? 5_000;
  return {
    async query(_tag, sessionId): Promise<LedgerQueryResult> {
      return queryLedgerByTag({
        mcpCommand: command,
        ...(env && { mcpEnv: env }),
        sessionId,
        timeoutMs,
      });
    },
    async record(decision, sessionId): Promise<void> {
      await recordPolicyDecision(decision, sessionId, {
        mcpCommand: command,
        ...(env && { mcpEnv: env }),
        timeoutMs,
      });
    },
  };
}

function degradedLedgerClient(reason: string): LedgerClient {
  return {
    async query(): Promise<LedgerQueryResult> {
      return { kind: "degraded", reason };
    },
    async record(): Promise<void> {
      /* no-op when ledger is unavailable */
    },
  };
}

export async function runInterceptCli(
  opts: InterceptCliOptions = {},
): Promise<InterceptCliResult> {
  const stdin = opts.stdin ?? process.stdin;
  const stdout = opts.stdout ?? process.stdout;
  const stderr = opts.stderr ?? process.stderr;
  const verbose = isVerboseEnabled(opts);
  const raw = await readStdin(stdin);
  let event: ToolEvent;
  try {
    event = JSON.parse(raw.trim() || "{}") as ToolEvent;
  } catch (err) {
    process.stderr.write(
      `harness policy intercept: malformed event JSON: ${(err as Error).message}\n`,
    );
    return { exitCode: 0, decisions: [], blocked: false };
  }

  let manifest: Manifest;
  try {
    manifest = opts.manifest ?? loadManifest(opts).manifest;
  } catch (err) {
    process.stderr.write(
      `harness policy intercept: manifest load failed: ${(err as Error).message}\n`,
    );
    return { exitCode: 0, decisions: [], blocked: false };
  }

  let ledger: LedgerClient;
  if (opts.ledger) {
    ledger = opts.ledger;
  } else {
    const server = findGroundingMcp(manifest);
    ledger = server
      ? realLedgerClient(server, opts)
      : degradedLedgerClient("grounding-mcp not declared in manifest");
  }

  // For the SESSION_ID builtin we keep the empty-string fallback rather
  // than routing through resolveSessionId (which lands on "default").
  // Routing through "default" would silently bake the literal string
  // into ledger_tag templates like `dogfood:${SESSION_ID}` →
  // `dogfood:default`, which would substring-match anything in the
  // shared "default" session — a worse failure mode than the current
  // empty substitution. The empty path produces tags like `dogfood:`
  // (substituteTemplate treats the registered "" value as a successful
  // substitution since the key is hasOwnProperty-present, so this is
  // NOT marked warn-degraded by the requires evaluator); the ledger
  // query for that fire also lands on the resolveSessionId-derived
  // session, so the asymmetry is acceptable in practice. Do NOT
  // "simplify" by routing this through resolveSessionId.
  // The env fallback is still applied so a Claude-Code-driven hook with
  // a stripped event can pick up the active session.
  const eventSessionId = typeof event.session_id === "string" ? event.session_id : undefined;
  const builtinSessionId = eventSessionId ?? process.env.CLAUDE_SESSION_ID ?? "";
  const builtins = {
    SESSION_ID: builtinSessionId,
    REPO: process.env.HARNESS_REPO ?? "",
    BRANCH: process.env.HARNESS_BRANCH ?? "",
    TOOL_NAME: typeof event.tool_name === "string" ? event.tool_name : "",
    CWD: typeof event.cwd === "string" ? event.cwd : process.cwd(),
  };

  const result = await intercept({
    manifest,
    event,
    ledger,
    builtins,
    ...(opts.ledgerTimeoutMs !== undefined && { ledgerTimeoutMs: opts.ledgerTimeoutMs }),
    ...(opts.now && { now: opts.now }),
  });

  if (result.blockJson) {
    stdout.write(`${JSON.stringify(result.blockJson)}\n`);
  }

  if (verbose) {
    for (const decision of result.decisions) {
      if (decision.outcome === "allow") continue;
      stderr.write(formatDecisionDiagnostic(decision));
    }
  }

  return {
    exitCode: 0,
    decisions: result.decisions,
    blocked: result.blockJson !== null,
  };
}

export type { LedgerEntry };
