import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { parse as parseTomlForTest } from "smol-toml";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  CODEX_MANAGED_BEGIN,
  CODEX_MANAGED_END,
  CodexInstallRefusalError,
  planCodexConfigInstall,
} from "../../../src/cli/apply/index.js";

// The legacy edges of the codex install that the refusal and boundary tests
// of the neighbouring files leave open (task c78a155b): a genuine legacy block
// after a stale generated-header line, an operator key between a legacy
// block's opening line and its first hook table, a harness-commented hook
// table with no block marker around it on the append path, and the END-or-move
// guidance of the no-END refusal for a table that already sits where the move
// would put it.

const GENERATED = "# Generated by harness apply --runtime codex.";
const SOURCE_PREFIX = "# Harness Codex hook wiring. Generated source: old";
const TOKEN = "sk-live-FAKE-c78a155b-0123456789";
const OPERATOR_COMMAND = `operator-cmd --token=${TOKEN}`;

const harnessTable = (id: string, event: string, command: string): string[] => [
  `# harness hook: ${id} (budget_ms=2000)`,
  `[[hooks.${event}]]`,
  'matcher = "Bash"',
  `hooks = [{ type = "command", command = "${command}", timeout = 2 }]`,
];

const HARNESS_A = harnessTable("a", "PreToolUse", "harness pack hook a");
const HARNESS_B = harnessTable("b", "Stop", "harness pack hook b");
const FRESH = [GENERATED, ...HARNESS_A, ...HARNESS_B, ""].join("\n");
const OPERATOR_STOP = ["[[hooks.Stop]]", `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }]`];
/** A legacy table without the comment line, as an older generator wrote it. */
const OLD_TABLE = [
  "[[hooks.PreToolUse]]",
  'matcher = "Bash"',
  'hooks = [{ type = "command", command = "harness pack hook old", timeout = 2 }]',
];
const LEGACY_HEADS: Array<[string, string[]]> = [
  ["source prefix", [SOURCE_PREFIX, GENERATED]],
  ["generated header", [GENERATED]],
];

let home: string;
let codexConfig: string;

beforeEach(() => {
  home = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "harness-codex-residuals-"));
  codexConfig = path.join(home, ".codex", "config.toml");
  fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
});

afterEach(() => {
  fs.rmSync(home, { recursive: true, force: true });
});

function write(lines: string[]): string {
  const body = lines.join("\n");
  fs.writeFileSync(codexConfig, body);
  return body;
}

function plan() {
  return planCodexConfigInstall({ configPath: codexConfig, generatedPath: "/x/config.toml", generatedContent: FRESH });
}

function refusal(): CodexInstallRefusalError {
  try {
    plan();
  } catch (err) {
    expect(err).toBeInstanceOf(CodexInstallRefusalError);
    return err as CodexInstallRefusalError;
  }
  throw new Error("expected the plan to refuse");
}

/** Plans, writes the result, plans again: the second plan must change nothing. */
function planTwice() {
  const first = plan();
  fs.writeFileSync(codexConfig, first.nextContent);
  const second = plan();
  expect(second.changed).toBe(false);
  expect(second.nextContent).toBe(first.nextContent);
  return first;
}

function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

function endLines(text: string): number {
  return text.split(/\r?\n/).filter((l) => l.trim() === CODEX_MANAGED_END).length;
}

/** 1-based number of the first line of `text` whose trimmed text is `line`. */
function lineOf(text: string, line: string): number {
  return text.split("\n").findIndex((l) => l.trim() === line) + 1;
}

/** Every hook command of the parsed config, by event. */
function hookCommands(text: string): string[] {
  const doc = parseTomlForTest(text) as {
    hooks?: Record<string, Array<{ command?: string; hooks?: Array<{ command?: string }> }>>;
  };
  return Object.entries(doc.hooks ?? {}).flatMap(([event, entries]) =>
    entries.flatMap((entry) => [
      ...(entry.command !== undefined ? [`${event}:${entry.command}`] : []),
      ...(entry.hooks ?? []).flatMap((h) => (h.command !== undefined ? [`${event}:${h.command}`] : [])),
    ]),
  );
}

describe("codex install: an operator key between a legacy block's opening line and its first hook table refuses (task c78a155b)", () => {
  for (const [label, head] of LEGACY_HEADS) {
    it(`${label}: a key of the operator hook table above the opening line refuses, naming line numbers only, and moving the key above the line installs`, () => {
      const config = write([...OPERATOR_STOP, ...head.slice(0, 1), `note = "${TOKEN}"`, ...head.slice(1), ...OLD_TABLE, ""]);
      const { message } = refusal();
      expect(message).toContain(`has a key or value line (line ${lineOf(config, `note = "${TOKEN}"`)}) between`);
      expect(message).toContain(`(line ${lineOf(config, head[0]!)}) and the first hook table below it (line ${lineOf(config, "[[hooks.PreToolUse]]")})`);
      expect(message).toContain("Move that line (with any value lines it continues) above the opening line");
      expect(message).not.toContain(TOKEN);
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);

      // Follow the guidance literally: the key goes above the opening line.
      write([...OPERATOR_STOP.slice(0, 1), `note = "${TOKEN}"`, ...OPERATOR_STOP.slice(1), ...head, ...OLD_TABLE, ""]);
      const p = planTwice();
      expect(count(p.nextContent, `note = "${TOKEN}"`)).toBe(1);
      expect(hookCommands(p.nextContent).sort()).toEqual(
        ["PreToolUse:harness pack hook a", "Stop:harness pack hook b", `Stop:${OPERATOR_COMMAND}`].sort(),
      );
      expect(count(p.nextContent, "harness pack hook old")).toBe(0);
      expect(endLines(p.nextContent)).toBe(1);
    });

    it(`${label}: a value line in a multi-line string between the opening line and the first hook table refuses too`, () => {
      const config = write([...head, 'note = """', `keep ${TOKEN}`, '"""', ...OLD_TABLE, ""]);
      const { message } = refusal();
      expect(message).toContain(`has a key or value line (line ${lineOf(config, 'note = """')}) between`);
      expect(message).not.toContain(TOKEN);
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);
    });

    it(`${label}: a legacy block that ends at an END marker refuses on the key between the opening line and the first hook table too`, () => {
      const config = write([
        ...OPERATOR_STOP,
        ...head.slice(0, 1),
        `note = "${TOKEN}"`,
        ...head.slice(1),
        ...OLD_TABLE,
        CODEX_MANAGED_END,
        "",
      ]);
      const { message } = refusal();
      expect(message).toContain(`has a key or value line (line ${lineOf(config, `note = "${TOKEN}"`)}) between`);
      expect(message).not.toContain(TOKEN);
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);
    });

    it(`${label}: only blank and comment lines between the opening line and the first hook table still install`, () => {
      write([...head, "", "# a note an operator left", ...OLD_TABLE, ""]);
      const p = planTwice();
      expect(count(p.nextContent, "harness pack hook old")).toBe(0);
      expect(hookCommands(p.nextContent).sort()).toEqual(
        ["PreToolUse:harness pack hook a", "Stop:harness pack hook b"].sort(),
      );
    });
  }

  it("a generated header pasted inside a foreign table refuses on the key under it", () => {
    const config = write(["[tui]", GENERATED, "a = 1", ...OLD_TABLE, ""]);
    const { message } = refusal();
    expect(message).toContain(`has a key or value line (line ${lineOf(config, "a = 1")}) between`);
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);
  });

  it("a top-level key right after a legacy source-prefix line refuses", () => {
    const config = write([SOURCE_PREFIX, 'model = "gpt-5.5"', ...OLD_TABLE, ""]);
    const { message } = refusal();
    expect(message).toContain(`has a key or value line (line ${lineOf(config, 'model = "gpt-5.5"')}) between`);
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);
  });

  it("a key after the first hook table of the block is not the refusal's case (it is read as the table's own field)", () => {
    write([GENERATED, ...OLD_TABLE, 'note = "inside the harness table"', ""]);
    const p = plan();
    expect(p.changed).toBe(true);
  });
});

describe("codex install: a genuine legacy block after a stale generated-header line refuses (task c78a155b)", () => {
  const STALE_THEN_BLOCK = [...OPERATOR_STOP, GENERATED, "[tui]", "t = 1", "", GENERATED, ...OLD_TABLE, ""];

  it("names both lines and refuses, and deleting the stale line installs and replaces the genuine block", () => {
    const config = write(STALE_THEN_BLOCK);
    const { message } = refusal();
    expect(message).toContain("has two '# Generated by harness apply --runtime codex.' lines");
    expect(message).toContain(`the one at line ${lineOf(config, GENERATED)} has no hook table of its own`);
    const lines = config.split("\n");
    const second = lines.lastIndexOf(GENERATED) + 1;
    expect(message).toContain(`the one at line ${second} sits above the hook table at line ${second + 1}`);
    expect(message).not.toContain(TOKEN);
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);

    // Follow the guidance: delete the stale line.
    const stale = lineOf(config, GENERATED) - 1;
    write(lines.filter((_, i) => i !== stale));
    const p = planTwice();
    expect(count(p.nextContent, "harness pack hook old")).toBe(0);
    expect(hookCommands(p.nextContent).sort()).toEqual(
      ["PreToolUse:harness pack hook a", "Stop:harness pack hook b", `Stop:${OPERATOR_COMMAND}`].sort(),
    );
    expect(p.nextContent).toContain("[tui]\nt = 1");
  });

  it("a stale generated-header line with a harness-commented later block refuses the same way", () => {
    write([GENERATED, "[tui]", "t = 1", "", GENERATED, ...HARNESS_A, ""]);
    expect(refusal().message).toContain("has two '# Generated by harness apply --runtime codex.' lines");
  });

  it("a later generated-header line that is not directly above a hook table is not the refusal's case", () => {
    // Documented boundary: only a generated-header line directly above a hook
    // table is read as a later block; a key line in between hides it.
    write([GENERATED, "[tui]", "t = 1", "", GENERATED, 'note = "x"', ...OLD_TABLE, ""]);
    const p = plan();
    expect(p.summary).toContain("installed harness-managed Codex hook block");
  });

  it("generated-header text in a string past the stale line is not a later block", () => {
    write([GENERATED, "[tui]", "t = 1", "note = '''", GENERATED, "[[hooks.Stop]]", "'''", ""]);
    const p = planTwice();
    expect(p.summary).toContain("installed harness-managed Codex hook block");
  });

  it("an operator hook table past the stale line, with no generated header above it, appends the block", () => {
    write([GENERATED, "[tui]", "t = 1", "", ...OPERATOR_STOP, ""]);
    const p = planTwice();
    expect(hookCommands(p.nextContent).sort()).toEqual(
      ["PreToolUse:harness pack hook a", "Stop:harness pack hook b", `Stop:${OPERATOR_COMMAND}`].sort(),
    );
  });
});

describe("codex install: a harness-commented hook table with no block marker around it refuses on the append path (task c78a155b)", () => {
  const ORPHAN = harnessTable("old", "Stop", "harness pack hook old");

  it("names the comment line and the table, never a value, and deleting the table with its comment installs", () => {
    const config = write([...OPERATOR_STOP, "", ...ORPHAN, ""]);
    const { message } = refusal();
    const marker = lineOf(config, "# harness hook: old (budget_ms=2000)");
    expect(message).toContain(`comment line (line ${marker}) directly above the hook table [[hooks.Stop]] (line ${marker + 1})`);
    expect(message).toContain("delete it together with its comment line");
    expect(message).not.toContain(TOKEN);
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);

    write([...OPERATOR_STOP, ""]);
    const p = planTwice();
    expect(hookCommands(p.nextContent).sort()).toEqual(
      ["PreToolUse:harness pack hook a", "Stop:harness pack hook b", `Stop:${OPERATOR_COMMAND}`].sort(),
    );
  });

  it("an operator's own table under such a comment installs once the comment is reworded", () => {
    write([...OPERATOR_STOP, "", "# harness hook: mine (budget_ms=2000)", ...OPERATOR_STOP, ""]);
    expect(refusal().message).toContain("delete or reword the comment line");
    write([...OPERATOR_STOP, "", "# my own hook", ...OPERATOR_STOP, ""]);
    expect(planTwice().changed).toBe(true);
  });

  it("a multi-line string line that closes with marker text before an orphan table does not hide it", () => {
    const config = write([...OPERATOR_STOP, 'note = """', `keep ${TOKEN}`, `${SOURCE_PREFIX}"""`, "", ...ORPHAN, ""]);
    const { message } = refusal();
    expect(message).toContain(`comment line (line ${lineOf(config, "# harness hook: old (budget_ms=2000)")})`);
    expect(message).not.toContain(TOKEN);
  });

  it("the comment above a hook table spelled another way refuses too", () => {
    const config = write([
      ...OPERATOR_STOP,
      "# harness hook: old (budget_ms=2000)",
      "[[ hooks.Stop ]]",
      'hooks = [{ type = "command", command = "harness pack hook old", timeout = 2 }]',
      "",
    ]);
    const { message } = refusal();
    expect(message).toContain(`directly above the hook table [[ hooks.Stop ]] (line ${lineOf(config, "[[ hooks.Stop ]]")})`);
  });

  it("the comment run may hold other comment and blank lines between the marker and the table", () => {
    write([...OPERATOR_STOP, "# harness hook: old (budget_ms=2000)", "", "# more", "[[hooks.Stop]]", 'hooks = []', ""]);
    expect(refusal().message).toContain("directly above the hook table [[hooks.Stop]]");
  });

  it("a config the parser cannot read before the comment refuses through the parse check, not as an orphan table", () => {
    // The comment line counts only at the top level of a readable prefix, as
    // every marker line does.
    write([...OPERATOR_STOP, "broken = ", "", ...ORPHAN, ""]);
    const { message } = refusal();
    expect(message).toContain("the TOML parser used by harness could not read this file");
    expect(message).not.toContain("directly above the hook table");
  });

  const stays: Array<[string, string[]]> = [
    [
      "marker text in a multi-line string line above a hook table",
      [...OPERATOR_STOP, 'note = """', "# harness hook: x (budget_ms=1)", '"""', ...OPERATOR_STOP, ""],
    ],
    [
      "marker text as a trailing comment of a content line above a hook table",
      [...OPERATOR_STOP, 'x = 1 # harness hook: x (budget_ms=1)', ...OPERATOR_STOP, ""],
    ],
    [
      "a marker comment above a table that is not a hook table",
      ["# harness hook: x (budget_ms=1)", "[tui]", "t = 1", "", ...OPERATOR_STOP, ""],
    ],
    [
      "a marker comment with a key line between it and the next hook table",
      [...OPERATOR_STOP, "# harness hook: x (budget_ms=1)", 'note = "x"', ...OPERATOR_STOP, ""],
    ],
    [
      "a marker comment at the end of the file",
      [...OPERATOR_STOP, "# harness hook: x (budget_ms=1)", ""],
    ],
  ];
  for (const [label, lines] of stays) {
    it(`${label} is operator content: the block is appended`, () => {
      const config = write(lines);
      const p = planTwice();
      expect(p.nextContent.startsWith(config)).toBe(true);
      expect(p.summary).toContain("installed harness-managed Codex hook block");
    });
  }

  for (const [label, head] of [["BEGIN", [CODEX_MANAGED_BEGIN, GENERATED]], ...LEGACY_HEADS] as Array<[string, string[]]>) {
    it(`${label}: a marked table inside a block that a marker opens is replaced, not refused`, () => {
      write([...OPERATOR_STOP, ...head, ...harnessTable("old", "Stop", "harness pack hook old"), ...(label === "BEGIN" ? [CODEX_MANAGED_END] : []), ""]);
      const p = planTwice();
      expect(count(p.nextContent, "harness pack hook old")).toBe(0);
    });
  }
});

describe("codex install: the no-END refusal for a table that already sits below the last harness table offers only the END fix (task c78a155b)", () => {
  const RESPELLED_HARNESS_TABLE = [
    "# harness hook: bb (budget_ms=2000)",
    "[[ hooks.SessionStart ]]",
    'hooks = [{ type = "command", command = "harness pack hook bb", timeout = 2 }]',
  ];

  for (const [label, head] of [["BEGIN", [CODEX_MANAGED_BEGIN, GENERATED]], ...LEGACY_HEADS] as Array<[string, string[]]>) {
    it(`${label}: the refusal for the respelled harness table that is last offers the END fix, not a move, and following it installs`, () => {
      // The chain of the first refusal's "move the table below the last
      // harness hook table": after that move the respelled harness table is
      // the last one and the second refusal names it.
      const config = write([
        ...head,
        ...HARNESS_A,
        ...RESPELLED_HARNESS_TABLE,
        "[[ hooks.Stop ]]",
        `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }]`,
        "",
      ]);
      const { message } = refusal();
      expect(message).toContain("has a foreign table ([[ hooks.SessionStart ]])");
      expect(message).toContain(`add a '${CODEX_MANAGED_END}' marker line right after the last harness hook table (before [[ hooks.SessionStart ]]), then re-run`);
      expect(message).not.toContain("below the last harness hook table");
      expect(message).not.toContain(TOKEN);
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);

      // Follow the END fix: put the marker right after the last harness table.
      const lines = config.split("\n");
      const at = lines.indexOf("# harness hook: bb (budget_ms=2000)");
      write([...lines.slice(0, at), CODEX_MANAGED_END, ...lines.slice(at)]);
      const p = planTwice();
      expect(endLines(p.nextContent)).toBe(1);
      expect(hookCommands(p.nextContent)).toContain("Stop:harness pack hook b");
    });
  }

  it("a table that has a harness-commented table after it still gets the move as the only fix", () => {
    write([
      CODEX_MANAGED_BEGIN,
      GENERATED,
      ...HARNESS_A,
      "[[ hooks.Stop ]]",
      `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }]`,
      ...RESPELLED_HARNESS_TABLE,
      "",
    ]);
    const { message } = refusal();
    expect(message).toContain("move [[ hooks.Stop ]] below the last harness hook table");
    expect(message).not.toContain(`add a '${CODEX_MANAGED_END}'`);
  });
});
