import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { parse as parseTomlForTest } from "smol-toml";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as yamlStringify } from "yaml";
import {
  CODEX_MANAGED_BEGIN,
  CODEX_MANAGED_END,
  CodexInstallRefusalError,
  planCodexConfigInstall,
} from "../../../src/cli/apply/index.js";
import { EX_OK } from "../../../src/cli/exit-codes.js";
import { run } from "../../../src/cli/index.js";

// Boundary checks of the codex install's hook-table scan and the shapes that
// kept a harness hook unnamed or duplicated, or left a second END marker
// (task e8f4fc03): a nested `hooks` sub-key and a `hooks` root compared
// exactly, an END marker line compared as a whole line, hook event tables
// spelled without the `[[hooks.` prefix directly after the harness tables,
// and a legacy config (no BEGIN marker) with a foreign table between its
// harness tables and a surviving END marker.

const GENERATED = "# Generated by harness apply --runtime codex.";
const SOURCE_PREFIX = "# Harness Codex hook wiring. Generated source: old";
const TOKEN = "sk-live-FAKE-e8f4fc03-0123456789";
const OPERATOR_COMMAND = `operator-cmd --token=${TOKEN}`;

const harnessTable = (id: string, event: string, command: string): string[] => [
  `# harness hook: ${id} (budget_ms=2000)`,
  `[[hooks.${event}]]`,
  'matcher = "Bash"',
  `hooks = [{ type = "command", command = "${command}", timeout = 2 }]`,
];

const HARNESS_A = harnessTable("a", "PreToolUse", "harness pack hook a");
const HARNESS_B = harnessTable("b", "Stop", "harness pack hook b");
const FRESH = [GENERATED, ...HARNESS_A, ...HARNESS_B, ""].join("\n");
const DOCS_TABLE = ["[mcp_servers.docs]", `command = "docs-server --token=${TOKEN}"`];
const TAIL = ['[projects."/work/x"]', 'trust_level = "trusted"'];

let home: string;
let codexConfig: string;
let manifestPath: string;

beforeEach(() => {
  home = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "harness-codex-boundaries-"));
  codexConfig = path.join(home, ".codex", "config.toml");
  fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
  manifestPath = path.join(home, "harness.yaml");
  fs.writeFileSync(
    manifestPath,
    yamlStringify({
      version: 1,
      tools: { mcp: [], cli: [], skills: { enabled: [], source_dirs: [] }, builtin: { known: [] } },
      memory: { directories: [] },
      hooks: [],
      policies: [],
      policy_packs: [{ name: "understanding-before-execution" }],
    }),
  );
});

afterEach(() => {
  fs.rmSync(home, { recursive: true, force: true });
});

function write(lines: string[]): string {
  const body = lines.join("\n");
  fs.writeFileSync(codexConfig, body);
  return body;
}

function plan(generatedContent = FRESH) {
  return planCodexConfigInstall({ configPath: codexConfig, generatedPath: "/x/config.toml", generatedContent });
}

/** The refusal the plan throws for the config on disk, or fails the test. */
function refusal(): CodexInstallRefusalError {
  try {
    plan();
  } catch (err) {
    expect(err).toBeInstanceOf(CodexInstallRefusalError);
    return err as CodexInstallRefusalError;
  }
  throw new Error("expected the plan to refuse");
}

/** Plans over the config on disk, writes the result, plans again: the second
 * plan must change nothing. Returns the first plan. */
function planTwice() {
  const first = plan();
  fs.writeFileSync(codexConfig, first.nextContent);
  const second = plan();
  expect(second.changed).toBe(false);
  expect(second.nextContent).toBe(first.nextContent);
  return first;
}

function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

function endLines(text: string): number {
  return text.split(/\r?\n/).filter((l) => l.trim() === CODEX_MANAGED_END).length;
}

/** 1-based number of the first line of `text` whose trimmed text is `line`. */
function lineOf(text: string, line: string): number {
  return text.split("\n").findIndex((l) => l.trim() === line) + 1;
}

/** 1-based number of the last such line (a kept table sits after the fresh block). */
function lastLineOf(text: string, line: string): number {
  return text.split("\n").map((l) => l.trim()).lastIndexOf(line) + 1;
}

function keptLabel(header: string, before: string, after: string): string {
  return `${header} (line ${lineOf(before, header)} before the install, line ${lastLineOf(after, header)} after it)`;
}

/** Every hook command of the parsed config's `hooks.Stop` array. */
function stopCommands(text: string): string[] {
  const doc = parseTomlForTest(text) as {
    hooks?: { Stop?: Array<{ command?: string; hooks?: Array<{ command?: string }> }> };
  };
  return (doc.hooks?.Stop ?? []).flatMap((entry) => [
    ...(entry.command !== undefined ? [entry.command] : []),
    ...(entry.hooks ?? []).flatMap((h) => (h.command !== undefined ? [h.command] : [])),
  ]);
}

interface CliRun {
  code: number;
  out: string;
  err: string;
}

async function cli(opts: { json?: boolean; dryRun?: boolean }): Promise<CliRun> {
  let out = "";
  let err = "";
  const code = await run({
    argv: [
      "apply",
      "--config",
      manifestPath,
      "--runtime",
      "codex",
      "--install",
      "--codex-config",
      codexConfig,
      ...(opts.dryRun ? ["--dry-run"] : []),
      ...(opts.json ? ["--json"] : []),
    ],
    stdout: (s: string) => {
      out += s;
    },
    stderr: (s: string) => {
      err += s;
    },
  });
  return { code, out, err };
}

/** The CLI over the config on disk in every mode (--dry-run, --dry-run
 * --json, the install and its --json form), the config written back before
 * each run. */
async function everyMode(): Promise<CliRun[]> {
  const original = fs.readFileSync(codexConfig, "utf8");
  const runs: CliRun[] = [];
  for (const opts of [{ dryRun: true }, { dryRun: true, json: true }, {}, { json: true }]) {
    fs.writeFileSync(codexConfig, original);
    runs.push(await cli(opts));
  }
  fs.writeFileSync(codexConfig, original);
  return runs;
}

describe("codex install: boundary checks of the hook header map and the END line are exact (task e8f4fc03)", () => {
  it("a sub-table [[hooks.Stop.HOOKS]] of a kept entry with two inline hooks is not the nested hooks array: both tables are kept and named", () => {
    const config = write([
      CODEX_MANAGED_BEGIN,
      GENERATED,
      ...HARNESS_A,
      "[[hooks.Stop]]",
      `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }, { type = "command", command = "operator-second", timeout = 5 }]`,
      "[[hooks.Stop.HOOKS]]",
      "x = 1",
      CODEX_MANAGED_END,
      "",
    ]);
    const p = planTwice();
    expect(p.keptOperatorHookTables).toEqual([
      keptLabel("[[hooks.Stop]]", config, p.nextContent),
      keptLabel("[[hooks.Stop.HOOKS]]", config, p.nextContent),
    ]);
    expect(stopCommands(p.nextContent)).toEqual(["harness pack hook b", OPERATOR_COMMAND, "operator-second"]);
  });

  it('a table whose quoted root key only equals `hooks` after trimming ([[ " hooks" . Stop ]]) is outside `hooks`: the kept table is matched to its own entry', () => {
    const other = ['[[ " hooks" . Stop ]]', 'hooks = [{ type = "command", command = "archived-hook", timeout = 5 }]'];
    const config = write([
      ...other,
      CODEX_MANAGED_BEGIN,
      GENERATED,
      ...HARNESS_A,
      "[[hooks.Stop]]",
      `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }]`,
      CODEX_MANAGED_END,
      "",
    ]);
    const p = planTwice();
    expect(p.keptOperatorHookTables).toEqual([keptLabel("[[hooks.Stop]]", config, p.nextContent)]);
    expect(p.nextContent.startsWith(`${other.join("\n")}\n`)).toBe(true);
    expect(stopCommands(p.nextContent)).toEqual(["harness pack hook b", OPERATOR_COMMAND]);
  });

  it("a comment line that only starts with the END marker text does not end the block: one END is written and each harness hook once", () => {
    write([
      CODEX_MANAGED_BEGIN,
      GENERATED,
      ...HARNESS_A,
      `${CODEX_MANAGED_END} (the old block ended here)`,
      ...HARNESS_B,
      CODEX_MANAGED_END,
      '[projects."/work/x"]',
      'trust_level = "trusted"',
      "",
    ]);
    const p = planTwice();
    expect(endLines(p.nextContent)).toBe(1);
    expect(p.nextContent).not.toContain("(the old block ended here)");
    expect(count(p.nextContent, 'command = "harness pack hook a"')).toBe(1);
    expect(count(p.nextContent, 'command = "harness pack hook b"')).toBe(1);
    expect(p.nextContent.endsWith(`${CODEX_MANAGED_END}\n[projects."/work/x"]\ntrust_level = "trusted"\n`)).toBe(true);
  });

  it("past a foreign table, a comment line that only starts with the END marker text is not the drifted END: the real END is removed and the comment kept", () => {
    const comment = `${CODEX_MANAGED_END} (moved here by hand)`;
    write([CODEX_MANAGED_BEGIN, GENERATED, ...HARNESS_A, "[tui]", comment, "theme = 1", CODEX_MANAGED_END, ...TAIL, ""]);
    const p = planTwice();
    expect(endLines(p.nextContent)).toBe(1);
    expect(count(p.nextContent, comment)).toBe(1);
    expect(p.nextContent.endsWith(`${CODEX_MANAGED_END}\n[tui]\n${comment}\ntheme = 1\n${TAIL.join("\n")}\n`)).toBe(true);
  });
});

// Layouts in which a hook event table spelled without the `[[hooks.` prefix
// sits directly after the harness tables: `table` is spliced in there.
const RESPELLED_LAYOUTS: Array<{ label: string; hasEnd: boolean; build: (table: string[]) => string[] }> = [
  { label: "BEGIN, END after the table", hasEnd: true, build: (t) => [CODEX_MANAGED_BEGIN, GENERATED, ...HARNESS_A, ...t, CODEX_MANAGED_END, ""] },
  { label: "BEGIN, no END", hasEnd: false, build: (t) => [CODEX_MANAGED_BEGIN, GENERATED, ...HARNESS_A, ...t, ""] },
  { label: "legacy source prefix, no END", hasEnd: false, build: (t) => [SOURCE_PREFIX, GENERATED, ...HARNESS_A, ...t, ""] },
  { label: "legacy generated header, no END", hasEnd: false, build: (t) => [GENERATED, ...HARNESS_A, ...t, ""] },
  { label: "legacy source prefix, END after the table", hasEnd: true, build: (t) => [SOURCE_PREFIX, GENERATED, ...HARNESS_A, ...t, CODEX_MANAGED_END, ""] },
  { label: "legacy generated header, END after the table", hasEnd: true, build: (t) => [GENERATED, ...HARNESS_A, ...t, CODEX_MANAGED_END, ""] },
];

const RESPELLINGS = ["[[ hooks.Stop ]]", '[["hooks".Stop]]', "[[hooks . Stop]]"];

const respelledTable = (header: string, command: string): string[] => [
  header,
  `note = "${TOKEN}"`,
  `hooks = [{ type = "command", command = "${command}", timeout = 5 }]`,
];

describe("codex install: a hook event table spelled without the [[hooks. prefix directly after the harness tables is named and checked (task e8f4fc03)", () => {
  for (const layout of RESPELLED_LAYOUTS) {
    for (const spelling of RESPELLINGS) {
      it(`${layout.label}, ${spelling} holding a command harness writes: refuses naming the table and its line, file untouched, no value text`, () => {
        const config = write(layout.build(respelledTable(spelling, "harness pack hook b")));
        const { message } = refusal();
        expect(message).toContain(`has a hook table ${spelling} (line ${lineOf(config, spelling)})`);
        expect(message).toContain("whose command is one harness itself writes");
        expect(message).not.toContain("Restore the comment line");
        expect(message).toContain("Delete the table");
        expect(message.includes("move it below the")).toBe(layout.hasEnd);
        expect(message).not.toContain("pack hook b");
        expect(message).not.toContain(TOKEN);
        expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);
      });

      it(`${layout.label}, ${spelling} holding an operator command: kept once, named once with both line numbers, installs idempotently`, () => {
        const config = write(layout.build(respelledTable(spelling, OPERATOR_COMMAND)));
        const p = planTwice();
        const label = keptLabel(spelling, config, p.nextContent);
        expect(p.keptOperatorHookTables).toEqual([label]);
        expect(p.foreignSectionsPreserved).toEqual([label]);
        expect(stopCommands(p.nextContent)).toEqual(["harness pack hook b", OPERATOR_COMMAND]);
        expect(endLines(p.nextContent)).toBe(1);
        expect(JSON.stringify([p.summary, p.removedHookIds, p.foreignSectionsPreserved])).not.toContain(TOKEN);
      });
    }
  }
});

describe("codex install: tables after the harness tables that are not hook event arrays stay foreign sections (task e8f4fc03)", () => {
  const controls: Array<[string, string[], string]> = [
    ["an array of tables outside `hooks`", ['[[ "hooks-archive" . Stop ]]', `note = "${TOKEN}"`], '[[ "hooks-archive" . Stop ]]'],
    ["a single-bracket table under `hooks`", ['[hooks.state."/work/x"]', `trusted_hash = "${TOKEN}"`], '[hooks.state."/work/x"]'],
  ];
  for (const [label, table, header] of controls) {
    for (const layout of RESPELLED_LAYOUTS) {
      it(`${layout.label}, ${label}: listed as a foreign section, not as a kept hook table`, () => {
        write(layout.build(table));
        const p = planTwice();
        expect(p.keptOperatorHookTables).toEqual([]);
        expect(p.foreignSectionsPreserved).toEqual([header]);
        expect(count(p.nextContent, header)).toBe(1);
        expect(endLines(p.nextContent)).toBe(1);
      });
    }
  }
});

const LEGACY_HEADS: Array<[string, string[]]> = [
  ["source-prefix", [SOURCE_PREFIX, GENERATED]],
  ["generated-header", [GENERATED]],
];

describe("codex install: a legacy config with a foreign table between its harness tables and a surviving END marker (task e8f4fc03)", () => {
  for (const [label, head] of LEGACY_HEADS) {
    it(`legacy ${label}: a harness-commented table after the foreign table refuses, naming the foreign table and never a value`, () => {
      const config = write([...head, ...HARNESS_A, ...DOCS_TABLE, ...HARNESS_B, CODEX_MANAGED_END, ...TAIL, ""]);
      const { message } = refusal();
      expect(message).toContain("has a foreign table ([mcp_servers.docs]) sitting before more harness-owned content");
      expect(message).toContain(`line ${lineOf(config, "# harness hook: b (budget_ms=2000)")} contains '# harness hook:'`);
      expect(message).not.toContain(CODEX_MANAGED_BEGIN);
      expect(message).not.toContain(TOKEN);
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);
    });

    it(`legacy ${label}: an END marker orphaned after the foreign table is removed, the install writes one END and a second install gives the same bytes`, () => {
      write([...head, ...HARNESS_A, ...DOCS_TABLE, CODEX_MANAGED_END, ...TAIL, ""]);
      const p = planTwice();
      expect(endLines(p.nextContent)).toBe(1);
      expect(p.foreignSectionsPreserved).toEqual(["[mcp_servers.docs]"]);
      expect(p.keptOperatorHookTables).toEqual([]);
      expect(count(p.nextContent, "[mcp_servers.docs]")).toBe(1);
      expect(p.nextContent.indexOf(CODEX_MANAGED_END)).toBeLessThan(p.nextContent.indexOf("[mcp_servers.docs]"));
      expect(p.nextContent.endsWith(`${DOCS_TABLE.join("\n")}\n${TAIL.join("\n")}\n`)).toBe(true);
      expect(count(p.nextContent, GENERATED)).toBe(1);
    });
  }
});

describe("codex install: no value text on any output channel for these shapes, installs idempotent (task e8f4fc03)", () => {
  const installing: Array<[string, string[]]> = [
    [
      "nested [[hooks.Stop.HOOKS]] sub-table",
      [
        CODEX_MANAGED_BEGIN,
        GENERATED,
        ...HARNESS_A,
        "[[hooks.Stop]]",
        `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }, { type = "command", command = "operator-second", timeout = 5 }]`,
        "[[hooks.Stop.HOOKS]]",
        `note = "${TOKEN}"`,
        CODEX_MANAGED_END,
        "",
      ],
    ],
    [
      'quoted " hooks" root above BEGIN',
      [
        '[[ " hooks" . Stop ]]',
        `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }]`,
        CODEX_MANAGED_BEGIN,
        GENERATED,
        ...HARNESS_A,
        "[[hooks.Stop]]",
        `hooks = [{ type = "command", command = "${OPERATOR_COMMAND}", timeout = 5 }]`,
        CODEX_MANAGED_END,
        "",
      ],
    ],
    [
      "END-prefixed comment inside the block",
      [CODEX_MANAGED_BEGIN, GENERATED, ...HARNESS_A, `${CODEX_MANAGED_END} (old)`, ...HARNESS_B, CODEX_MANAGED_END, ...DOCS_TABLE, ""],
    ],
    ...RESPELLINGS.map((s): [string, string[]] => [
      `operator ${s} after the harness tables, END after it`,
      [CODEX_MANAGED_BEGIN, GENERATED, ...HARNESS_A, ...respelledTable(s, OPERATOR_COMMAND), CODEX_MANAGED_END, ""],
    ]),
    [
      "operator [[ hooks.Stop ]] after a legacy generated-header block, no END",
      [GENERATED, ...HARNESS_A, ...respelledTable("[[ hooks.Stop ]]", OPERATOR_COMMAND), ""],
    ],
    ...LEGACY_HEADS.map(([label, head]): [string, string[]] => [
      `legacy ${label} orphan END after a foreign table`,
      [...head, ...HARNESS_A, ...DOCS_TABLE, CODEX_MANAGED_END, ...TAIL, ""],
    ]),
  ];

  for (const [label, lines] of installing) {
    it(`${label}: every mode exits 0 with no value text, the install writes one END and a second install gives the same bytes`, async () => {
      write(lines);
      for (const r of await everyMode()) {
        expect(r.code).toBe(EX_OK);
        expect(r.out).not.toContain(TOKEN);
        expect(r.err).not.toContain(TOKEN);
      }
      expect((await cli({})).code).toBe(EX_OK);
      const first = fs.readFileSync(codexConfig, "utf8");
      expect(endLines(first)).toBe(1);
      expect((await cli({})).code).toBe(EX_OK);
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(first);
    });
  }

  const refusing: Array<[string, string[]]> = [
    ...RESPELLINGS.map((s): [string, string[]] => [
      `harness-shaped ${s} after the harness tables`,
      [CODEX_MANAGED_BEGIN, GENERATED, ...HARNESS_A, ...respelledTable(s, "harness my-own-cli run"), CODEX_MANAGED_END, ""],
    ]),
    ...LEGACY_HEADS.map(([label, head]): [string, string[]] => [
      `legacy ${label} foreign table between harness tables before a surviving END`,
      [...head, ...HARNESS_A, ...DOCS_TABLE, ...HARNESS_B, CODEX_MANAGED_END, ""],
    ]),
  ];

  for (const [label, lines] of refusing) {
    it(`${label}: every mode refuses with no value text and leaves the file untouched`, async () => {
      const config = write(lines);
      for (const r of await everyMode()) {
        expect(r.code).not.toBe(EX_OK);
        expect(`${r.out}${r.err}`).toMatch(/refus|untouched/);
        expect(r.out).not.toContain(TOKEN);
        expect(r.err).not.toContain(TOKEN);
        expect(`${r.out}${r.err}`).not.toContain("my-own-cli");
        expect(fs.readFileSync(codexConfig, "utf8")).toBe(config);
      }
    });
  }
});
