import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as yamlStringify } from "yaml";
import {
  CODEX_CONFIG_BASENAME,
  CODEX_MANAGED_BEGIN,
  CODEX_MANAGED_END,
  GENERATED_DIRNAME,
  MEMORY_BASENAME,
  SETTINGS_BASENAME,
  apply,
} from "../../../src/cli/apply/index.js";
import { HarnessExitError } from "../../../src/cli/exit-codes.js";
import { readLastApply } from "../../../src/io/last-apply.js";

let tmpHome: string;

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), "harness-apply-codex-"));
});

afterEach(() => {
  fs.rmSync(tmpHome, { recursive: true, force: true });
});

function writeManifestWithPack(): string {
  const manifest = {
    version: 1,
    tools: {
      mcp: [],
      cli: [],
      skills: { enabled: [], source_dirs: [] },
      builtin: { known: [] },
    },
    memory: { directories: [] },
    hooks: [],
    policies: [],
    policy_packs: [{ name: "understanding-before-execution" }],
  };
  const target = path.join(tmpHome, "harness.yaml");
  fs.writeFileSync(target, yamlStringify(manifest));
  return target;
}

describe("apply --runtime codex", () => {
  it("writes harness.generated/codex/config.toml in place of settings.json", async () => {
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");

    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    const settingsPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      SETTINGS_BASENAME,
    );
    const memoryPath = path.join(tmpHome, GENERATED_DIRNAME, MEMORY_BASENAME);

    expect(fs.existsSync(codexPath)).toBe(true);
    expect(fs.existsSync(settingsPath)).toBe(false);
    expect(fs.existsSync(memoryPath)).toBe(true);

    const config = fs.readFileSync(codexPath, "utf8");
    expect(config).toContain("Generated by harness apply --runtime codex");
    expect(config).toContain("harness pack hook codex-pre-tool-use");
    expect(config).toContain("harness pack hook codex-user-prompt-submit");
    expect(config).toContain(
      'matcher = "apply_patch|Bash|shell|exec_command|functions.exec_command"',
    );
    expect(config).toContain("[[hooks.PreToolUse]]");
    expect(config).toContain('hooks = [{ type = "command"');
    expect(config).not.toContain("[[hooks.pre_tool_use]]");
    expect(config).not.toContain("timeout_ms = ");
    expect(config).not.toContain("blocking = ");
  });

  it("does NOT prefix the codex UserPromptSubmit hook with UNDERSTANDING_GATE_PAUSE_FILE (agent-tasks 63fefe3a fix-round)", async () => {
    // Apply computes `pauseFile` (sentinelPath(generatedDir)) unconditionally
    // for every runtime and passes it to expandPolicyPacks, but the
    // PAUSE_FILE prefix (wrapPause) is wired ONLY into the Claude Code
    // UserPromptSubmit command (`understanding-before-execution.ts`'s
    // codex branch uses the fixed COMMAND_USER_PROMPT_SUBMIT_CODEX with no
    // wrap at all) — the npm-backed bin the prefix exists for is a
    // Claude-Code-only hook; the Codex adapter shells out to harness's own
    // CLI, which resolves generatedDir itself.
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");
    const config = fs.readFileSync(
      path.join(tmpHome, GENERATED_DIRNAME, CODEX_CONFIG_BASENAME),
      "utf8",
    );
    expect(config).toContain("harness pack hook codex-user-prompt-submit");
    expect(config).not.toContain("UNDERSTANDING_GATE_PAUSE_FILE");
  });

  it("emits the operator audit instructions.md with runtime: codex", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    const instructions = fs.readFileSync(
      path.join(
        tmpHome,
        GENERATED_DIRNAME,
        "policy-packs",
        "understanding-before-execution",
        "instructions.md",
      ),
      "utf8",
    );
    expect(instructions).toContain("Runtime\n\ncodex");
    expect(instructions).toContain("harness.generated/codex/config.toml");
    expect(instructions).toContain(
      "apply_patch|Bash|shell|exec_command|functions.exec_command",
    );
    expect(instructions).toContain("harness pack hook codex-stop");
  });

  it("default runtime keeps existing claude-code shape (settings.json present)", async () => {
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome });
    expect(result.outcome).toBe("applied");

    const settingsPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      SETTINGS_BASENAME,
    );
    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    expect(fs.existsSync(settingsPath)).toBe(true);
    expect(fs.existsSync(codexPath)).toBe(false);

    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8")) as {
      hooks: Record<string, unknown>;
    };
    expect(settings.hooks).toHaveProperty("PreToolUse");
    expect(settings.hooks).toHaveProperty("UserPromptSubmit");
    expect(settings.hooks).toHaveProperty("Stop");
  });

  it("rejects --target with --runtime codex (incompatible Claude Code surface)", async () => {
    writeManifestWithPack();
    const targetPath = path.join(tmpHome, "claude-settings.json");
    await expect(
      apply({ homeDir: tmpHome, runtime: "codex", target: targetPath }),
    ).rejects.toBeInstanceOf(HarnessExitError);
  });

  it("a re-apply against the codex output is no-op (byte-stable regeneration)", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    const second = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(second.outcome).toBe("no-changes");
  });

  it("preserves the Codex last-apply entry when a later claude-code apply refreshes .last-apply", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    await apply({ homeDir: tmpHome });

    const record = readLastApply(path.join(tmpHome, GENERATED_DIRNAME));
    expect(record?.files[CODEX_CONFIG_BASENAME]).toBeDefined();

    const codexAgain = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(codexAgain.outcome).not.toBe("drift-refuse");
    const codexFile = codexAgain.files.find(
      (f) => f.basename === CODEX_CONFIG_BASENAME,
    );
    expect(codexFile?.verdict).toBe("no-drift");
  });

  it("recovers a stale harness-generated Codex artifact when .last-apply lacks codex/config.toml", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome });

    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    fs.mkdirSync(path.dirname(codexPath), { recursive: true });
    fs.writeFileSync(
      codexPath,
      [
        "# Generated by harness apply --runtime codex.",
        "# DO NOT EDIT: re-run `harness apply --runtime codex` to regenerate.",
        "",
        "[[hooks.PreToolUse]]",
        'hooks = [{ type = "command", command = "UNDERSTANDING_GATE_REPORT_DIR=\'/home/u/.claude/.understanding-gate/reports\' harness pack hook codex-pre-tool-use", timeout = 5 }]',
        "",
      ].join("\n"),
    );

    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      codexConfigPath: codexConfig,
      now: new Date("2026-05-19T06:00:00.000Z"),
    });

    expect(result.outcome).toBe("applied");
    const codexFile = result.files.find(
      (f) => f.basename === CODEX_CONFIG_BASENAME,
    );
    expect(codexFile?.verdict).toBe("no-drift");

    const generated = fs.readFileSync(codexPath, "utf8");
    const expectedReportsDir = path.join(
      tmpHome,
      ".understanding-gate",
      "reports",
    );
    expect(generated).toContain(
      `UNDERSTANDING_GATE_REPORT_DIR='${expectedReportsDir}'`,
    );
    expect(generated).not.toContain("/.claude/.understanding-gate/reports");
    expect(
      readLastApply(path.join(tmpHome, GENERATED_DIRNAME))?.files[
        CODEX_CONFIG_BASENAME
      ],
    ).toBeDefined();
    expect(fs.readFileSync(codexConfig, "utf8")).toContain(
      `UNDERSTANDING_GATE_REPORT_DIR='${expectedReportsDir}'`,
    );
  });

  it("surfaces a warning when permission_profile is set under --runtime codex (silent-drop guard)", async () => {
    const manifest = {
      version: 1,
      tools: {
        mcp: [],
        cli: [],
        skills: { enabled: [], source_dirs: [] },
        builtin: { known: [] },
      },
      memory: { directories: [] },
      hooks: [],
      policies: [],
      policy_packs: [
        {
          name: "understanding-before-execution",
          config: { permission_profile: "safe-start" },
        },
      ],
    };
    fs.writeFileSync(
      path.join(tmpHome, "harness.yaml"),
      yamlStringify(manifest),
    );
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");
    expect(
      result.warnings.some(
        (w) => w.includes("permission") && w.includes("codex"),
      ),
    ).toBe(true);
  });

  it("installs the generated hook block into ~/.codex/config.toml and backs up the previous config", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = [
      'model = "gpt-5.5"',
      "",
      '[projects."/repo"]',
      'trust_level = "trusted"',
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, before);

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:00:00.000Z"),
    });

    expect(result.outcome).toBe("applied");
    expect(result.codexConfigInstall?.written).toBe(true);
    expect(result.codexConfigInstall?.backupPath).toBe(
      `${codexConfig}.harness-backup-2026-05-19T05-00-00-000Z`,
    );
    expect(fs.readFileSync(result.codexConfigInstall!.backupPath!, "utf8")).toBe(before);

    const installed = fs.readFileSync(codexConfig, "utf8");
    expect(installed.startsWith(`${before}\n`)).toBe(true);
    expect(installed).toContain(CODEX_MANAGED_BEGIN);
    expect(installed).toContain(CODEX_MANAGED_END);
    expect(installed).toContain("[[hooks.PreToolUse]]");
    expect(installed).toContain("harness pack hook codex-pre-tool-use");
    expect(installed).not.toContain("[[hooks.pre_tool_use]]");
    expect(installed).not.toContain("timeout_ms =");
    expect(installed).not.toContain("blocking =");
  });

  it("updates a legacy pasted harness block while preserving operator-owned config around it", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = 'model = "gpt-5.5"\n\n';
    const legacyBlock = [
      "# Harness Codex hook wiring. Generated source: old",
      "# Generated by harness apply --runtime codex.",
      "[[hooks.pre_tool_use]]",
      'match = "Bash"',
      'command = "harness old"',
      "timeout_ms = 5000",
      "blocking = true",
      "",
    ].join("\n");
    const after = [
      "[mcp_servers.agent-tasks]",
      'command = "agent-tasks-mcp-bridge"',
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, `${before}${legacyBlock}${after}`);

    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:01:00.000Z"),
    });

    const installed = fs.readFileSync(codexConfig, "utf8");
    expect(installed.startsWith(before)).toBe(true);
    expect(installed.endsWith(after)).toBe(true);
    expect(installed).toContain(CODEX_MANAGED_BEGIN);
    expect(installed).toContain("[[hooks.PreToolUse]]");
    expect(installed).not.toContain("[[hooks.pre_tool_use]]");
    expect(installed).not.toContain('command = "harness old"');
  });

  it("updates an existing current managed block and keeps surrounding config byte-for-byte", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = "[notice.model_migrations]\n\"gpt-5.3-codex\" = \"gpt-5.4\"\n\n";
    const staleBlock = [
      "# Harness Codex hook wiring. Generated source: old",
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness stale", timeout = 1 }]',
      CODEX_MANAGED_END,
      "",
    ].join("\n");
    const after = "[hooks.state]\n";
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, `${before}${staleBlock}${after}`);

    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:02:00.000Z"),
    });

    const installed = fs.readFileSync(codexConfig, "utf8");
    expect(installed.startsWith(before)).toBe(true);
    expect(installed.endsWith(after)).toBe(true);
    expect(installed).toContain(CODEX_MANAGED_BEGIN);
    expect(installed).toContain(CODEX_MANAGED_END);
    expect(installed).toContain("harness pack hook codex-pre-tool-use");
    expect(installed).not.toContain("harness stale");
  });

  it("is idempotent after installing the current managed block", async () => {
    writeManifestWithPack();
    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:03:00.000Z"),
    });

    const second = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:04:00.000Z"),
    });

    expect(second.outcome).toBe("no-changes");
    expect(second.codexConfigInstall?.changed).toBe(false);
    expect(second.codexConfigInstall?.written).toBe(false);
    const backups = fs
      .readdirSync(path.join(tmpHome, ".codex"))
      .filter((name) => name.includes(".harness-backup-"));
    expect(backups).toHaveLength(1);
  });

  it("rejects --install without --runtime codex", async () => {
    writeManifestWithPack();
    await expect(apply({ homeDir: tmpHome, installCodex: true })).rejects.toBeInstanceOf(
      HarnessExitError,
    );
  });
});
