import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as yamlStringify } from "yaml";
import {
  CODEX_CONFIG_BASENAME,
  GENERATED_DIRNAME,
  MEMORY_BASENAME,
  SETTINGS_BASENAME,
  apply,
} from "../../../src/cli/apply/index.js";
import { HarnessExitError } from "../../../src/cli/exit-codes.js";

let tmpHome: string;

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), "harness-apply-codex-"));
});

afterEach(() => {
  fs.rmSync(tmpHome, { recursive: true, force: true });
});

function writeManifestWithPack(): string {
  const manifest = {
    version: 1,
    tools: {
      mcp: [],
      cli: [],
      skills: { enabled: [], source_dirs: [] },
      builtin: { known: [] },
    },
    memory: { directories: [] },
    hooks: [],
    policies: [],
    policy_packs: [{ name: "understanding-before-execution" }],
  };
  const target = path.join(tmpHome, "harness.yaml");
  fs.writeFileSync(target, yamlStringify(manifest));
  return target;
}

describe("apply --runtime codex", () => {
  it("writes harness.generated/codex/config.toml in place of settings.json", async () => {
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");

    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    const settingsPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      SETTINGS_BASENAME,
    );
    const memoryPath = path.join(tmpHome, GENERATED_DIRNAME, MEMORY_BASENAME);

    expect(fs.existsSync(codexPath)).toBe(true);
    expect(fs.existsSync(settingsPath)).toBe(false);
    expect(fs.existsSync(memoryPath)).toBe(true);

    const config = fs.readFileSync(codexPath, "utf8");
    expect(config).toContain("Generated by harness apply --runtime codex");
    expect(config).toContain("harness pack hook codex-pre-tool-use");
    expect(config).toContain("harness pack hook codex-user-prompt-submit");
    expect(config).toContain(
      'match = "apply_patch|Bash|shell|exec_command|functions.exec_command"',
    );
  });

  it("emits the operator audit instructions.md with runtime: codex", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    const instructions = fs.readFileSync(
      path.join(
        tmpHome,
        GENERATED_DIRNAME,
        "policy-packs",
        "understanding-before-execution",
        "instructions.md",
      ),
      "utf8",
    );
    expect(instructions).toContain("Runtime\n\ncodex");
    expect(instructions).toContain("harness.generated/codex/config.toml");
    expect(instructions).toContain(
      "apply_patch|Bash|shell|exec_command|functions.exec_command",
    );
    expect(instructions).toContain("harness pack hook codex-stop");
  });

  it("default runtime keeps existing claude-code shape (settings.json present)", async () => {
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome });
    expect(result.outcome).toBe("applied");

    const settingsPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      SETTINGS_BASENAME,
    );
    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    expect(fs.existsSync(settingsPath)).toBe(true);
    expect(fs.existsSync(codexPath)).toBe(false);

    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8")) as {
      hooks: Record<string, unknown>;
    };
    expect(settings.hooks).toHaveProperty("PreToolUse");
    expect(settings.hooks).toHaveProperty("UserPromptSubmit");
    expect(settings.hooks).toHaveProperty("Stop");
  });

  it("rejects --target with --runtime codex (incompatible Claude Code surface)", async () => {
    writeManifestWithPack();
    const targetPath = path.join(tmpHome, "claude-settings.json");
    await expect(
      apply({ homeDir: tmpHome, runtime: "codex", target: targetPath }),
    ).rejects.toBeInstanceOf(HarnessExitError);
  });

  it("a re-apply against the codex output is no-op (byte-stable regeneration)", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    const second = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(second.outcome).toBe("no-changes");
  });

  it("surfaces a warning when permission_profile is set under --runtime codex (silent-drop guard)", async () => {
    const manifest = {
      version: 1,
      tools: {
        mcp: [],
        cli: [],
        skills: { enabled: [], source_dirs: [] },
        builtin: { known: [] },
      },
      memory: { directories: [] },
      hooks: [],
      policies: [],
      policy_packs: [
        {
          name: "understanding-before-execution",
          config: { permission_profile: "safe-start" },
        },
      ],
    };
    fs.writeFileSync(
      path.join(tmpHome, "harness.yaml"),
      yamlStringify(manifest),
    );
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");
    expect(
      result.warnings.some(
        (w) => w.includes("permission") && w.includes("codex"),
      ),
    ).toBe(true);
  });
});
