import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

// Counts every TOML parse the install makes. The header recognition answers
// "does this line start at the top level?" by parsing the text before the
// line, so the number of parses is what a scan over many header-shaped
// lines costs (task 01053b27).
const parses = vi.hoisted(() => ({ count: 0 }));
vi.mock("smol-toml", async (importOriginal) => {
  const actual = await importOriginal<typeof import("smol-toml")>();
  return {
    ...actual,
    parse: (...args: Parameters<typeof actual.parse>) => {
      parses.count += 1;
      return actual.parse(...args);
    },
  };
});

import {
  CODEX_MANAGED_BEGIN,
  CODEX_MANAGED_END,
  planCodexConfigInstall,
} from "../../../src/cli/apply/install-codex-config.js";

let tmpHome: string;

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "harness-codex-map-cost-"));
});

afterEach(() => {
  fs.rmSync(tmpHome, { recursive: true, force: true });
});

describe("codex install: the hook header map does not probe lines that cannot be hook headers (task 01053b27)", () => {
  const GENERATED = "# Generated by harness apply --runtime codex.";

  /** Plans the install over a config whose foreign array above the BEGIN
   * marker holds `elementLines` header-shaped element lines, with an operator
   * hook table kept after the harness tables (so the header map runs), and
   * returns how many TOML parses the plan made. */
  function parsesWithElementLines(elementLines: number): number {
    const config = [
      "[mcp_servers.x]",
      "args = [",
      ...Array.from({ length: elementLines }, (_, i) => [`  ["e${i}"]`, "  ,"]).flat(),
      "]",
      CODEX_MANAGED_BEGIN,
      GENERATED,
      "# harness hook: example-retired (budget_ms=2000)",
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      "[[hooks.Stop]]",
      'hooks = [{ type = "command", command = "operator-owned-script --flag", timeout = 5 }]',
      CODEX_MANAGED_END,
      "",
    ].join("\n");
    const configPath = path.join(tmpHome, ".codex", "config.toml");
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.writeFileSync(configPath, config);

    parses.count = 0;
    const result = planCodexConfigInstall({
      homeDir: tmpHome,
      generatedPath: "/x/config.toml",
      generatedContent: `${GENERATED}\n`,
    });
    const count = parses.count;

    const after = result.nextContent.split("\n").lastIndexOf("[[hooks.Stop]]") + 1;
    expect(result.keptOperatorHookTables).toEqual([
      `[[hooks.Stop]] (line ${elementLines * 2 + 10} before the install, line ${after} after it)`,
    ]);
    return count;
  }

  it("element lines of an array above the BEGIN marker add no parse when an operator hook table is kept", () => {
    // Probing an element line costs a parse of the text before it; none of
    // them can be a hook header, so the count must not grow with them.
    expect(parsesWithElementLines(200)).toBe(parsesWithElementLines(20));
  });
});
