import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

// Counts every TOML parse the install makes. A marker lookup answers "does
// this line sit at the top level?" by parsing the text before the line, so the
// number of parses is what a lookup over many candidate lines costs (task
// c78a155b).
const parses = vi.hoisted(() => ({ count: 0 }));
vi.mock("smol-toml", async (importOriginal) => {
  const actual = await importOriginal<typeof import("smol-toml")>();
  return {
    ...actual,
    parse: (...args: Parameters<typeof actual.parse>) => {
      parses.count += 1;
      return actual.parse(...args);
    },
  };
});

import { planCodexConfigInstall } from "../../../src/cli/apply/install-codex-config.js";

const GENERATED = "# Generated by harness apply --runtime codex.";
const HARNESS_HOOK = "# harness hook: ";

let tmpHome: string;

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "harness-codex-residuals-cost-"));
});

afterEach(() => {
  fs.rmSync(tmpHome, { recursive: true, force: true });
});

/** The number of TOML parses one plan over `lines` makes, and its result. */
function parsesFor(lines: string[]): { count: number; changed: boolean } {
  const configPath = path.join(tmpHome, ".codex", "config.toml");
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, lines.join("\n"));
  parses.count = 0;
  const plan = planCodexConfigInstall({
    homeDir: tmpHome,
    generatedPath: "/x/config.toml",
    generatedContent: `${GENERATED}\n${HARNESS_HOOK}a (budget_ms=2000)\n[[hooks.PreToolUse]]\nmatcher = "Bash"\nhooks = [{ type = "command", command = "harness pack hook a", timeout = 2 }]\n`,
  });
  const count = parses.count;
  // The counter sees the install's own parses, so equal counts are not two zeros.
  expect(count).toBeGreaterThan(0);
  return { count, changed: plan.changed };
}

const inString = (inner: string[]): string[] => ["note = '''", ...inner, "'''"];

describe("codex install: marker lookups stop probing where they cannot matter (task c78a155b)", () => {
  it("`[[hooks.` lines in a string past a generated header that opens no block add no parse", () => {
    // The lookup that lets a generated header open a block stops at the end of
    // the range the scan owns; every line past it used to cost a parse of the
    // document before it.
    const shape = (n: number) => [
      GENERATED,
      "[tui]",
      ...inString(Array.from({ length: n }, (_, i) => `[[hooks.Stop]] ${i}`)),
      "",
    ];
    const small = parsesFor(shape(20));
    const large = parsesFor(shape(200));
    expect(small.changed).toBe(true);
    expect(large.count).toBe(small.count);
  });

  it("generated-header lines in a string past a stale generated header add no parse", () => {
    const shape = (n: number) => [
      GENERATED,
      "[tui]",
      ...inString(Array.from({ length: n }, (_, i) => `${GENERATED} ${i}`)),
      "",
    ];
    expect(parsesFor(shape(200)).count).toBe(parsesFor(shape(20)).count);
  });

  it("`# harness hook:` comment and hook header pairs in a string on the append path add no parse", () => {
    const shape = (n: number) => [
      "[tui]",
      ...inString(Array.from({ length: n }, (_, i) => [`${HARNESS_HOOK}x${i} (budget_ms=1)`, "[[hooks.Stop]]"]).flat()),
      "",
    ];
    const small = parsesFor(shape(20));
    expect(small.changed).toBe(true);
    expect(parsesFor(shape(200)).count).toBe(small.count);
  });
});
