import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as yamlStringify } from "yaml";
import {
  GENERATED_DIRNAME,
  MEMORY_BASENAME,
  OPENCODE_CONFIG_BASENAME,
  SETTINGS_BASENAME,
  apply,
} from "../../../src/cli/apply/index.js";
import { HarnessExitError } from "../../../src/cli/exit-codes.js";

let tmpHome: string;

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), "harness-apply-opencode-"));
});

afterEach(() => {
  fs.rmSync(tmpHome, { recursive: true, force: true });
});

function writeManifest(extra: Record<string, unknown> = {}): string {
  const manifest = {
    version: 1,
    tools: {
      mcp: [{ name: "agent-tasks", command: "agent-tasks-mcp-bridge" }],
      cli: [],
      skills: { enabled: [], source_dirs: [] },
      builtin: { known: [] },
    },
    memory: { directories: [] },
    hooks: [],
    policies: [],
    ...extra,
  };
  const target = path.join(tmpHome, "harness.yaml");
  fs.writeFileSync(target, yamlStringify(manifest));
  return target;
}

describe("apply --runtime opencode", () => {
  it("writes harness.generated/opencode/opencode.json in place of settings.json", async () => {
    writeManifest();
    const result = await apply({ homeDir: tmpHome, runtime: "opencode" });
    expect(result.outcome).toBe("applied");

    const opencodePath = path.join(tmpHome, GENERATED_DIRNAME, OPENCODE_CONFIG_BASENAME);
    const settingsPath = path.join(tmpHome, GENERATED_DIRNAME, SETTINGS_BASENAME);
    const memoryPath = path.join(tmpHome, GENERATED_DIRNAME, MEMORY_BASENAME);

    expect(fs.existsSync(opencodePath)).toBe(true);
    expect(fs.existsSync(settingsPath)).toBe(false);
    expect(fs.existsSync(memoryPath)).toBe(true);

    const config = fs.readFileSync(opencodePath, "utf8");
    expect(config).toContain("Generated by harness apply --runtime opencode");
    expect(config).toContain('"agent-tasks"');
    expect(config).toContain('"type": "local"');
    expect(config).toContain("agent-tasks-mcp-bridge");
  });

  it("default runtime keeps existing claude-code shape (settings.json present)", async () => {
    writeManifest();
    const result = await apply({ homeDir: tmpHome });
    expect(result.outcome).toBe("applied");

    const settingsPath = path.join(tmpHome, GENERATED_DIRNAME, SETTINGS_BASENAME);
    const opencodePath = path.join(tmpHome, GENERATED_DIRNAME, OPENCODE_CONFIG_BASENAME);
    expect(fs.existsSync(settingsPath)).toBe(true);
    expect(fs.existsSync(opencodePath)).toBe(false);
  });

  it("rejects --target with --runtime opencode (incompatible Claude Code surface)", async () => {
    writeManifest();
    const targetPath = path.join(tmpHome, "claude-settings.json");
    await expect(
      apply({ homeDir: tmpHome, runtime: "opencode", target: targetPath }),
    ).rejects.toBeInstanceOf(HarnessExitError);
  });

  it("a re-apply against the opencode output is no-op (byte-stable regeneration)", async () => {
    writeManifest();
    await apply({ homeDir: tmpHome, runtime: "opencode" });
    const second = await apply({ homeDir: tmpHome, runtime: "opencode" });
    expect(second.outcome).toBe("no-changes");
  });

  it("surfaces a warning when permission_profile is set under --runtime opencode (silent-drop guard)", async () => {
    writeManifest({
      policy_packs: [
        {
          name: "understanding-before-execution",
          config: { permission_profile: "safe-start" },
        },
      ],
    });
    const result = await apply({ homeDir: tmpHome, runtime: "opencode" });
    expect(result.outcome).toBe("applied");
    expect(
      result.warnings.some((w) => w.includes("permission") && w.includes("opencode")),
    ).toBe(true);
  });

  it("does not project policy-pack hooks into the opencode config, and warns", async () => {
    writeManifest({
      policy_packs: [{ name: "understanding-before-execution" }],
    });
    const result = await apply({ homeDir: tmpHome, runtime: "opencode" });
    expect(result.outcome).toBe("applied");

    const opencodePath = path.join(tmpHome, GENERATED_DIRNAME, OPENCODE_CONFIG_BASENAME);
    const config = fs.readFileSync(opencodePath, "utf8");
    expect(config).not.toContain("harness pack hook");
    expect(config).not.toContain("PreToolUse");
    expect(
      result.warnings.some(
        (w) => w.includes("hook(s)") && w.includes("no declarative hook wiring"),
      ),
    ).toBe(true);

    // instructions.md still ships (runtime-agnostic pack file).
    const instructions = fs.readFileSync(
      path.join(
        tmpHome,
        GENERATED_DIRNAME,
        "policy-packs",
        "understanding-before-execution",
        "instructions.md",
      ),
      "utf8",
    );
    expect(instructions.length).toBeGreaterThan(0);
  });
});
