import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as yamlStringify } from "yaml";
import {
  CODEX_CONFIG_BASENAME,
  CODEX_MANAGED_BEGIN,
  CODEX_MANAGED_END,
  CodexInstallRefusalError,
  GENERATED_DIRNAME,
  MEMORY_BASENAME,
  SETTINGS_BASENAME,
  apply,
} from "../../../src/cli/apply/index.js";
import { buildProgram } from "../../../src/cli/index.js";
import { EX_FAIL, HarnessExitError } from "../../../src/cli/exit-codes.js";
import { readLastApply } from "../../../src/io/last-apply.js";

let tmpHome: string;

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), "harness-apply-codex-"));
});

afterEach(() => {
  fs.rmSync(tmpHome, { recursive: true, force: true });
});

function writeManifestWithPack(): string {
  const manifest = {
    version: 1,
    tools: {
      mcp: [],
      cli: [],
      skills: { enabled: [], source_dirs: [] },
      builtin: { known: [] },
    },
    memory: { directories: [] },
    hooks: [],
    policies: [],
    policy_packs: [{ name: "understanding-before-execution" }],
  };
  const target = path.join(tmpHome, "harness.yaml");
  fs.writeFileSync(target, yamlStringify(manifest));
  return target;
}

describe("apply --runtime codex", () => {
  it("writes harness.generated/codex/config.toml in place of settings.json", async () => {
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");

    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    const settingsPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      SETTINGS_BASENAME,
    );
    const memoryPath = path.join(tmpHome, GENERATED_DIRNAME, MEMORY_BASENAME);

    expect(fs.existsSync(codexPath)).toBe(true);
    expect(fs.existsSync(settingsPath)).toBe(false);
    expect(fs.existsSync(memoryPath)).toBe(true);

    const config = fs.readFileSync(codexPath, "utf8");
    expect(config).toContain("Generated by harness apply --runtime codex");
    expect(config).toContain("harness pack hook codex-pre-tool-use");
    expect(config).toContain("harness pack hook codex-user-prompt-submit");
    expect(config).toContain(
      'matcher = "apply_patch|Bash|shell|exec_command|functions.exec_command"',
    );
    expect(config).toContain("[[hooks.PreToolUse]]");
    expect(config).toContain('hooks = [{ type = "command"');
    expect(config).not.toContain("[[hooks.pre_tool_use]]");
    expect(config).not.toContain("timeout_ms = ");
    expect(config).not.toContain("blocking = ");
  });

  it("does NOT prefix the codex UserPromptSubmit hook with UNDERSTANDING_GATE_PAUSE_FILE", async () => {
    // Apply computes `pauseFile` (sentinelPath(generatedDir)) unconditionally
    // for every runtime and passes it to expandPolicyPacks, but the
    // PAUSE_FILE prefix (wrapPause) is wired ONLY into the Claude Code
    // UserPromptSubmit command (`understanding-before-execution.ts`'s
    // codex branch uses the fixed COMMAND_USER_PROMPT_SUBMIT_CODEX with no
    // wrap at all) — the prefix exists only for the npm-backed
    // understanding-gate-claude-hook bin, which is Claude-Code-only; the
    // reason the Codex hook doesn't need it isn't that the Codex path is
    // already pause-aware. It is NOT: per src/cli/pack/hook-bootstrap.ts's
    // own inventory comment, hook-codex-user-prompt-submit.ts does no pause
    // check at all today. Codex pause-parity is an open, unrelated gap this
    // task does not close (agent-tasks 63fefe3a fix-round).
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");
    const config = fs.readFileSync(
      path.join(tmpHome, GENERATED_DIRNAME, CODEX_CONFIG_BASENAME),
      "utf8",
    );
    expect(config).toContain("harness pack hook codex-user-prompt-submit");
    expect(config).not.toContain("UNDERSTANDING_GATE_PAUSE_FILE");
  });

  it("emits the operator audit instructions.md with runtime: codex", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    const instructions = fs.readFileSync(
      path.join(
        tmpHome,
        GENERATED_DIRNAME,
        "policy-packs",
        "understanding-before-execution",
        "instructions.md",
      ),
      "utf8",
    );
    expect(instructions).toContain("Runtime\n\ncodex");
    expect(instructions).toContain("harness.generated/codex/config.toml");
    expect(instructions).toContain(
      "apply_patch|Bash|shell|exec_command|functions.exec_command",
    );
    expect(instructions).toContain("harness pack hook codex-stop");
  });

  it("default runtime keeps existing claude-code shape (settings.json present)", async () => {
    writeManifestWithPack();
    const result = await apply({ homeDir: tmpHome });
    expect(result.outcome).toBe("applied");

    const settingsPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      SETTINGS_BASENAME,
    );
    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    expect(fs.existsSync(settingsPath)).toBe(true);
    expect(fs.existsSync(codexPath)).toBe(false);

    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8")) as {
      hooks: Record<string, unknown>;
    };
    expect(settings.hooks).toHaveProperty("PreToolUse");
    expect(settings.hooks).toHaveProperty("UserPromptSubmit");
    expect(settings.hooks).toHaveProperty("Stop");
  });

  it("rejects --target with --runtime codex (incompatible Claude Code surface)", async () => {
    writeManifestWithPack();
    const targetPath = path.join(tmpHome, "claude-settings.json");
    await expect(
      apply({ homeDir: tmpHome, runtime: "codex", target: targetPath }),
    ).rejects.toBeInstanceOf(HarnessExitError);
  });

  it("a re-apply against the codex output is no-op (byte-stable regeneration)", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    const second = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(second.outcome).toBe("no-changes");
  });

  it("preserves the Codex last-apply entry when a later claude-code apply refreshes .last-apply", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome, runtime: "codex" });
    await apply({ homeDir: tmpHome });

    const record = readLastApply(path.join(tmpHome, GENERATED_DIRNAME));
    expect(record?.files[CODEX_CONFIG_BASENAME]).toBeDefined();

    const codexAgain = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(codexAgain.outcome).not.toBe("drift-refuse");
    const codexFile = codexAgain.files.find(
      (f) => f.basename === CODEX_CONFIG_BASENAME,
    );
    expect(codexFile?.verdict).toBe("no-drift");
  });

  it("recovers a stale harness-generated Codex artifact when .last-apply lacks codex/config.toml", async () => {
    writeManifestWithPack();
    await apply({ homeDir: tmpHome });

    const codexPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    fs.mkdirSync(path.dirname(codexPath), { recursive: true });
    fs.writeFileSync(
      codexPath,
      [
        "# Generated by harness apply --runtime codex.",
        "# DO NOT EDIT: re-run `harness apply --runtime codex` to regenerate.",
        "",
        "[[hooks.PreToolUse]]",
        'hooks = [{ type = "command", command = "UNDERSTANDING_GATE_REPORT_DIR=\'/home/u/.claude/.understanding-gate/reports\' harness pack hook codex-pre-tool-use", timeout = 5 }]',
        "",
      ].join("\n"),
    );

    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      codexConfigPath: codexConfig,
      now: new Date("2026-05-19T06:00:00.000Z"),
    });

    expect(result.outcome).toBe("applied");
    const codexFile = result.files.find(
      (f) => f.basename === CODEX_CONFIG_BASENAME,
    );
    expect(codexFile?.verdict).toBe("no-drift");

    const generated = fs.readFileSync(codexPath, "utf8");
    const expectedReportsDir = path.join(
      tmpHome,
      ".understanding-gate",
      "reports",
    );
    expect(generated).toContain(
      `UNDERSTANDING_GATE_REPORT_DIR='${expectedReportsDir}'`,
    );
    expect(generated).not.toContain("/.claude/.understanding-gate/reports");
    expect(
      readLastApply(path.join(tmpHome, GENERATED_DIRNAME))?.files[
        CODEX_CONFIG_BASENAME
      ],
    ).toBeDefined();
    expect(fs.readFileSync(codexConfig, "utf8")).toContain(
      `UNDERSTANDING_GATE_REPORT_DIR='${expectedReportsDir}'`,
    );
  });

  it("surfaces a warning when permission_profile is set under --runtime codex (silent-drop guard)", async () => {
    const manifest = {
      version: 1,
      tools: {
        mcp: [],
        cli: [],
        skills: { enabled: [], source_dirs: [] },
        builtin: { known: [] },
      },
      memory: { directories: [] },
      hooks: [],
      policies: [],
      policy_packs: [
        {
          name: "understanding-before-execution",
          config: { permission_profile: "safe-start" },
        },
      ],
    };
    fs.writeFileSync(
      path.join(tmpHome, "harness.yaml"),
      yamlStringify(manifest),
    );
    const result = await apply({ homeDir: tmpHome, runtime: "codex" });
    expect(result.outcome).toBe("applied");
    expect(
      result.warnings.some(
        (w) => w.includes("permission") && w.includes("codex"),
      ),
    ).toBe(true);
  });

  it("installs the generated hook block into ~/.codex/config.toml and backs up the previous config", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = [
      'model = "gpt-5.5"',
      "",
      '[projects."/repo"]',
      'trust_level = "trusted"',
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, before);

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:00:00.000Z"),
    });

    expect(result.outcome).toBe("applied");
    expect(result.codexConfigInstall?.written).toBe(true);
    expect(result.codexConfigInstall?.backupPath).toBe(
      `${codexConfig}.harness-backup-2026-05-19T05-00-00-000Z`,
    );
    expect(fs.readFileSync(result.codexConfigInstall!.backupPath!, "utf8")).toBe(before);

    const installed = fs.readFileSync(codexConfig, "utf8");
    expect(installed.startsWith(`${before}\n`)).toBe(true);
    expect(installed).toContain(CODEX_MANAGED_BEGIN);
    expect(installed).toContain(CODEX_MANAGED_END);
    expect(installed).toContain("[[hooks.PreToolUse]]");
    expect(installed).toContain("harness pack hook codex-pre-tool-use");
    expect(installed).not.toContain("[[hooks.pre_tool_use]]");
    expect(installed).not.toContain("timeout_ms =");
    expect(installed).not.toContain("blocking =");
  });

  it("updates a legacy pasted harness block while preserving operator-owned config around it", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = 'model = "gpt-5.5"\n\n';
    const legacyBlock = [
      "# Harness Codex hook wiring. Generated source: old",
      "# Generated by harness apply --runtime codex.",
      "[[hooks.pre_tool_use]]",
      'match = "Bash"',
      'command = "harness old"',
      "timeout_ms = 5000",
      "blocking = true",
      "",
    ].join("\n");
    const after = [
      "[mcp_servers.agent-tasks]",
      'command = "agent-tasks-mcp-bridge"',
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, `${before}${legacyBlock}${after}`);

    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:01:00.000Z"),
    });

    const installed = fs.readFileSync(codexConfig, "utf8");
    expect(installed.startsWith(before)).toBe(true);
    expect(installed.endsWith(after)).toBe(true);
    expect(installed).toContain(CODEX_MANAGED_BEGIN);
    expect(installed).toContain("[[hooks.PreToolUse]]");
    expect(installed).not.toContain("[[hooks.pre_tool_use]]");
    expect(installed).not.toContain('command = "harness old"');
  });

  it("updates an existing current managed block and keeps surrounding config byte-for-byte", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = "[notice.model_migrations]\n\"gpt-5.3-codex\" = \"gpt-5.4\"\n\n";
    const staleBlock = [
      "# Harness Codex hook wiring. Generated source: old",
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness stale", timeout = 1 }]',
      CODEX_MANAGED_END,
      "",
    ].join("\n");
    const after = "[hooks.state]\n";
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, `${before}${staleBlock}${after}`);

    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:02:00.000Z"),
    });

    const installed = fs.readFileSync(codexConfig, "utf8");
    expect(installed.startsWith(before)).toBe(true);
    expect(installed.endsWith(after)).toBe(true);
    expect(installed).toContain(CODEX_MANAGED_BEGIN);
    expect(installed).toContain(CODEX_MANAGED_END);
    expect(installed).toContain("harness pack hook codex-pre-tool-use");
    expect(installed).not.toContain("harness stale");
  });

  it("is idempotent after installing the current managed block", async () => {
    writeManifestWithPack();
    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:03:00.000Z"),
    });

    const second = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-05-19T05:04:00.000Z"),
    });

    expect(second.outcome).toBe("no-changes");
    expect(second.codexConfigInstall?.changed).toBe(false);
    expect(second.codexConfigInstall?.written).toBe(false);
    const backups = fs
      .readdirSync(path.join(tmpHome, ".codex"))
      .filter((name) => name.includes(".harness-backup-"));
    expect(backups).toHaveLength(1);
  });

  it("rejects --install without --runtime codex", async () => {
    writeManifestWithPack();
    await expect(apply({ homeDir: tmpHome, installCodex: true })).rejects.toBeInstanceOf(
      HarnessExitError,
    );
  });
});

// Task 6a037359: a real dogfood install found the previous harness release's
// `findManagedRange` trusting a found END marker unconditionally. In the
// operator's config the END marker had drifted to sit after Codex's own
// [hooks.state] trust table, [marketplaces.*], [plugins.*] and [tui]
// tables, so an install deleted all of them. This fixture reproduces that
// shape with neutral placeholder paths (the real evidence file carries the
// operator's home directory).
const RETIRED_HOOK_ID = "policy-pack:example-retired-pack:codex:pre-tool-use";

const FOREIGN_BLOCK = [
  "[hooks.state]",
  "",
  '[hooks.state."/home/user/.codex/config.toml:pre_tool_use:0:0"]',
  'trusted_hash = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"',
  "",
  '[hooks.state."/home/user/.codex/config.toml:post_tool_use:0:0"]',
  'trusted_hash = "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"',
  "",
  "[marketplaces.example-bundled]",
  'source_type = "local"',
  'source = "/home/user/.codex/.tmp/bundled-marketplaces/example-bundled"',
  "",
  '[plugins."visualize@example-bundled"]',
  "enabled = true",
  "",
  "[tui]",
  "screen_reader_detection_done = true",
  "",
].join("\n");

const TRAILING_OPERATOR_BLOCK = [
  "# User-managed MCP registrations.",
  "",
  "[mcp_servers.example]",
  'command = "example"',
  "",
].join("\n");

function buildDriftedEndConfig(): string {
  const staleManagedBlock = [
    "# Harness Codex hook wiring. Generated source: old",
    CODEX_MANAGED_BEGIN,
    "# Generated by harness apply --runtime codex.",
    `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
    "[[hooks.PreToolUse]]",
    'matcher = "Bash"',
    'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
    "",
  ].join("\n");
  return [
    'model = "gpt-5.5"',
    "",
    staleManagedBlock,
    FOREIGN_BLOCK,
    CODEX_MANAGED_END,
    "",
    TRAILING_OPERATOR_BLOCK,
  ].join("\n");
}

describe("apply --runtime codex --install against a config whose END marker drifted past foreign content (task 6a037359)", () => {
  it("keeps every foreign table byte-for-byte, strips the stray END, and re-stamps a fresh END right after the regenerated block", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, buildDriftedEndConfig());

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-09-23T14:00:00.000Z"),
    });

    expect(result.outcome).toBe("applied");
    const installed = fs.readFileSync(codexConfig, "utf8");

    // Every foreign table survives byte-for-byte, and so does the
    // operator's own content that used to follow the stray END.
    expect(installed).toContain(FOREIGN_BLOCK);
    expect(installed).toContain(TRAILING_OPERATOR_BLOCK);

    // Exactly one END marker, immediately before the foreign block (not
    // after it, which is what the bug produced).
    const endOccurrences = installed.split(CODEX_MANAGED_END).length - 1;
    expect(endOccurrences).toBe(1);
    expect(installed.indexOf(CODEX_MANAGED_END)).toBeLessThan(
      installed.indexOf("[hooks.state]"),
    );

    // The regenerated block replaces the stale hook table; the retired
    // one is gone.
    expect(installed).toContain(
      'apply_patch|Bash|shell|exec_command|functions.exec_command',
    );
    expect(installed).not.toContain("harness pack hook example-retired");
    expect(installed).not.toContain(RETIRED_HOOK_ID);
  });

  it("dry-run names the removed hook block and every foreign section it preserves, before writing anything", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = buildDriftedEndConfig();
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, before);

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      dryRun: true,
    });

    expect(result.outcome).toBe("would-apply");
    expect(result.codexConfigInstall?.written).toBe(false);
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(before);

    // Exact equality (not `arrayContaining`): the FOREIGN_BLOCK fixture has
    // three `[hooks.state...]`-family lines collapsing to one root, so
    // `arrayContaining` alone would not notice a duplicate/undeduped entry
    // (a mutant on `collectForeignSectionHeaders`'s dedup
    // check survived exactly because the prior assertion here could not
    // tell "4 correct entries" from "6 entries, one just happens to be
    // present 3 times" apart).
    expect(result.codexConfigInstall?.removedHookIds).toEqual([RETIRED_HOOK_ID]);
    expect(result.codexConfigInstall?.foreignSectionsPreserved).toEqual([
      "[hooks.state] (3 tables)",
      "[marketplaces.example-bundled]",
      '[plugins."visualize@example-bundled"]',
      "[tui]",
    ]);
  });

  it("produces the exact installed byte content for the drifted fixture", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const input = buildDriftedEndConfig();
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, input);

    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-09-23T14:00:00.000Z"),
    });
    const installed = fs.readFileSync(codexConfig, "utf8");

    // Independently derive the expected FULL content by string-replacing
    // the exact stale-managed-block text (known verbatim: it is exactly
    // what `buildDriftedEndConfig`'s own `staleManagedBlock` literal
    // constructs) with a freshly built managed block, inside the KNOWN
    // input fixture -- leaving every other byte of the input (blank
    // lines, FOREIGN_BLOCK, the original stray END, TRAILING_OPERATOR_
    // BLOCK) completely untouched. The new block's own generated hook
    // content comes from the SAME harness.generated/codex/config.toml
    // apply() also wrote, not copied from `installed`, so this assertion
    // is not circular: it fails if anything besides that one substitution
    // changed (extra/missing blank lines, wrong END position, mangled
    // foreign/trailing content), not only if the managed block's own text
    // is wrong.
    const staleManagedBlockText = [
      "# Harness Codex hook wiring. Generated source: old",
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      "",
    ].join("\n");
    expect(input).toContain(staleManagedBlockText);

    const generatedCodexConfigPath = path.join(
      tmpHome,
      GENERATED_DIRNAME,
      CODEX_CONFIG_BASENAME,
    );
    const generatedContent = fs.readFileSync(generatedCodexConfigPath, "utf8");
    const freshManagedBlock = [
      `# Harness Codex hook wiring. Generated source: ${generatedCodexConfigPath}`,
      CODEX_MANAGED_BEGIN,
      generatedContent.trimEnd(),
      CODEX_MANAGED_END,
      "",
    ].join("\n");
    const afterBlockSwap = input.replace(staleManagedBlockText, freshManagedBlock);
    // The fix also excises the ORIGINAL (stray) END marker line -- the
    // whole point of the underlying bug fix -- so remove exactly that one
    // line, found strictly after the freshly-built block's own END, from
    // the expectation too.
    const freshBlockEndIdx = afterBlockSwap.indexOf(freshManagedBlock) + freshManagedBlock.length;
    const strayEndLine = `${CODEX_MANAGED_END}\n`;
    const strayEndIdx = afterBlockSwap.indexOf(strayEndLine, freshBlockEndIdx);
    expect(strayEndIdx).toBeGreaterThan(-1);
    const expected =
      afterBlockSwap.slice(0, strayEndIdx) +
      afterBlockSwap.slice(strayEndIdx + strayEndLine.length);
    expect(installed).toBe(expected);
  });
});

describe("apply --runtime codex --install refuses when the harness block looks split by foreign content (task 6a037359 mirror case)", () => {
  it("throws a CodexInstallRefusalError naming the resolved config path, the offending line, and the last-resort backup warning, instead of guessing", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const splitConfig = [
      "# Harness Codex hook wiring. Generated source: old",
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      "",
      "[a-foreign-table-inserted-mid-block]",
      'value = "surprise"',
      "",
      "# harness hook: policy-pack:example-retired-pack:codex:stop (budget_ms=2000)",
      "[[hooks.Stop]]",
      'hooks = [{ type = "command", command = "harness pack hook example-retired-stop", timeout = 2 }]',
      CODEX_MANAGED_END,
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, splitConfig);

    let caught: unknown;
    try {
      await apply({ homeDir: tmpHome, runtime: "codex", installCodex: true });
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(CodexInstallRefusalError);
    const err = caught as CodexInstallRefusalError;
    expect(err).toBeInstanceOf(HarnessExitError);
    expect(err.exitCode).toBe(EX_FAIL);
    expect(err.configPath).toBe(codexConfig);
    // Names the resolved config path (never a hard-coded ~/.codex), the
    // foreign table that split the block, and tells the operator what to
    // do about it: move the table, or delete the offending lines.
    expect(err.message).toContain(codexConfig);
    expect(err.message).toContain("[a-foreign-table-inserted-mid-block]");
    expect(err.message).toContain(
      "Move [a-foreign-table-inserted-mid-block] below the '# END harness-managed codex hooks' marker",
    );
    expect(err.message).toContain(
      "delete the lines between '# BEGIN harness-managed codex hooks' and '# END harness-managed codex hooks'",
    );
    // The backup restore is offered only as a last resort, with a warning
    // that it drops later Codex state.
    expect(err.message).toContain("As a last resort");
    expect(err.message).toContain(
      "discards any Codex state (hook trust entries, marketplaces, plugins)",
    );
    expect(err.message).not.toContain("~/.codex");

    // Refuses before writing anything.
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(splitConfig);
  });

  it("--json emits a structured codex-install-refuse error on stdout instead of only the plain-text message", async () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), "harness-apply-codex-json-"));
    try {
      const manifest = {
        version: 1,
        tools: {
          mcp: [],
          cli: [],
          skills: { enabled: [], source_dirs: [] },
          builtin: { known: [] },
        },
        memory: { directories: [] },
        hooks: [],
        policies: [],
        policy_packs: [{ name: "understanding-before-execution" }],
      };
      fs.writeFileSync(path.join(home, "harness.yaml"), yamlStringify(manifest));
      const codexConfig = path.join(home, ".codex", "config.toml");
      const splitConfig = [
        "# Harness Codex hook wiring. Generated source: old",
        CODEX_MANAGED_BEGIN,
        "# Generated by harness apply --runtime codex.",
        `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
        "[[hooks.PreToolUse]]",
        'matcher = "Bash"',
        'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
        "",
        "[a-foreign-table-inserted-mid-block]",
        'value = "surprise"',
        "",
        "# harness hook: policy-pack:example-retired-pack:codex:stop (budget_ms=2000)",
        "[[hooks.Stop]]",
        'hooks = [{ type = "command", command = "harness pack hook example-retired-stop", timeout = 2 }]',
        CODEX_MANAGED_END,
        "",
      ].join("\n");
      fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
      fs.writeFileSync(codexConfig, splitConfig);

      let out = "";
      let err = "";
      const program = buildProgram({
        stdout: (s: string) => {
          out += s;
        },
        stderr: (s: string) => {
          err += s;
        },
      });
      await expect(
        program.parseAsync(
          [
            "apply",
            "--config",
            path.join(home, "harness.yaml"),
            "--runtime",
            "codex",
            "--install",
            "--codex-config",
            codexConfig,
            "--json",
          ],
          { from: "user" },
        ),
      ).rejects.toBeInstanceOf(HarnessExitError);

      const parsed = JSON.parse(out) as {
        outcome: string;
        configPath: string;
        error: string;
      };
      expect(parsed.outcome).toBe("codex-install-refuse");
      expect(parsed.configPath).toBe(codexConfig);
      expect(parsed.error).toContain("[a-foreign-table-inserted-mid-block]");
      // No prose mixed into the machine-readable stream: the JSON object
      // is the only thing on stdout, and (matching the existing
      // `target-exists-refuse` / `drift-refuse` --json convention) the
      // exit-signaling `HarnessExitError` this throws carries no message
      // of its own, so stderr stays empty too -- the full error text
      // lives only in the JSON's `error` field.
      expect(out.trim().startsWith("{")).toBe(true);
      expect(err).toBe("");
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(splitConfig);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it("rejects a config with two harness-managed BEGIN markers instead of guessing which is current, and leaves the file untouched", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const duplicateBeginConfig = [
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      CODEX_MANAGED_END,
      "",
      "[tui]",
      "a = 1",
      "",
      CODEX_MANAGED_BEGIN,
      "# a second, stale managed block an operator's merge left behind",
      CODEX_MANAGED_END,
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, duplicateBeginConfig);

    let caught: unknown;
    try {
      await apply({ homeDir: tmpHome, runtime: "codex", installCodex: true });
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(CodexInstallRefusalError);
    const err = caught as CodexInstallRefusalError;
    expect(err.exitCode).toBe(EX_FAIL);
    expect(err.configPath).toBe(codexConfig);
    expect(err.message).toContain(codexConfig);
    expect(err.message).toContain("more than one");
    expect(err.message).not.toContain("~/.codex");

    // Refuses before writing anything.
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(duplicateBeginConfig);
  });

  it("rejects a BEGIN with no END once a foreign table is followed by a real harness-hook comment further down, instead of guessing", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    // No END marker anywhere: the owned-content scan stops at the first
    // foreign table ([tui]), the stray-END search then finds nothing, and
    // the remaining zone (from [tui] to EOF) still contains a real
    // `# harness hook:` comment further down -- the block looks split by
    // foreign content, so this must refuse rather than silently discard
    // whatever comes after [tui] as part of the replaced region.
    const beginNoEndConfig = [
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      "",
      "[tui]",
      "a = 1",
      "",
      "# harness hook: policy-pack:example-retired-pack:codex:stop (budget_ms=2000)",
      "[[hooks.Stop]]",
      'hooks = [{ type = "command", command = "harness pack hook example-retired-stop", timeout = 2 }]',
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, beginNoEndConfig);

    let caught: unknown;
    try {
      await apply({ homeDir: tmpHome, runtime: "codex", installCodex: true });
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(CodexInstallRefusalError);
    expect((caught as CodexInstallRefusalError).message).toContain("[tui]");
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(beginNoEndConfig);
  });
});

describe("apply --runtime codex --install: header recognition does not misread a multi-line array or a foreign multi-line string (task `6a037359`)", () => {
  it("does not end the owned region on an array-continuation line, and preserves only the real foreign table after it", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    // `matrix = [ ... ]` spans multiple lines inside the STALE hook table
    // being replaced; its continuation line `  [1, 2],` must not be
    // misread as a foreign table header (it has no matching TOML header
    // shape: a trailing comma after the closing bracket).
    const arrayContinuationConfig = [
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      "matrix = [",
      "  [1, 2],",
      "]",
      "",
      "[tui]",
      "a = 1",
      CODEX_MANAGED_END,
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, arrayContinuationConfig);

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      dryRun: true,
    });

    expect(result.outcome).toBe("would-apply");
    // Only the real foreign table is reported/preserved; the array
    // continuation line and its closing bracket never appear as a
    // "foreign section" of their own.
    expect(result.codexConfigInstall?.foreignSectionsPreserved).toEqual(["[tui]"]);
  });

  it("does not corrupt a foreign multi-line TOML string that happens to contain a line reading like the harness END marker", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    // Drifted (no real END marker after the stale hook table): the ONLY
    // textual occurrence of "# END harness-managed codex hooks" sits
    // inside a foreign `[notes]` table's own triple-quoted string value.
    // Excising it as if it were a real stray END would corrupt that
    // string; the fix must preserve `[notes]` (and its string) verbatim.
    const embeddedEndConfig = [
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      "",
      "[notes]",
      'text = """',
      CODEX_MANAGED_END,
      "keep me",
      '"""',
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, embeddedEndConfig);

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-09-23T15:00:00.000Z"),
    });

    expect(result.outcome).toBe("applied");
    const installed = fs.readFileSync(codexConfig, "utf8");
    // The whole `[notes]` table, including its embedded look-alike line,
    // survives byte-for-byte.
    expect(installed).toContain(
      ['[notes]', 'text = """', CODEX_MANAGED_END, "keep me", '"""', ""].join("\n"),
    );
    // Exactly one END marker overall: the fresh one right after the
    // regenerated block, not a second one excised from inside the string.
    const endOccurrences = installed.split(CODEX_MANAGED_END).length - 1;
    expect(endOccurrences).toBe(2); // the fresh END, plus the one still embedded in the string
  });
});

describe("apply --runtime codex --install: preserves the config's own file mode instead of widening it (task `6a037359`)", () => {
  it("keeps a 0600 config and its backup at 0600 after install", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const before = ['model = "gpt-5.5"', ""].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, before);
    fs.chmodSync(codexConfig, 0o600);

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-09-23T16:00:00.000Z"),
    });

    expect(result.codexConfigInstall?.written).toBe(true);
    const backupPath = result.codexConfigInstall!.backupPath!;
    expect(fs.statSync(codexConfig).mode & 0o777).toBe(0o600);
    expect(fs.statSync(backupPath).mode & 0o777).toBe(0o600);
  });

  it("creates a fresh config and its backup at 0600 (not atomicWriteFile's 0644 default) when no config existed before", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");

    const result = await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-09-23T16:01:00.000Z"),
    });

    expect(result.codexConfigInstall?.written).toBe(true);
    expect(fs.statSync(codexConfig).mode & 0o777).toBe(0o600);
  });
});

describe("apply --runtime codex --install: an operator comment directly above the first foreign table stays attached to it, not swallowed into the replaced block (task `6a037359`)", () => {
  it("preserves the comment exactly once, positioned after the new END and directly above the foreign table", async () => {
    writeManifestWithPack();
    const codexConfig = path.join(tmpHome, ".codex", "config.toml");
    const operatorComment = "# operator: keep this comment with the foreign block below";
    const config = [
      'model = "gpt-5.5"',
      "",
      "# Harness Codex hook wiring. Generated source: old",
      CODEX_MANAGED_BEGIN,
      "# Generated by harness apply --runtime codex.",
      `# harness hook: ${RETIRED_HOOK_ID} (budget_ms=2000)`,
      "[[hooks.PreToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook example-retired", timeout = 2 }]',
      "",
      operatorComment,
      FOREIGN_BLOCK,
      CODEX_MANAGED_END,
      "",
      TRAILING_OPERATOR_BLOCK,
    ].join("\n");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, config);

    await apply({
      homeDir: tmpHome,
      runtime: "codex",
      installCodex: true,
      now: new Date("2026-09-23T17:00:00.000Z"),
    });
    const installed = fs.readFileSync(codexConfig, "utf8");

    // Exactly once (a mutant that folds the comment into the replaced
    // managed block instead of backing off before it would silently drop
    // it, not duplicate it -- but the exact-count assertion also catches
    // a duplication regression, which "toContain" alone would not).
    const occurrences = installed.split(operatorComment).length - 1;
    expect(occurrences).toBe(1);

    const commentIdx = installed.indexOf(operatorComment);
    const endIdx = installed.indexOf(CODEX_MANAGED_END);
    expect(commentIdx).toBeGreaterThan(-1);
    expect(commentIdx).toBeGreaterThan(endIdx);
    // Directly above the first foreign table, no other line in between.
    expect(installed.slice(commentIdx)).toMatch(
      new RegExp(`^${operatorComment.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n\\[hooks\\.state\\]`),
    );
  });
});

describe("apply --runtime codex --install --dry-run / --install: CLI-level output names removed hook blocks and preserved foreign sections (task `6a037359`)", () => {
  function writeDriftedFixture(home: string): { codexConfig: string; manifestPath: string } {
    const manifest = {
      version: 1,
      tools: {
        mcp: [],
        cli: [],
        skills: { enabled: [], source_dirs: [] },
        builtin: { known: [] },
      },
      memory: { directories: [] },
      hooks: [],
      policies: [],
      policy_packs: [{ name: "understanding-before-execution" }],
    };
    const manifestPath = path.join(home, "harness.yaml");
    fs.writeFileSync(manifestPath, yamlStringify(manifest));
    const codexConfig = path.join(home, ".codex", "config.toml");
    fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
    fs.writeFileSync(codexConfig, buildDriftedEndConfig());
    return { codexConfig, manifestPath };
  }

  it("--dry-run prints the removing-hook-block and preserving-foreign-section lines via the real CLI program, before writing anything", async () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), "harness-apply-codex-cli-dry-"));
    try {
      const { codexConfig, manifestPath } = writeDriftedFixture(home);
      const before = fs.readFileSync(codexConfig, "utf8");
      let out = "";
      const program = buildProgram({
        stdout: (s: string) => {
          out += s;
        },
        stderr: () => {},
      });
      await program.parseAsync(
        [
          "apply",
          "--config",
          manifestPath,
          "--runtime",
          "codex",
          "--install",
          "--dry-run",
          "--codex-config",
          codexConfig,
        ],
        { from: "user" },
      );

      expect(out).toContain(`removing hook block: ${RETIRED_HOOK_ID}`);
      expect(out).toContain("preserving foreign section: [hooks.state] (3 tables)");
      expect(out).toContain("preserving foreign section: [marketplaces.example-bundled]");
      expect(out).toContain('preserving foreign section: [plugins."visualize@example-bundled"]');
      expect(out).toContain("preserving foreign section: [tui]");
      // Dry-run: nothing written.
      expect(fs.readFileSync(codexConfig, "utf8")).toBe(before);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it("a non-dry-run install prints the removed-hook-block and preserved-foreign-section summary lines via the real CLI program", async () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), "harness-apply-codex-cli-applied-"));
    try {
      const { codexConfig, manifestPath } = writeDriftedFixture(home);
      let out = "";
      const program = buildProgram({
        stdout: (s: string) => {
          out += s;
        },
        stderr: () => {},
      });
      await program.parseAsync(
        [
          "apply",
          "--config",
          manifestPath,
          "--runtime",
          "codex",
          "--install",
          "--codex-config",
          codexConfig,
        ],
        { from: "user" },
      );

      expect(out).toContain(`removed hook block: ${RETIRED_HOOK_ID}`);
      expect(out).toContain("preserved foreign section: [hooks.state] (3 tables)");
      expect(out).toContain("preserved foreign section: [marketplaces.example-bundled]");
      expect(out).toContain('preserved foreign section: [plugins."visualize@example-bundled"]');
      expect(out).toContain("preserved foreign section: [tui]");
      expect(out).toMatch(/backup written to/);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });
});
