import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as yamlStringify } from "yaml";
import {
  CODEX_MANAGED_BEGIN,
  CODEX_MANAGED_END,
  CodexInstallRefusalError,
  planCodexConfigInstall,
} from "../../../src/cli/apply/index.js";
import { assertNoSplitBlock } from "../../../src/cli/apply/install-codex-config.js";
import { EX_OK } from "../../../src/cli/exit-codes.js";
import { run } from "../../../src/cli/index.js";

// A multi-line array whose element sits on its own line (`["x"]`, `['x']`,
// `[1]`, `[1979-05-27]`) has the exact shape of a TOML table header. The
// install must never take such a line for a header: not when it lists the
// foreign sections it preserves, not when it finds where the harness block
// ends, and not when it names the foreign table in a split-block refusal
// (task 6b56d735).

const TOKEN = "sk-live-FAKE0123456789";

// Each shape is one array element on its own line, with the text the
// element must never surface as.
const SHAPES: Array<{ label: string; element: string; text: string }> = [
  { label: "nested basic string", element: `  ["--token=${TOKEN}"]`, text: TOKEN },
  { label: "nested literal string", element: `  ['${TOKEN}']`, text: TOKEN },
  { label: "nested integer", element: "  [1]", text: "[1]" },
  { label: "nested date", element: "  [1979-05-27]", text: "1979-05-27" },
];

const RETIRED_ID = "example-retired";
const OLD_BLOCK = [
  "# Harness Codex hook wiring. Generated source: old",
  CODEX_MANAGED_BEGIN,
  "# Generated by harness apply --runtime codex.",
  `# harness hook: ${RETIRED_ID} (budget_ms=2000)`,
  "[[hooks.PreToolUse]]",
  'matcher = "Bash"',
  `hooks = [{ type = "command", command = "harness pack hook ${RETIRED_ID}", timeout = 2 }]`,
];
const GENERATED = [
  "# Generated by harness apply --runtime codex.",
  "# harness hook: fresh (budget_ms=2000)",
  "[[hooks.PreToolUse]]",
  'matcher = "Bash"',
  'hooks = [{ type = "command", command = "harness pack hook fresh", timeout = 2 }]',
  "",
].join("\n");

/** A foreign table whose `args` array holds `element` on its own line. */
function foreignTableWithElement(element: string, header = "[mcp_servers.x]"): string[] {
  return [header, "args = [", element, "]"];
}

let home: string;
let codexConfig: string;
let manifestPath: string;

beforeEach(() => {
  home = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "harness-codex-array-header-"));
  codexConfig = path.join(home, ".codex", "config.toml");
  fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
  manifestPath = path.join(home, "harness.yaml");
  fs.writeFileSync(
    manifestPath,
    yamlStringify({
      version: 1,
      tools: { mcp: [], cli: [], skills: { enabled: [], source_dirs: [] }, builtin: { known: [] } },
      memory: { directories: [] },
      hooks: [],
      policies: [],
      policy_packs: [{ name: "understanding-before-execution" }],
    }),
  );
});

afterEach(() => {
  fs.rmSync(home, { recursive: true, force: true });
});

function write(lines: string[]): string {
  const body = lines.join("\n");
  fs.writeFileSync(codexConfig, body);
  return body;
}

/** The plan's operator-facing fields; the two content fields legitimately
 * hold the config's own text and are left out. */
function printedFields(p: ReturnType<typeof plan>): string {
  return JSON.stringify([p.summary, p.removedHookIds, p.foreignSectionsPreserved]);
}

function plan() {
  return planCodexConfigInstall({
    configPath: codexConfig,
    generatedPath: "/x/config.toml",
    generatedContent: GENERATED,
  });
}

interface CliRun {
  code: number;
  out: string;
  err: string;
}

async function cli(opts: { json?: boolean; dryRun?: boolean }): Promise<CliRun> {
  let out = "";
  let err = "";
  const code = await run({
    argv: [
      "apply",
      "--config",
      manifestPath,
      "--runtime",
      "codex",
      "--install",
      "--codex-config",
      codexConfig,
      ...(opts.dryRun ? ["--dry-run"] : []),
      ...(opts.json ? ["--json"] : []),
    ],
    stdout: (s: string) => {
      out += s;
    },
    stderr: (s: string) => {
      err += s;
    },
  });
  return { code, out, err };
}

/** Every output channel of the install for the config on disk: --dry-run
 * (stdout and stderr), --dry-run --json, and the real install's summary and
 * its --json form. Each entry is one stream's text; all must exit 0. The
 * real installs run last, since they rewrite the config. */
async function everyOutput(): Promise<string[]> {
  const runs = [
    await cli({ dryRun: true }),
    await cli({ dryRun: true, json: true }),
    await cli({}),
    await cli({ json: true }),
  ];
  for (const r of runs) expect(r.code).toBe(EX_OK);
  return runs.flatMap((r) => [r.out, r.err]);
}

/** Every value printed after "foreign section: " in the human output. */
function foreignSectionLines(out: string): string[] {
  return [...out.matchAll(/foreign section: (.*)$/gm)].map((m) => m[1] ?? "");
}

function jsonForeignSections(out: string): string[] {
  const parsed = JSON.parse(out) as { codexConfigInstall?: { foreignSectionsPreserved: string[] } };
  return parsed.codexConfigInstall?.foreignSectionsPreserved ?? [];
}

describe("codex install lists foreign sections without taking an array element for a table header (task 6b56d735)", () => {
  // Two ways the install reaches the foreign-section listing: no END marker
  // after the hook tables, and an END marker that sits past the foreign
  // table.
  const layouts: Array<[string, (element: string) => string[]]> = [
    ["no END marker", (el) => [...OLD_BLOCK, ...foreignTableWithElement(el), ""]],
    ["END marker past the foreign table", (el) => [...OLD_BLOCK, ...foreignTableWithElement(el), CODEX_MANAGED_END, ""]],
  ];
  for (const [layoutLabel, build] of layouts) {
    for (const shape of SHAPES) {
      it(`${layoutLabel}, ${shape.label}: the element is not a foreign section in the plan, --dry-run, the install summary or --json`, async () => {
        write(build(shape.element));
        expect(plan().foreignSectionsPreserved).toEqual(["[mcp_servers.x]"]);
        expect(printedFields(plan())).not.toContain(shape.text);

        const dry = await cli({ dryRun: true });
        expect(dry.code).toBe(EX_OK);
        expect(foreignSectionLines(dry.out)).toEqual(["[mcp_servers.x]"]);
        expect(dry.out).not.toContain(shape.text);
        expect(dry.err).not.toContain(shape.text);

        const json = await cli({ dryRun: true, json: true });
        expect(jsonForeignSections(json.out)).toEqual(["[mcp_servers.x]"]);
        expect(json.out).not.toContain(shape.text);

        const applied = await cli({});
        expect(applied.code).toBe(EX_OK);
        expect(foreignSectionLines(applied.out)).toEqual(["[mcp_servers.x]"]);
        expect(applied.out).not.toContain(shape.text);
        // The foreign table keeps its own lines, element included.
        expect(fs.readFileSync(codexConfig, "utf8")).toContain(shape.element);
      });
    }
  }

  it("an element that spells the name of a real table elsewhere in the file is still not a header", () => {
    write([
      ...OLD_BLOCK,
      ...foreignTableWithElement('  ["tui"]'),
      "[tui]",
      "theme = 1",
      "",
    ]);
    // A lookup of the element's key path in the parsed document would find
    // the real `[tui]` table and take the element for a second header,
    // printing `[tui.*] (2 tables)`.
    expect(plan().foreignSectionsPreserved).toEqual(["[mcp_servers.x]", "[tui]"]);
  });

  it("a real table that shares a number-like name with an element is still listed", () => {
    write([...OLD_BLOCK, ...foreignTableWithElement("  [1]"), "[1]", "v = 2", ""]);
    expect(plan().foreignSectionsPreserved).toEqual(["[mcp_servers.x]", "[1]"]);
  });

  // The array-continuation shapes below stress how "still inside a value"
  // is decided; the parser decides it, so none of them can confuse it.
  const trickyValues: Array<[string, string[], string]> = [
    ["a `]` inside a string on the line before the element", ["args = [", '  "]",', `  ["${TOKEN}"]`, "]"], TOKEN],
    ["a `[` inside a comment on the line before the element", ["args = [ # [", `  ["${TOKEN}"]`, "]"], TOKEN],
    ["the element after a closed multi-line string", ['note = """', "text", '"""', "args = [", `  ["${TOKEN}"]`, "]"], TOKEN],
    ["the element inside a multi-line string", ['note = """', `["${TOKEN}"]`, '"""'], TOKEN],
    ["an element in a multi-line inline table", ["meta = {", "  a = [", `    ["${TOKEN}"]`, "  ]", "}"], TOKEN],
  ];
  for (const [label, valueLines, text] of trickyValues) {
    it(`${label}: the element is not a foreign section`, () => {
      write([...OLD_BLOCK, "[mcp_servers.x]", ...valueLines, ""]);
      expect(plan().foreignSectionsPreserved).toEqual(["[mcp_servers.x]"]);
      expect(printedFields(plan())).not.toContain(text);
    });
  }
});

describe("codex install finds the end of the harness block across an array element (task 6b56d735)", () => {
  // An operator table sitting inside the harness block that holds a
  // multi-line array: the element must not end the harness block.
  const operatorTable = (element: string) => [
    "[[hooks.Stop]]",
    'hooks = [{ type = "command", command = "operator", timeout = 5 }]',
    "args = [",
    element,
    "]",
  ];

  for (const shape of SHAPES) {
    it(`${shape.label}: a foreign table after the element still ends the harness block, and a hook table after the element is still recognized`, async () => {
      write([
        ...OLD_BLOCK,
        ...operatorTable(shape.element),
        "# harness hook: late-retired (budget_ms=2000)",
        "[[hooks.PostToolUse]]",
        'matcher = "Bash"',
        'hooks = [{ type = "command", command = "harness pack hook late-retired", timeout = 2 }]',
        "[tui]",
        "theme = 1",
        "",
      ]);
      const p = plan();
      // Both stale hook blocks are named, the second one because it sits
      // after the element line.
      expect(p.removedHookIds).toEqual([RETIRED_ID, "late-retired"]);
      expect(p.foreignSectionsPreserved).toEqual(["[tui]"]);
      expect(p.nextContent.endsWith(`${CODEX_MANAGED_END}\n[tui]\ntheme = 1\n`)).toBe(true);
      expect(p.nextContent).not.toContain("late-retired");
      expect(p.nextContent).not.toContain(shape.element);

      for (const output of await everyOutput()) expect(output).not.toContain(shape.text);
    });

    it(`${shape.label}: with the END marker after the element, the block ends at that marker`, async () => {
      write([
        ...OLD_BLOCK,
        ...operatorTable(shape.element),
        CODEX_MANAGED_END,
        "[tui]",
        "theme = 1",
        "",
      ]);
      const p = plan();
      expect(p.nextContent.endsWith(`${CODEX_MANAGED_END}\n[tui]\ntheme = 1\n`)).toBe(true);
      expect(p.nextContent).not.toContain(shape.element);
      expect(p.foreignSectionsPreserved).toEqual([]);
      for (const output of await everyOutput()) expect(output).not.toContain(shape.text);
    });
  }
});

describe("codex install decides header recognition with the parser, not with indentation (task 6b56d735)", () => {
  // An element line with no leading whitespace: the same shape as a real
  // top-level header, told apart only by what is open before it.
  const bareElement = `["${TOKEN}"]`;

  const layouts: Array<[string, string[]]> = [
    ["no END marker", [...OLD_BLOCK, ...foreignTableWithElement(bareElement), ""]],
    [
      "END marker past the foreign table",
      [...OLD_BLOCK, ...foreignTableWithElement(bareElement), CODEX_MANAGED_END, ""],
    ],
  ];
  for (const [label, lines] of layouts) {
    it(`${label}: an unindented element in a foreign args array is not listed and its text never prints`, async () => {
      write(lines);
      expect(plan().foreignSectionsPreserved).toEqual(["[mcp_servers.x]"]);
      expect(printedFields(plan())).not.toContain(TOKEN);
      for (const output of await everyOutput()) expect(output).not.toContain(TOKEN);
      expect(fs.readFileSync(codexConfig, "utf8")).toContain(`\n${bareElement}\n`);
    });
  }

  it("an unindented element inside an owned hook table does not end the block: the hook after it is recognized", async () => {
    write([
      ...OLD_BLOCK,
      "[[hooks.Stop]]",
      'hooks = [{ type = "command", command = "operator", timeout = 5 }]',
      "args = [",
      bareElement,
      "]",
      "# harness hook: late-retired (budget_ms=2000)",
      "[[hooks.PostToolUse]]",
      'matcher = "Bash"',
      'hooks = [{ type = "command", command = "harness pack hook late-retired", timeout = 2 }]',
      "[tui]",
      "theme = 1",
      "",
    ]);
    const p = plan();
    expect(p.removedHookIds).toEqual([RETIRED_ID, "late-retired"]);
    expect(p.foreignSectionsPreserved).toEqual(["[tui]"]);
    expect(p.nextContent.endsWith(`${CODEX_MANAGED_END}\n[tui]\ntheme = 1\n`)).toBe(true);
    for (const output of await everyOutput()) expect(output).not.toContain(TOKEN);
  });

  it("an indented real header after a block with no END marker is listed and kept", () => {
    write([...OLD_BLOCK, "  [tui]", "  theme = 1", ""]);
    const p = plan();
    expect(p.foreignSectionsPreserved).toEqual(["[tui]"]);
    expect(p.nextContent.endsWith(`${CODEX_MANAGED_END}\n  [tui]\n  theme = 1\n`)).toBe(true);
    expect(p.nextContent).not.toContain(RETIRED_ID);
  });
});

describe("codex install split-block refusal never names an array element as the foreign table (task 6b56d735)", () => {
  // A hook table with a multi-line array, then a marker comment and more
  // harness content. With the element read as a header the install refused
  // and printed the element as the foreign table; it is not a header, so the
  // harness block simply runs on through it and the install succeeds.
  for (const shape of SHAPES) {
    it(`${shape.label}: no refusal and no element text on stderr, stdout, --dry-run or --json`, async () => {
      write([
        ...OLD_BLOCK.slice(0, 3),
        "# operator note",
        "# harness hook: wedged (budget_ms=2000)",
        "[[hooks.Stop]]",
        'hooks = [{ type = "command", command = "operator", timeout = 5 }]',
        "args = [",
        shape.element,
        "]",
        "# harness hook: more (budget_ms=2000)",
        "[[hooks.Stop]]",
        'hooks = [{ type = "command", command = "harness pack hook more", timeout = 2 }]',
        "",
      ]);
      for (const output of await everyOutput()) {
        expect(output).not.toContain(shape.text);
      }
    });
  }

  it("a real foreign table before more harness content is still refused and named", () => {
    const body = write([...OLD_BLOCK, "[tui]", "theme = 1", "", ...OLD_BLOCK.slice(3), ""]);
    let message = "";
    try {
      plan();
    } catch (e) {
      expect(e).toBeInstanceOf(CodexInstallRefusalError);
      message = (e as Error).message;
    }
    expect(message).toContain("foreign table ([tui])");
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(body);
  });

  // The refusal's own naming rule, called directly: the scan never hands it
  // an element line, so this is the only way to reach that rule with one.
  function refusalFor(text: string, from: number): string {
    try {
      assertNoSplitBlock(text, from, text.length, "/cfg/config.toml", false);
    } catch (e) {
      expect(e).toBeInstanceOf(CodexInstallRefusalError);
      return (e as Error).message;
    }
    throw new Error("expected a refusal");
  }

  for (const shape of SHAPES) {
    it(`${shape.label}: a header-shaped element line is named by its line number, never by its text`, () => {
      const text = ["x = [", shape.element, "]", "# harness hook: a (budget_ms=1)", ""].join("\n");
      const message = refusalFor(text, text.indexOf(shape.element));
      expect(message).toContain("foreign table (line 2)");
      expect(message).not.toContain(shape.text);
    });
  }

  it("a real header is named by its bracketed key path, a comment on it dropped", () => {
    const text = ["[tui] # note", "x = 1", "# harness hook: a (budget_ms=1)", ""].join("\n");
    expect(refusalFor(text, 0)).toContain("foreign table ([tui])");
  });

  it("a content line that is no header at all stays unnamed", () => {
    const text = ["x = 1", "# harness hook: a (budget_ms=1)", ""].join("\n");
    expect(refusalFor(text, 0)).toContain("foreign table ((unknown))");
  });
});
