import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { CodexInstallRefusalError, planCodexConfigInstall } from "../../../src/cli/apply/index.js";

// Pins what the TOML parser behind the Codex config read accepts and refuses
// (task f73524e0). smol-toml 1.9.0 rewrote its parser: a malformed `[[table]`
// header that 1.8.0 read is refused, and a leading byte order mark is
// accepted. A dependency bump that changes either shows up here.

const FRESH = [
  "# Generated by harness apply --runtime codex.",
  "# harness hook: a (budget_ms=2000)",
  "[[hooks.PreToolUse]]",
  'matcher = "Bash"',
  'hooks = [{ type = "command", command = "harness pack hook a", timeout = 2 }]',
  "",
].join("\n");

let home: string;
let codexConfig: string;

beforeEach(() => {
  home = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "harness-codex-toml-pins-"));
  codexConfig = path.join(home, ".codex", "config.toml");
  fs.mkdirSync(path.dirname(codexConfig), { recursive: true });
});

afterEach(() => {
  fs.rmSync(home, { recursive: true, force: true });
});

function plan() {
  return planCodexConfigInstall({
    configPath: codexConfig,
    generatedPath: "/x/config.toml",
    generatedContent: FRESH,
  });
}

describe("codex install: TOML parser refusals and acceptances are pinned (task f73524e0)", () => {
  it("refuses a malformed [[hooks.Stop] header with the parser's line, column and reason", () => {
    const body = '[[hooks.Stop]\nmatcher = "Bash"\n';
    fs.writeFileSync(codexConfig, body);
    let caught: unknown;
    try {
      plan();
    } catch (err) {
      caught = err;
    }
    expect(caught).toBeInstanceOf(CodexInstallRefusalError);
    const message = (caught as Error).message;
    expect(message).toContain("the TOML parser used by harness could not read this file");
    expect(message).toContain("(line 1, column 14: expected end of table array declaration)");
    // The refusal leaves the file untouched.
    expect(fs.readFileSync(codexConfig, "utf8")).toBe(body);
  });

  it("accepts a config with a leading byte order mark and keeps its tables", () => {
    fs.writeFileSync(codexConfig, '﻿[mcp_servers.docs]\ncommand = "docs-server"\n');
    const result = plan();
    expect(result.changed).toBe(true);
    expect(result.nextContent).toContain("[mcp_servers.docs]");
    expect(result.nextContent).toContain("[[hooks.PreToolUse]]");
  });
});
