import { describe, expect, it } from "vitest";
import {
  CODEX_GENERATED_HEADER_LINE,
  generateCodexConfig,
} from "../../../src/cli/apply/generate-codex-config.js";
import { parseManifest, type Manifest } from "../../../src/schema/index.js";

function manifest(extra: Record<string, unknown> = {}): Manifest {
  return parseManifest({
    version: 1,
    hooks: [
      {
        name: "policy-pack:understanding-before-execution:codex:pre-tool-use",
        event: "PreToolUse",
        match: "apply_patch|Bash|shell|exec_command|functions.exec_command",
        command: "harness pack hook codex-pre-tool-use",
        blocking: "hard",
        budget_ms: 5000,
        description: "Codex blocker",
      },
      {
        name: "policy-pack:understanding-before-execution:codex:user-prompt-submit",
        event: "UserPromptSubmit",
        command: "harness pack hook codex-user-prompt-submit",
        blocking: false,
        budget_ms: 5000,
      },
    ],
    ...extra,
  });
}

describe("generateCodexConfig", () => {
  it("emits CODEX_GENERATED_HEADER_LINE as the first line (apply's recovery branch pin)", () => {
    // src/cli/apply/apply.ts:recoverMissingLastApplyContent detects a
    // harness-generated codex artefact by `onDisk.startsWith(CODEX_GENERATED_HEADER_LINE)`.
    // If the generator's banner ever drifts away from this literal,
    // recovery silently disables and post-migration codex applies start
    // refusing again. Pin the link explicitly so a banner re-word fails
    // here loud instead of in a future operator's dogfood.
    const { content } = generateCodexConfig(manifest());
    expect(content.startsWith(CODEX_GENERATED_HEADER_LINE)).toBe(true);
  });

  it("emits a header banner and one TOML stanza per hook", () => {
    const { content, warnings } = generateCodexConfig(manifest());
    expect(warnings).toEqual([]);
    expect(content).toContain("Generated by harness apply --runtime codex");
    expect(content).toContain("[[hooks.PreToolUse]]");
    expect(content).toContain("[[hooks.UserPromptSubmit]]");
    expect(content).toContain(
      "# harness hook: policy-pack:understanding-before-execution:codex:pre-tool-use (budget_ms=5000)",
    );
    expect(content).toContain(
      'hooks = [{ type = "command", command = "harness pack hook codex-pre-tool-use", timeout = 5 }]',
    );
    expect(content).toContain(
      'matcher = "apply_patch|Bash|shell|exec_command|functions.exec_command"',
    );
    expect(content).not.toContain("timeout_ms = ");
    expect(content).not.toContain("blocking = ");
    expect(content).not.toContain("name = ");
    expect(content).not.toContain("description = ");
  });

  it("emits Codex protocol event names as hook table keys", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "stop-hook",
            event: "Stop",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
          },
          {
            name: "session-start-hook",
            event: "SessionStart",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
          },
          {
            name: "post-tool-hook",
            event: "PostToolUse",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain("[[hooks.Stop]]");
    expect(content).toContain("[[hooks.SessionStart]]");
    expect(content).toContain("[[hooks.PostToolUse]]");
    expect(content).not.toContain("[[hooks.stop]]");
    expect(content).not.toContain("[[hooks.session_start]]");
    expect(content).not.toContain("[[hooks.post_tool_use]]");
  });

  it("expands Claude-style tool names to Codex hook match aliases", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "policy-intercept-shell",
            event: "PreToolUse",
            match: "Bash",
            command: "harness policy intercept",
            blocking: "hard",
            budget_ms: 1000,
          },
          {
            name: "policy-intercept-agent-tasks",
            event: "PreToolUse",
            match: "mcp__agent-tasks__pull_requests_create",
            command: "harness policy intercept",
            blocking: "hard",
            budget_ms: 1000,
          },
        ],
      }),
    );

    expect(content).toContain(
      'matcher = "Bash|shell|exec_command|functions.exec_command"',
    );
    expect(content).toContain(
      'matcher = "mcp__agent-tasks__pull_requests_create|mcp__agent-tasks__.pull_requests_create|mcp__agent_tasks__pull_requests_create|mcp__agent_tasks__.pull_requests_create"',
    );
    expect(content).toContain(
      "# harness hook: policy-intercept-shell (budget_ms=1000)",
    );
    expect(content).toContain(
      'hooks = [{ type = "command", command = "harness policy intercept --hook policy-intercept-shell", timeout = 2 }]',
    );
    expect(content).toContain(
      'hooks = [{ type = "command", command = "harness policy intercept --hook policy-intercept-agent-tasks", timeout = 2 }]',
    );
  });

  it("keeps the 2s policy-intercept floor when budget_ms ceil already meets it", () => {
    // Guards against a regression where the timeout floor would shadow
    // (rather than coexist with) a legitimate >=2000ms budget. The
    // intercept hooks at 2000ms must still surface as timeout=2, not be
    // floored back down to 2 by accident (Math.max picks the larger).
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "policy-intercept-shell",
            event: "PreToolUse",
            match: "Bash",
            command: "harness policy intercept",
            blocking: "hard",
            budget_ms: 2000,
          },
        ],
      }),
    );
    expect(content).toContain(
      'hooks = [{ type = "command", command = "harness policy intercept --hook policy-intercept-shell", timeout = 2 }]',
    );
  });

  it("does NOT append --hook to non-policy-intercept commands", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "memory-router-style",
            event: "UserPromptSubmit",
            command: "memory-router-user-prompt-submit",
            blocking: false,
            budget_ms: 5000,
          },
        ],
      }),
    );
    expect(content).toContain(
      'hooks = [{ type = "command", command = "memory-router-user-prompt-submit", timeout = 5 }]',
    );
    expect(content).not.toContain("--hook");
  });

  it("skips --hook injection when the hook name contains unsafe characters", () => {
    // Defence: Hook.name schema is z.string().min(1); an exotic value
    // ("space in name", "weird;name") would otherwise slip into the
    // emitted command literal and break shell parsing. The fallback is
    // the un-tagged emission; the preceding TOML comment still names it.
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "weird;name with space",
            event: "PreToolUse",
            match: "Bash",
            command: "harness policy intercept",
            blocking: "hard",
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain(
      'hooks = [{ type = "command", command = "harness policy intercept", timeout = 2 }]',
    );
    expect(content).not.toContain("--hook");
  });

  it("converts manifest millisecond budgets to Codex timeout seconds", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "round-up",
            event: "SessionStart",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1501,
          },
        ],
      }),
    );
    expect(content).toContain('command = "/bin/true", timeout = 2');
  });

  it("keeps non-policy 1000ms hooks at Codex's 1s minimum", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "fast-non-policy",
            event: "PreToolUse",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain('command = "/bin/true", timeout = 1');
  });

  it("is byte-stable for a given manifest (regenerable on no-op apply)", () => {
    const a = generateCodexConfig(manifest()).content;
    const b = generateCodexConfig(manifest()).content;
    expect(a).toBe(b);
  });

  it("warns when the manifest has no hooks", () => {
    const { content, warnings } = generateCodexConfig(
      parseManifest({ version: 1, hooks: [] }),
    );
    expect(warnings.length).toBe(1);
    expect(warnings[0]).toMatch(/no hooks/);
    expect(content).toContain("Generated by harness apply --runtime codex");
  });

  it("escapes embedded double-quotes in TOML strings", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "weird",
            event: "PreToolUse",
            match: 'has "quotes"',
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain('matcher = "has \\"quotes\\""');
  });

  it("escapes raw control characters in nested command hooks", () => {
    const SOH = String.fromCharCode(0x01);
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "controls",
            event: "PreToolUse",
            command: `/bin/true\n${SOH}`,
            description: `line1\nline2${SOH}end`,
            blocking: false,
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain('command = "/bin/true\\n\\u0001"');
    // The emitted TOML basic-string carries no raw control chars.
    const commandLine = content
      .split("\n")
      .find((l) => l.includes('command = "/bin/true'));
    expect(commandLine).toBeDefined();
    const controlRe = new RegExp("[\\u0000-\\u001f\\u007f]");
    expect(controlRe.test(commandLine!)).toBe(false);
  });

  it("warns when a hook carries path_match or bash_match (not projected)", () => {
    const { warnings } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "with-filter",
            event: "PreToolUse",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
            path_match: "src/**/*.ts",
            bash_match: "^git push",
          },
        ],
      }),
    );
    expect(warnings.some((w) => w.includes("path_match"))).toBe(true);
    expect(warnings.some((w) => w.includes("bash_match"))).toBe(true);
  });

  it("projects memory.router into a user_prompt_submit hook (PR #203)", () => {
    // Codex parity with generate-settings.ts: per-prompt memory
    // augmentation must wire on both runtimes, otherwise a Codex
    // operator who uses memory-router would silently lose the feature.
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        memory: {
          directories: [],
          router: { command: ["memory-router-user-prompt-submit"] },
        },
      }),
    );
    expect(content).toContain("[[hooks.UserPromptSubmit]]");
    expect(content).toContain('command = "memory-router-user-prompt-submit"');
    expect(content).toContain("timeout = 5");
  });

  it("omits memory.router from codex config when enabled:false", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        memory: {
          directories: [],
          router: {
            command: ["memory-router-user-prompt-submit"],
            enabled: false,
          },
        },
      }),
    );
    expect(content).not.toContain("memory-router-user-prompt-submit");
    expect(content).not.toContain("memory:router");
  });
});
