import { describe, expect, it } from "vitest";
import { generateCodexConfig } from "../../../src/cli/apply/generate-codex-config.js";
import { parseManifest, type Manifest } from "../../../src/schema/index.js";

function manifest(extra: Record<string, unknown> = {}): Manifest {
  return parseManifest({
    version: 1,
    hooks: [
      {
        name: "policy-pack:understanding-before-execution:codex:pre-tool-use",
        event: "PreToolUse",
        match: "apply_patch|Bash|shell",
        command: "harness pack hook codex-pre-tool-use",
        blocking: "hard",
        budget_ms: 5000,
        description: "Codex blocker",
      },
      {
        name: "policy-pack:understanding-before-execution:codex:user-prompt-submit",
        event: "UserPromptSubmit",
        command: "harness pack hook codex-user-prompt-submit",
        blocking: false,
        budget_ms: 5000,
      },
    ],
    ...extra,
  });
}

describe("generateCodexConfig", () => {
  it("emits a header banner and one TOML stanza per hook", () => {
    const { content, warnings } = generateCodexConfig(manifest());
    expect(warnings).toEqual([]);
    expect(content).toContain("Generated by harness apply --runtime codex");
    expect(content).toContain("[[hooks.pre_tool_use]]");
    expect(content).toContain("[[hooks.user_prompt_submit]]");
    expect(content).toContain('command = "harness pack hook codex-pre-tool-use"');
    expect(content).toContain('match = "apply_patch|Bash|shell"');
    expect(content).toContain("timeout_ms = 5000");
    expect(content).toContain("blocking = true");
  });

  it("snake_cases known event names", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "stop-hook",
            event: "Stop",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain("[[hooks.stop]]");
  });

  it("is byte-stable for a given manifest (regenerable on no-op apply)", () => {
    const a = generateCodexConfig(manifest()).content;
    const b = generateCodexConfig(manifest()).content;
    expect(a).toBe(b);
  });

  it("warns when the manifest has no hooks", () => {
    const { content, warnings } = generateCodexConfig(parseManifest({ version: 1, hooks: [] }));
    expect(warnings.length).toBe(1);
    expect(warnings[0]).toMatch(/no hooks/);
    expect(content).toContain("Generated by harness apply --runtime codex");
  });

  it("escapes embedded double-quotes in TOML strings", () => {
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "weird",
            event: "PreToolUse",
            match: 'has "quotes"',
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain('match = "has \\"quotes\\""');
  });

  it("escapes raw control characters as \\uXXXX or shorthand forms", () => {
    const SOH = String.fromCharCode(0x01);
    const { content } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "controls",
            event: "PreToolUse",
            command: "/bin/true",
            description: `line1\nline2${SOH}end`,
            blocking: false,
            budget_ms: 1000,
          },
        ],
      }),
    );
    expect(content).toContain('description = "line1\\nline2\\u0001end"');
    // The emitted TOML basic-string carries no raw control chars.
    const descriptionLine = content
      .split("\n")
      .find((l) => l.startsWith("description = "));
    expect(descriptionLine).toBeDefined();
    const controlRe = new RegExp("[\\u0000-\\u001f\\u007f]");
    expect(controlRe.test(descriptionLine!)).toBe(false);
  });

  it("warns when a hook carries path_match or bash_match (not projected)", () => {
    const { warnings } = generateCodexConfig(
      parseManifest({
        version: 1,
        hooks: [
          {
            name: "with-filter",
            event: "PreToolUse",
            command: "/bin/true",
            blocking: false,
            budget_ms: 1000,
            path_match: "src/**/*.ts",
            bash_match: "^git push",
          },
        ],
      }),
    );
    expect(warnings.some((w) => w.includes("path_match"))).toBe(true);
    expect(warnings.some((w) => w.includes("bash_match"))).toBe(true);
  });
});
