import { describe, expect, it } from "vitest";
import {
  OPENCODE_GENERATED_HEADER_LINE,
  generateOpencodeConfig,
} from "../../../src/cli/apply/generate-opencode-config.js";
import { EVIDENCE_LEDGER_DB_ENV } from "../../../src/cli/apply/generate-settings.js";
import { parseManifest, type Manifest } from "../../../src/schema/index.js";

// Canonical manifest used by the "runs against a real manifest" +
// byte-stability tests, analogous to generate-codex-config.test.ts's
// `manifest()` helper. Covers hooks (must NOT be projected), an MCP
// server (must be projected), and memory.router (must NOT be projected).
function canonicalManifest(extra: Record<string, unknown> = {}): Manifest {
  return parseManifest({
    version: 1,
    tools: {
      mcp: [
        {
          name: "grounding-mcp",
          command: ["grounding-mcp-server"],
        },
        {
          name: "agent-tasks",
          command: "agent-tasks-mcp-bridge --stdio",
          env: { AGENT_TASKS_TOKEN: "secret" },
        },
      ],
    },
    memory: {
      directories: [],
      router: { command: ["memory-router-user-prompt-submit"] },
    },
    hooks: [
      {
        name: "policy-pack:understanding-before-execution:pre-tool-use",
        event: "PreToolUse",
        match: "Bash",
        command: "harness policy intercept",
        blocking: "hard",
        budget_ms: 5000,
      },
    ],
    ...extra,
  });
}

describe("generateOpencodeConfig", () => {
  it("emits OPENCODE_GENERATED_HEADER_LINE as the first line", () => {
    const { content } = generateOpencodeConfig(canonicalManifest(), {
      homeDir: "/home/op",
    });
    expect(content.startsWith(OPENCODE_GENERATED_HEADER_LINE)).toBe(true);
  });

  it("runs against a canonical manifest and projects tools.mcp[] into opencode's local MCP shape", () => {
    const { content, mcp } = generateOpencodeConfig(canonicalManifest(), {
      homeDir: "/home/op",
    });
    expect(content).toContain("Generated by harness apply --runtime opencode");
    expect(content).toContain('"$schema": "https://opencode.ai/config.json"');

    // Structured result: opencode's McpLocalConfig shape.
    expect(mcp["agent-tasks"]).toEqual({
      type: "local",
      command: ["agent-tasks-mcp-bridge", "--stdio"],
      environment: { AGENT_TASKS_TOKEN: "secret" },
    });
    expect(mcp["grounding-mcp"]?.type).toBe("local");
    expect(mcp["grounding-mcp"]?.command).toEqual(["grounding-mcp-server"]);
    expect(mcp["grounding-mcp"]?.environment?.[EVIDENCE_LEDGER_DB_ENV]).toBe(
      "/home/op/.evidence-ledger/ledger.db",
    );

    // The JSON body carries the same data (parseable once the leading
    // `//` banner comments are stripped -- opencode.json is JSONC).
    const jsonBody = content
      .split("\n")
      .filter((l) => !l.startsWith("//"))
      .join("\n");
    const parsed = JSON.parse(jsonBody) as { mcp: Record<string, unknown> };
    expect(parsed.mcp["agent-tasks"]).toEqual({
      type: "local",
      command: ["agent-tasks-mcp-bridge", "--stdio"],
      environment: { AGENT_TASKS_TOKEN: "secret" },
    });
  });

  it("sorts mcp server keys ascending by name (stable-output rule)", () => {
    const { content } = generateOpencodeConfig(canonicalManifest(), {
      homeDir: "/home/op",
    });
    const agentTasksIdx = content.indexOf('"agent-tasks"');
    const groundingIdx = content.indexOf('"grounding-mcp"');
    expect(agentTasksIdx).toBeGreaterThan(-1);
    expect(groundingIdx).toBeGreaterThan(-1);
    expect(agentTasksIdx).toBeLessThan(groundingIdx);
  });

  it("does NOT project manifest hooks[] and warns instead", () => {
    const { content, warnings } = generateOpencodeConfig(canonicalManifest(), {
      homeDir: "/home/op",
    });
    expect(content).not.toContain("harness policy intercept");
    expect(content).not.toContain("PreToolUse");
    expect(
      warnings.some(
        (w) => w.includes("1 hook(s)") && w.includes("no declarative hook wiring"),
      ),
    ).toBe(true);
  });

  it("does NOT project memory.router and warns instead", () => {
    const { content, warnings } = generateOpencodeConfig(canonicalManifest(), {
      homeDir: "/home/op",
    });
    expect(content).not.toContain("memory-router-user-prompt-submit");
    expect(warnings.some((w) => w.includes("memory.router"))).toBe(true);
  });

  it("omits memory.router warning when enabled:false", () => {
    const { warnings } = generateOpencodeConfig(
      parseManifest({
        version: 1,
        memory: {
          directories: [],
          router: {
            command: ["memory-router-user-prompt-submit"],
            enabled: false,
          },
        },
      }),
    );
    expect(warnings.some((w) => w.includes("memory.router"))).toBe(false);
  });

  it("omits the `mcp` key entirely when there are no enabled MCP servers", () => {
    const { content, mcp } = generateOpencodeConfig(
      parseManifest({ version: 1 }),
    );
    expect(mcp).toEqual({});
    // The banner comment mentions the string "mcp" in prose (how to wire
    // the file in), so assert against the parsed JSON body instead of
    // raw substring-matching `content` (which would false-negative on
    // the banner text alone).
    const jsonBody = content
      .split("\n")
      .filter((l) => !l.startsWith("//"))
      .join("\n");
    const parsed = JSON.parse(jsonBody) as Record<string, unknown>;
    expect(parsed).not.toHaveProperty("mcp");
    expect(parsed).toEqual({ "$schema": "https://opencode.ai/config.json" });
  });

  it("warns when every tools.mcp[] entry is disabled", () => {
    const { warnings, mcp } = generateOpencodeConfig(
      parseManifest({
        version: 1,
        tools: {
          mcp: [{ name: "off", command: "x", enabled: false }],
        },
      }),
    );
    expect(mcp).toEqual({});
    expect(warnings.some((w) => w.includes("disabled"))).toBe(true);
  });

  it("does not warn about hooks when the manifest has none", () => {
    const { warnings } = generateOpencodeConfig(
      parseManifest({ version: 1, hooks: [] }),
    );
    expect(warnings.some((w) => w.includes("hook"))).toBe(false);
  });

  it("is byte-stable for a given manifest (regenerable on no-op apply)", () => {
    const a = generateOpencodeConfig(canonicalManifest(), { homeDir: "/home/op" }).content;
    const b = generateOpencodeConfig(canonicalManifest(), { homeDir: "/home/op" }).content;
    expect(a).toBe(b);
  });

  it("forwards the literal-tilde EVIDENCE_LEDGER_DB warning from buildMcpServers", () => {
    const { warnings } = generateOpencodeConfig(
      parseManifest({
        version: 1,
        tools: {
          mcp: [
            {
              name: "grounding-mcp",
              command: "grounding-mcp-server",
              env: { EVIDENCE_LEDGER_DB: "~/.evidence-ledger/ledger.db" },
            },
          ],
        },
      }),
      { homeDir: "/home/op" },
    );
    expect(warnings.some((w) => w.includes("starts with a literal ~"))).toBe(true);
  });
});
