export * from "./schema/index.js";
export * from "./overrides/index.js";
export { describe, isPillar, type DescribeOptions, type DescribeResult, type Pillar } from "./cli/describe.js";
export { loadManifest, loadMergedRaw, resolvePaths, type LoaderOptions } from "./cli/loader.js";
export { HarnessExitError, EX_NOINPUT, EX_USAGE, EX_SOFTWARE } from "./cli/exit-codes.js";
export { validate, formatReport, runAssetChecks, fmtDiagnostic, type Diagnostic } from "./cli/validate/index.js";
export { doctor, type DoctorOptions } from "./cli/doctor/index.js";
export { format as formatDoctor } from "./cli/doctor/format.js";
export { RealMcpProbe, type McpProbe, type McpProbeResult } from "./probes/mcp.js";
export { inspectMemory, type MemoryReport, type StaleMemory } from "./probes/memory.js";
